import { createClient } from 'jsr:@supabase/supabase-js@2'
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'}
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,'Content-Type':'application/json'}})
type Role='owner'|'manager'|'sales'|'finance'|'delivery';const roles:Role[]=['owner','manager','sales','finance','delivery']
const normalizeWhatsapp=(value:unknown)=>{const raw=String(value||'').trim();if(!raw)return null;const digits=raw.replace(/\D/g,'');return digits?`+${digits}`:null}
Deno.serve(async(req)=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'Method not allowed'},405)
 const token=(req.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'');if(!token)return json({error:'Unauthorized'},401)
 const admin=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{autoRefreshToken:false,persistSession:false}})
 const{data:userData,error:userError}=await admin.auth.getUser(token);if(userError||!userData.user)return json({error:'Unauthorized'},401)
 const callerId=userData.user.id;const{data:callerProfile}=await admin.from('profiles').select('role,full_name,manager_scope').eq('id',callerId).single()
 if(!callerProfile||!['owner','manager'].includes(callerProfile.role))return json({error:'Owner or manager access required'},403)
 const callerRole=callerProfile.role as Role, managerScope=callerProfile.manager_scope as string|null
 let body:Record<string,unknown>;try{body=await req.json()}catch{return json({error:'Invalid JSON'},400)};const action=String(body.action||'')
 const allowedIds=async()=>{if(callerRole==='owner'||(callerRole==='manager'&&managerScope==='store'))return null;const{data:teams}=await admin.from('sales_teams').select('id').eq('manager_id',callerId).eq('active',true);const ids=(teams||[]).map(t=>t.id);if(!ids.length)return new Set([callerId]);const{data:members}=await admin.from('sales_team_members').select('profile_id').in('team_id',ids);return new Set([callerId,...(members||[]).map(m=>m.profile_id)])}
 if(action==='list'){
  const scope=await allowedIds();const[{data:profileRows,error:profileError},{data:authData,error:authError}]=await Promise.all([admin.from('profiles').select('id,full_name,role,whatsapp,created_at,manager_scope').order('created_at',{ascending:true}),admin.auth.admin.listUsers({page:1,perPage:1000})]);if(profileError)return json({error:profileError.message},400);if(authError)return json({error:authError.message},400)
  const profiles=new Map((profileRows||[]).map(p=>[p.id,p]));const users=authData.users.filter(u=>!scope||scope.has(u.id)).map(u=>{const p=profiles.get(u.id) as any;return{id:u.id,email:u.email||'',full_name:p?.full_name||u.user_metadata?.full_name||'',role:(p?.role||u.user_metadata?.role||'sales') as Role,whatsapp:p?.whatsapp||'',manager_scope:p?.manager_scope||null,active:!u.banned_until||new Date(u.banned_until).getTime()<=Date.now(),created_at:u.created_at,last_sign_in_at:u.last_sign_in_at||null}});return json({users,callerRole,managerScope})
 }
 if(callerRole!=='owner')return json({error:'Owner access required for employee changes'},403)
 const ensureNotLastOwner=async(targetId:string,nextRole:Role|null,nextActive:boolean|null)=>{const{data:target}=await admin.from('profiles').select('role').eq('id',targetId).maybeSingle();if(target?.role!=='owner')return null;const removes=(nextRole!==null&&nextRole!=='owner')||nextActive===false;if(!removes)return null;const{count}=await admin.from('profiles').select('id',{count:'exact',head:true}).eq('role','owner');return(count||0)<=1?'The last owner cannot be disabled or downgraded':null}
 if(action==='create'){const email=String(body.email||'').trim().toLowerCase(),password=String(body.password||''),fullName=String(body.full_name||'').trim(),role=String(body.role||'sales') as Role,whatsapp=normalizeWhatsapp(body.whatsapp),scope=role==='manager'?String(body.manager_scope||'sales_team'):null;if(!email||!email.includes('@'))return json({error:'Valid email is required'},400);if(password.length<8)return json({error:'Password must be at least 8 characters'},400);if(!fullName)return json({error:'Full name is required'},400);if(!roles.includes(role))return json({error:'Invalid role'},400);if(scope&&!['sales_team','store'].includes(scope))return json({error:'Invalid manager scope'},400);const{data,error}=await admin.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{full_name:fullName,role}});if(error||!data.user)return json({error:error?.message||'Could not create user'},400);const{error:profileError}=await admin.from('profiles').upsert({id:data.user.id,full_name:fullName,role,whatsapp,manager_scope:scope},{onConflict:'id'});if(profileError){await admin.auth.admin.deleteUser(data.user.id);return json({error:profileError.message},400)}return json({ok:true,id:data.user.id})}
 if(action==='update'){const targetId=String(body.user_id||''),fullName=String(body.full_name||'').trim(),role=String(body.role||'') as Role,active=Boolean(body.active),whatsapp=normalizeWhatsapp(body.whatsapp),scope=role==='manager'?String(body.manager_scope||'sales_team'):null;if(!targetId||!fullName||!roles.includes(role))return json({error:'Invalid user update'},400);if(scope&&!['sales_team','store'].includes(scope))return json({error:'Invalid manager scope'},400);const ownerError=await ensureNotLastOwner(targetId,role,active);if(ownerError)return json({error:ownerError},400);const{error:authError}=await admin.auth.admin.updateUserById(targetId,{ban_duration:active?'none':'876000h',user_metadata:{full_name:fullName,role}});if(authError)return json({error:authError.message},400);const{error:profileError}=await admin.from('profiles').update({full_name:fullName,role,whatsapp,manager_scope:scope}).eq('id',targetId);if(profileError)return json({error:profileError.message},400);return json({ok:true})}
 if(action==='set_password'){const targetId=String(body.user_id||''),password=String(body.password||'');if(!targetId||password.length<8)return json({error:'Password must be at least 8 characters'},400);const{error}=await admin.auth.admin.updateUserById(targetId,{password});if(error)return json({error:error.message},400);return json({ok:true})}
 return json({error:'Unknown action'},400)
})