import { useEffect,useMemo,useState } from 'react'
import { BarChart3,Eye,Heart,MessageCircle,Share2,Users,Video } from 'lucide-react'
import { supabase } from '../lib/supabase'
import type { Lang } from '../lib/modules'

type VideoRow={profile_id:string;video_id:string;title:string|null;video_description:string|null;create_time:string|null;view_count:number|null;like_count:number|null;comment_count:number|null;share_count:number|null}
type AccountRow={profile_id:string;display_name:string|null;username:string|null}
type ProfileRow={id:string;full_name:string|null}
const iso=(d:Date)=>d.toISOString().slice(0,10)
const compact=(v:number)=>new Intl.NumberFormat('en-US',{notation:v>=10000?'compact':'standard',maximumFractionDigits:1}).format(v)
export default function ContentCommandSummary({lang}:{lang:Lang}){
 const zh=lang==='zh',now=new Date();const [start,setStart]=useState(iso(new Date(now.getFullYear(),now.getMonth(),1))),[end,setEnd]=useState(iso(now)),[videos,setVideos]=useState<VideoRow[]>([]),[accounts,setAccounts]=useState<AccountRow[]>([]),[profiles,setProfiles]=useState<ProfileRow[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('')
 const load=async()=>{try{setLoading(true);setError('');if(!supabase)throw new Error('Supabase not configured');const [{data:v,error:ve},{data:a,error:ae},{data:p,error:pe}]=await Promise.all([supabase.from('tiktok_videos').select('profile_id,video_id,title,video_description,create_time,view_count,like_count,comment_count,share_count').gte('create_time',`${start}T00:00:00Z`).lte('create_time',`${end}T23:59:59Z`).order('view_count',{ascending:false}),supabase.from('tiktok_accounts').select('profile_id,display_name,username').eq('token_status','connected'),supabase.from('profiles').select('id,full_name').eq('active',true)]);if(ve||ae||pe)throw new Error(ve?.message||ae?.message||pe?.message);setVideos((v||[]) as VideoRow[]);setAccounts((a||[]) as AccountRow[]);setProfiles((p||[]) as ProfileRow[])}catch(e:any){setError(e?.message||String(e))}finally{setLoading(false)}}
 useEffect(()=>{void load()},[start,end])
 const name=(id:string)=>profiles.find(p=>p.id===id)?.full_name||accounts.find(a=>a.profile_id===id)?.display_name||'—'
 const stats=useMemo(()=>videos.reduce((a,v)=>({videos:a.videos+1,views:a.views+(v.view_count||0),likes:a.likes+(v.like_count||0),comments:a.comments+(v.comment_count||0),shares:a.shares+(v.share_count||0)}),{videos:0,views:0,likes:0,comments:0,shares:0}),[videos])
 const sellers=useMemo(()=>accounts.map(a=>{const vs=videos.filter(v=>v.profile_id===a.profile_id);return{id:a.profile_id,name:name(a.profile_id),videos:vs.length,views:vs.reduce((s,v)=>s+(v.view_count||0),0),engagement:vs.reduce((s,v)=>s+(v.like_count||0)+(v.comment_count||0)+(v.share_count||0),0)}}).sort((a,b)=>b.views-a.views),[accounts,videos,profiles])
 return <section className="lcc-content-block"><header><div><span><BarChart3 size={14}/> TIKTOK CONTENT</span><h2>{zh?'全店内容经营':'Performance contenu équipe'}</h2><p>{zh?'根据当前账号权限自动显示：销售看自己，销售经理看本组，店长/Owner看全店。':'Périmètre automatique selon les droits : vendeur = soi, manager = équipe, store manager/Owner = magasin.'}</p></div><div className="lcc-content-range"><input type="date" value={start} max={end} onChange={e=>setStart(e.target.value)}/><span>→</span><input type="date" value={end} min={start} max={iso(now)} onChange={e=>setEnd(e.target.value)}/></div></header>{error&&<div className="lcc-error">{error}</div>}<div className="lcc-content-kpis">{[[Video,zh?'视频':'Vidéos',stats.videos],[Eye,zh?'播放':'Vues',stats.views],[Heart,zh?'点赞':'J’aime',stats.likes],[MessageCircle,zh?'评论':'Commentaires',stats.comments],[Share2,zh?'分享':'Partages',stats.shares],[Users,zh?'已连接员工':'Comptes',accounts.length]].map(([I,l,v]:any)=><div key={l}><I size={17}/><small>{l}</small><strong>{compact(Number(v))}</strong></div>)}</div><div className="lcc-content-grid"><div><header><b>{zh?'内容员工榜':'Classement vendeurs contenu'}</b><small>{zh?'按播放量':'Par vues'}</small></header>{sellers.length?sellers.slice(0,8).map((s,i)=><div className="lcc-content-row" key={s.id}><span>{i+1}</span><div><b>{s.name}</b><small>{s.videos}{zh?'条视频':' vidéos'} · {compact(s.engagement)} {zh?'互动':'interactions'}</small></div><strong>{compact(s.views)}</strong></div>):<p className="lcc-empty">{loading?(zh?'加载中…':'Chargement…'):(zh?'暂无内容数据':'Aucune donnée contenu')}</p>}</div><div><header><b>{zh?'TOP 视频':'TOP vidéos'}</b><small>{zh?'当前区间':'Période'}</small></header>{videos.length?videos.slice(0,5).map((v,i)=><div className="lcc-content-row" key={v.video_id}><span>{i+1}</span><div><b>{v.title||v.video_description||(zh?'未命名视频':'Vidéo sans titre')}</b><small>{name(v.profile_id)} · {v.create_time?new Date(v.create_time).toLocaleDateString():''}</small></div><strong>{compact(v.view_count||0)}</strong></div>):<p className="lcc-empty">{loading?(zh?'加载中…':'Chargement…'):(zh?'该区间暂无视频':'Aucune vidéo')}</p>}</div></div></section>
}
