import { useEffect,useMemo,useState } from 'react'
import { BarChart3,CircleDollarSign,Eye,MapPin,Target,Users,Video } from 'lucide-react'
import { supabase } from '../lib/supabase'
import type { Lang } from '../lib/modules'

type VideoRow={id:string;profile_id:string;video_id:string;title:string|null;video_description:string|null;create_time:string|null;view_count:number|null;like_count:number|null;comment_count:number|null;share_count:number|null}
type AttributionRow={video_row_id:string;profile_id:string;customer_id:string;visited_at:string|null;sale_id:string|null;sale_price_xof:number|null;attribution_role:string}
type AccountRow={profile_id:string;display_name:string|null;username:string|null}
type ProfileRow={id:string;full_name:string|null}
const iso=(d:Date)=>d.toISOString().slice(0,10)
const compact=(v:number)=>new Intl.NumberFormat('en-US',{notation:v>=10000?'compact':'standard',maximumFractionDigits:1}).format(v)
const money=(v:number)=>v?`${Math.round(v/100000)/10} M CFA`:'0'
export default function ContentCommandSummary({lang}:{lang:Lang}){
 const zh=lang==='zh',now=new Date();const [start,setStart]=useState(iso(new Date(now.getFullYear(),now.getMonth(),1))),[end,setEnd]=useState(iso(now)),[videos,setVideos]=useState<VideoRow[]>([]),[attrs,setAttrs]=useState<AttributionRow[]>([]),[accounts,setAccounts]=useState<AccountRow[]>([]),[profiles,setProfiles]=useState<ProfileRow[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('')
 const load=async()=>{try{setLoading(true);setError('');if(!supabase)throw new Error('Supabase not configured');const [{data:v,error:ve},{data:a,error:ae},{data:p,error:pe},{data:at,error:ate}]=await Promise.all([supabase.from('tiktok_videos').select('id,profile_id,video_id,title,video_description,create_time,view_count,like_count,comment_count,share_count').gte('create_time',`${start}T00:00:00Z`).lte('create_time',`${end}T23:59:59Z`).order('view_count',{ascending:false}),supabase.from('tiktok_accounts').select('profile_id,display_name,username').eq('token_status','connected'),supabase.from('profiles').select('id,full_name').eq('active',true),supabase.from('tiktok_content_attribution').select('video_row_id,profile_id,customer_id,visited_at,sale_id,sale_price_xof,attribution_role')]);if(ve||ae||pe||ate)throw new Error(ve?.message||ae?.message||pe?.message||ate?.message);setVideos((v||[]) as VideoRow[]);setAccounts((a||[]) as AccountRow[]);setProfiles((p||[]) as ProfileRow[]);setAttrs((at||[]) as AttributionRow[])}catch(e:any){setError(e?.message||String(e))}finally{setLoading(false)}}
 useEffect(()=>{void load()},[start,end])
 const name=(id:string)=>profiles.find(p=>p.id===id)?.full_name||accounts.find(a=>a.profile_id===id)?.display_name||'—'
 const videoIds=useMemo(()=>new Set(videos.map(v=>v.id)),[videos]);const scopedAttrs=useMemo(()=>attrs.filter(a=>videoIds.has(a.video_row_id)),[attrs,videoIds])
 const stats=useMemo(()=>({videos:videos.length,views:videos.reduce((s,v)=>s+(v.view_count||0),0),leads:new Set(scopedAttrs.map(a=>a.customer_id)).size,visits:new Set(scopedAttrs.filter(a=>a.visited_at).map(a=>a.customer_id)).size,sales:new Set(scopedAttrs.filter(a=>a.sale_id&&a.attribution_role==='primary').map(a=>a.sale_id as string)).size,revenue:scopedAttrs.filter(a=>a.sale_id&&a.attribution_role==='primary').reduce((s,a)=>s+(Number(a.sale_price_xof)||0),0)}),[videos,scopedAttrs])
 const sellers=useMemo(()=>accounts.map(a=>{const vs=videos.filter(v=>v.profile_id===a.profile_id),va=new Set(vs.map(v=>v.id)),aa=scopedAttrs.filter(x=>va.has(x.video_row_id));return{id:a.profile_id,name:name(a.profile_id),videos:vs.length,views:vs.reduce((s,v)=>s+(v.view_count||0),0),leads:new Set(aa.map(x=>x.customer_id)).size,visits:new Set(aa.filter(x=>x.visited_at).map(x=>x.customer_id)).size,sales:new Set(aa.filter(x=>x.sale_id&&x.attribution_role==='primary').map(x=>x.sale_id as string)).size,revenue:aa.filter(x=>x.sale_id&&x.attribution_role==='primary').reduce((s,x)=>s+(Number(x.sale_price_xof)||0),0)}}).sort((a,b)=>b.sales-a.sales||b.leads-a.leads||b.views-a.views),[accounts,videos,profiles,scopedAttrs])
 const videoPerf=useMemo(()=>videos.map(v=>{const aa=scopedAttrs.filter(a=>a.video_row_id===v.id);return{...v,leads:new Set(aa.map(a=>a.customer_id)).size,visits:new Set(aa.filter(a=>a.visited_at).map(a=>a.customer_id)).size,sales:new Set(aa.filter(a=>a.sale_id&&a.attribution_role==='primary').map(a=>a.sale_id as string)).size,revenue:aa.filter(a=>a.sale_id&&a.attribution_role==='primary').reduce((s,a)=>s+(Number(a.sale_price_xof)||0),0)}}).sort((a,b)=>b.sales-a.sales||b.leads-a.leads||(b.view_count||0)-(a.view_count||0)),[videos,scopedAttrs])
 return <section className="lcc-content-block"><header><div><span><BarChart3 size={14}/> TIKTOK CONTENT → CRM</span><h2>{zh?'内容到成交':'Contenu vers ventes'}</h2><p>{zh?'从视频播放继续追踪到CRM线索、到店和成交。归因是内部经营分析，不代表TikTok官方因果判断。':'Suivi interne vidéo → CRM → visite → vente. Attribution analytique interne, pas une causalité officielle TikTok.'}</p></div><div className="lcc-content-range"><input type="date" value={start} max={end} onChange={e=>setStart(e.target.value)}/><span>→</span><input type="date" value={end} min={start} max={iso(now)} onChange={e=>setEnd(e.target.value)}/></div></header>{error&&<div className="lcc-error">{error}</div>}<div className="lcc-content-kpis">{[[Video,zh?'视频':'Vidéos',stats.videos],[Eye,zh?'播放':'Vues',stats.views],[Target,zh?'内容线索':'Leads contenu',stats.leads],[MapPin,zh?'到店':'Visites',stats.visits],[CircleDollarSign,zh?'成交':'Ventes',stats.sales],[CircleDollarSign,zh?'归因成交额':'CA attribué',money(stats.revenue)]].map(([I,l,v]:any)=><div key={l}><I size={17}/><small>{l}</small><strong>{typeof v==='number'?compact(v):v}</strong></div>)}</div><div className="lcc-content-grid"><div><header><b>{zh?'员工内容成交榜':'Classement contenu → ventes'}</b><small>{zh?'按成交/线索排序':'Ventes / leads'}</small></header>{sellers.length?sellers.slice(0,8).map((s,i)=><div className="lcc-content-row" key={s.id}><span>{i+1}</span><div><b>{s.name}</b><small>{s.videos}{zh?'条视频':' vidéos'} · {compact(s.views)} {zh?'播放':'vues'} · {s.leads} Leads · {s.visits} {zh?'到店':'visites'}</small></div><strong>{s.sales}{zh?'单':' ventes'} · {money(s.revenue)}</strong></div>):<p className="lcc-empty">{loading?(zh?'加载中…':'Chargement…'):(zh?'暂无内容数据':'Aucune donnée contenu')}</p>}</div><div><header><b>{zh?'TOP 成交视频':'TOP vidéos conversion'}</b><small>{zh?'当前区间':'Période'}</small></header>{videoPerf.length?videoPerf.slice(0,6).map((v,i)=><div className="lcc-content-row" key={v.video_id}><span>{i+1}</span><div><b>{v.title||v.video_description||(zh?'未命名视频':'Vidéo sans titre')}</b><small>{name(v.profile_id)} · {compact(v.view_count||0)} {zh?'播放':'vues'} · {v.leads} Leads · {v.visits} {zh?'到店':'visites'}</small></div><strong>{v.sales}{zh?'单':' ventes'}</strong></div>):<p className="lcc-empty">{loading?(zh?'加载中…':'Chargement…'):(zh?'该区间暂无视频':'Aucune vidéo')}</p>}</div></div><div className="lcc-content-foot"><Users size={14}/><span>{zh?'下一步：通过每条视频的专属追踪链接/CRM来源，把新客户自动挂到对应视频；现在后端归因结构已经就绪。':'Étape suivante : lien traqué par vidéo / source CRM pour rattacher automatiquement chaque nouveau client. Le moteur d’attribution backend est prêt.'}</span></div></section>
}
