import { useCallback, useEffect, useMemo, useState } from 'react'
import { Eye, Pencil, Plus, RefreshCw, Search, X } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { optionText, statuses, type Lang, type Role } from '../lib/modules'

type Staff={id:string;full_name:string;role:Role;active:boolean}
type Customer={id:string;full_name:string;phone:string|null;whatsapp:string|null;email:string|null;nationality:string|null;lead_source:string|null;lead_type:string|null;interested_model:string|null;budget:number|null;assigned_to:string|null;stage:string|null;follow_up_date:string|null;notes:string|null;created_at:string}

const sourceOptions=['tiktok','facebook','instagram','google_search','voitures_ci','autoci','walk_in','referral','whatsapp','other']
const sourceText:Record<string,{fr:string;zh:string}>={google_search:{fr:'Google Search',zh:'Google 搜索'},voitures_ci:{fr:'Voitures.ci',zh:'Voitures.ci'},autoci:{fr:'AutoCI',zh:'AutoCI'},active:{fr:'Prospection active',zh:'主动客户'},passive:{fr:'Lead publicité société',zh:'被动客户 / 公司广告'}}
const txt={fr:{title:'CRM & Prospects',sub:'Gérez les prospects et distribuez les leads publicitaires à l’équipe.',create:'Nouveau client',search:'Rechercher…',name:'Nom',phone:'Téléphone',source:'Source',type:'Type',staff:'Commercial assigné',stage:'Étape',follow:'Relance',actions:'Actions',refresh:'Actualiser',empty:'Aucun client.',save:'Enregistrer',cancel:'Annuler',edit:'Modifier le client',new:'Nouveau client',email:'E-mail',whatsapp:'WhatsApp',nationality:'Nationalité',model:'Modèle recherché',budget:'Budget',notes:'Notes',active:'Actif · prospect développé par le commercial',passive:'Passif · lead généré par la publicité société',unassigned:'Non assigné'},zh:{title:'客户管理',sub:'管理客户，并将公司广告新客直接派单给员工。',create:'新增客户',search:'搜索客户…',name:'姓名',phone:'电话',source:'客户来源',type:'客户类型',staff:'负责员工',stage:'阶段',follow:'下次跟进',actions:'操作',refresh:'刷新',empty:'暂无客户。',save:'保存',cancel:'取消',edit:'编辑客户',new:'新增客户',email:'邮箱',whatsapp:'WhatsApp',nationality:'国籍',model:'意向车型',budget:'预算',notes:'备注',active:'主动 · 员工自己开发的新客',passive:'被动 · 公司投放广告获得的新客',unassigned:'暂未派单'}}
const label=(v:string|null,lang:Lang)=>v?(sourceText[v]?.[lang]||optionText[v]?.[lang]||v):'—'

export default function CrmModule({lang,role,userId}:{lang:Lang;role:Role;userId:string}){
 const t=txt[lang];const[rows,setRows]=useState<Customer[]>([]),[staff,setStaff]=useState<Staff[]>([]),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[editing,setEditing]=useState<Customer|null|undefined>(undefined),[viewing,setViewing]=useState<Customer|null>(null)
 const load=useCallback(async()=>{if(!supabase)return;setLoading(true);setError('');let q=supabase.from('customers').select('id,full_name,phone,whatsapp,email,nationality,lead_source,lead_type,interested_model,budget,assigned_to,stage,follow_up_date,notes,created_at').order('created_at',{ascending:false});if(role==='sales')q=q.eq('assigned_to',userId);const[{data,error},{data:staffData}]=await Promise.all([q,supabase.from('profiles').select('id,full_name,role,active').eq('active',true).in('role',['owner','manager','sales'])]);if(error)setError(error.message);else setRows((data||[]) as Customer[]);setStaff((staffData||[]) as Staff[]);setLoading(false)},[role,userId])
 useEffect(()=>{void load()},[load])
 const staffMap=useMemo(()=>Object.fromEntries(staff.map(s=>[s.id,s.full_name||s.id])),[staff])
 const filtered=rows.filter(r=>`${r.full_name} ${r.phone||''} ${r.email||''} ${r.interested_model||''}`.toLowerCase().includes(query.toLowerCase()))
 return <main className="main module-page"><section className="module-title"><div><p>GREEN FAST AUTO · CRM</p><h1>{t.title}</h1><h2>{t.sub}</h2></div><button className="primary" onClick={()=>setEditing(null)}><Plus size={16}/>{t.create}</button></section><div className="module-toolbar"><div className="search module-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.search}/></div><button className="secondary" onClick={()=>void load()}><RefreshCw size={15}/>{t.refresh}</button></div>{error&&<div className="error-banner">{error}</div>}{loading?<div className="card loading-state">…</div>:filtered.length===0?<div className="card empty"><h3>{t.empty}</h3></div>:<div className="card data-wrap"><table><thead><tr><th>{t.name}</th><th>{t.phone}</th><th>{t.source}</th><th>{t.type}</th><th>{t.staff}</th><th>{t.stage}</th><th>{t.follow}</th><th>{t.actions}</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td><strong>{r.full_name}</strong></td><td>{r.phone||'—'}</td><td>{label(r.lead_source,lang)}</td><td><span className={`lead-type ${r.lead_type==='passive'?'passive':''}`}>{label(r.lead_type,lang)}</span></td><td>{r.assigned_to?staffMap[r.assigned_to]||r.assigned_to:t.unassigned}</td><td>{label(r.stage,lang)}</td><td>{r.follow_up_date?new Date(r.follow_up_date).toLocaleString():'—'}</td><td className="row-actions"><button onClick={()=>setViewing(r)}><Eye/></button><button onClick={()=>setEditing(r)}><Pencil/></button></td></tr>)}</tbody></table></div>}{editing!==undefined&&<CustomerEditor lang={lang} role={role} userId={userId} staff={staff} row={editing} close={()=>setEditing(undefined)} saved={()=>{setEditing(undefined);void load()}}/>}{viewing&&<div className="modal-layer"><div className="modal detail"><div className="modal-head"><div><small>CRM</small><h2>{viewing.full_name}</h2></div><button onClick={()=>setViewing(null)}><X/></button></div><div className="detail-grid"><div><small>{t.phone}</small><strong>{viewing.phone||'—'}</strong></div><div><small>{t.whatsapp}</small><strong>{viewing.whatsapp||'—'}</strong></div><div><small>{t.source}</small><strong>{label(viewing.lead_source,lang)}</strong></div><div><small>{t.type}</small><strong>{label(viewing.lead_type,lang)}</strong></div><div><small>{t.staff}</small><strong>{viewing.assigned_to?staffMap[viewing.assigned_to]||viewing.assigned_to:t.unassigned}</strong></div><div><small>{t.stage}</small><strong>{label(viewing.stage,lang)}</strong></div><div className="wide"><small>{t.notes}</small><strong>{viewing.notes||'—'}</strong></div></div></div></div>}</main>
}

function CustomerEditor({lang,role,userId,staff,row,close,saved}:{lang:Lang;role:Role;userId:string;staff:Staff[];row:Customer|null;close:()=>void;saved:()=>void}){
 const t=txt[lang];const admin=role==='owner'||role==='manager';const[f,setF]=useState(()=>({full_name:row?.full_name||'',phone:row?.phone||'',whatsapp:row?.whatsapp||'',email:row?.email||'',nationality:row?.nationality||'',lead_source:row?.lead_source||'',lead_type:row?.lead_type||(admin?'passive':'active'),interested_model:row?.interested_model||'',budget:row?.budget??'',assigned_to:row?.assigned_to||(admin?'':userId),stage:row?.stage||'new',follow_up_date:row?.follow_up_date?.slice(0,16)||'',notes:row?.notes||''}));const[error,setError]=useState(''),[saving,setSaving]=useState(false)
 const set=(k:string,v:unknown)=>setF({...f,[k]:v})
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!supabase)return;setSaving(true);setError('');const payload={...f,budget:f.budget===''?null:Number(f.budget),assigned_to:f.assigned_to||null,assigned_by:admin&&f.assigned_to?userId:null,follow_up_date:f.follow_up_date||null};const res=row?await supabase.from('customers').update(payload).eq('id',row.id):await supabase.from('customers').insert(payload);setSaving(false);if(res.error)setError(res.error.message);else saved()}
 return <div className="modal-layer"><div className="modal"><div className="modal-head"><div><small>CRM</small><h2>{row?t.edit:t.new}</h2></div><button onClick={close}><X/></button></div><form onSubmit={submit}><div className="form-grid"><label>{t.name} *<input required value={f.full_name} onChange={e=>set('full_name',e.target.value)}/></label><label>{t.phone}<input value={f.phone} onChange={e=>set('phone',e.target.value)}/></label><label>{t.whatsapp}<input value={f.whatsapp} onChange={e=>set('whatsapp',e.target.value)}/></label><label>{t.email}<input type="email" value={f.email} onChange={e=>set('email',e.target.value)}/></label><label>{t.nationality}<input value={f.nationality} onChange={e=>set('nationality',e.target.value)}/></label><label>{t.source}<select value={f.lead_source} onChange={e=>set('lead_source',e.target.value)}><option value="">—</option>{sourceOptions.map(s=><option value={s} key={s}>{label(s,lang)}</option>)}</select></label><label>{t.type}<select value={f.lead_type} onChange={e=>set('lead_type',e.target.value)} disabled={!admin}><option value="active">{t.active}</option><option value="passive">{t.passive}</option></select></label><label>{t.staff}<select value={f.assigned_to} onChange={e=>set('assigned_to',e.target.value)} disabled={!admin}><option value="">{t.unassigned}</option>{staff.map(s=><option value={s.id} key={s.id}>{s.full_name} · {s.role}</option>)}</select></label><label>{t.model}<input value={f.interested_model} onChange={e=>set('interested_model',e.target.value)}/></label><label>{t.budget}<input type="number" value={f.budget} onChange={e=>set('budget',e.target.value)}/></label><label>{t.stage}<select value={f.stage} onChange={e=>set('stage',e.target.value)}>{statuses.customer.map(s=><option value={s} key={s}>{label(s,lang)}</option>)}</select></label><label>{t.follow}<input type="datetime-local" value={f.follow_up_date} onChange={e=>set('follow_up_date',e.target.value)}/></label><label className="wide">{t.notes}<textarea value={f.notes} onChange={e=>set('notes',e.target.value)}/></label></div>{error&&<div className="error-banner">{error}</div>}<div className="form-actions"><button type="button" className="secondary" onClick={close}>{t.cancel}</button><button className="primary" disabled={saving}>{saving?'…':t.save}</button></div></form></div></div>
}
