import {useEffect,useMemo,useState} from 'react'
import {ExternalLink,RefreshCw,Search} from 'lucide-react'
import {supabase} from '../lib/supabase'
import type {Lang,Role} from '../lib/modules'
import './TikTokLeadRadar.css'

type Q='hot'|'valid'|'long_term'|'invalid'|null
type Lead={id:string;username:string;display_name:string|null;source_type:'live'|'video_comment';original_text:string;interested_model:string|null;intent_score:number;assigned_at:string|null;assigned_to:string|null;manager_id:string|null;lead_quality:Q;next_follow_up_at:string|null;public_phone:string|null;public_whatsapp:string|null;sla_due_at:string|null;reclaim_at:string|null;response_started_at:string|null;sla_state:string|null;reassignment_count:number}
type Person={id:string;full_name:string|null}
type Range='today'|'yesterday'|'3d'|'7d'|'month'|'custom'
type WorkView='assigned'|'manager_queue'|'team'|'followup_today'|'followup_overdue'|'all'
const F='id,username,display_name,source_type,original_text,interested_model,intent_score,assigned_at,assigned_to,manager_id,lead_quality,next_follow_up_at,public_phone,public_whatsapp,sla_due_at,reclaim_at,response_started_at,sla_state,reassignment_count'
const dayStart=(d=new Date())=>new Date(d.getFullYear(),d.getMonth(),d.getDate()).getTime()
function inside(v:string|null,r:Range,a:string,b:string){if(!v)return false;const t=new Date(v).getTime(),n=new Date(),s=dayStart(n);if(r==='today')return t>=s;if(r==='yesterday')return t>=s-86400000&&t<s;if(r==='3d')return t>=s-2*86400000;if(r==='7d')return t>=s-6*86400000;if(r==='month')return t>=new Date(n.getFullYear(),n.getMonth(),1).getTime();return t>=(a?new Date(a+'T00:00:00').getTime():0)&&t<=(b?new Date(b+'T23:59:59').getTime():Infinity)}
function sla(l:Lead,lang:Lang){if(!l.sla_due_at)return '—';if(l.response_started_at)return lang==='fr'?'Répondu':'已响应';const left=Math.ceil((new Date(l.sla_due_at).getTime()-Date.now())/60000);if(left>0)return lang==='fr'?`${left} min`:`剩${left}分钟`;const reclaim=l.reclaim_at?Math.ceil((new Date(l.reclaim_at).getTime()-Date.now())/60000):0;return reclaim>0?(lang==='fr'?`Retard · reprise dans ${reclaim} min`:`已超3分钟 · ${reclaim}分钟后回收`):(lang==='fr'?'À réattribuer':'待回收')}
function followState(l:Lead,lang:Lang){if(!l.next_follow_up_at)return '—';const s=dayStart(),e=s+86400000,d=new Date(l.next_follow_up_at).getTime();if(d<s)return lang==='fr'?'En retard':'已逾期';if(d<e)return lang==='fr'?"Aujourd'hui":'今天';return new Date(l.next_follow_up_at).toLocaleString(lang==='fr'?'fr-FR':'zh-CN')}

export default function CrmProspectWorkbench({lang,role,userId}:{lang:Lang;role:Role;userId:string}){
 const t=(fr:string,zh:string)=>lang==='fr'?fr:zh
 const[rows,setRows]=useState<Lead[]>([]),[sales,setSales]=useState<Person[]>([]),[range,setRange]=useState<Range>('today'),[view,setView]=useState<WorkView>(role==='manager'?'manager_queue':'assigned'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[q,setQ]=useState(''),[sel,setSel]=useState<Lead|null>(null),[follow,setFollow]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[checked,setChecked]=useState<Set<string>>(new Set()),[bulkTarget,setBulkTarget]=useState(''),[error,setError]=useState('')
 const load=async()=>{if(!supabase)return;setError('');const l=await supabase.from('social_leads').select(F).order('assigned_at',{ascending:false}).limit(500);if(l.error){setError(l.error.message);return}setRows((l.data||[]) as Lead[]);if(role==='manager'){const p=await supabase.rpc('gfauto_manager_sales');if(p.error)setError(p.error.message);else setSales((p.data||[]) as Person[])}}
 useEffect(()=>{void load();const x=window.setInterval(()=>void load(),30_000);return()=>window.clearInterval(x)},[])
 const todayStart=dayStart(),todayEnd=todayStart+86400000
 const managerQueue=rows.filter(x=>role==='manager'&&x.manager_id===userId&&x.assigned_to===userId)
 const teamRows=rows.filter(x=>role==='manager'&&x.manager_id===userId&&x.assigned_to!==userId)
 const followToday=rows.filter(x=>x.lead_quality==='long_term'&&x.next_follow_up_at&&new Date(x.next_follow_up_at).getTime()>=todayStart&&new Date(x.next_follow_up_at).getTime()<todayEnd).length
 const followOverdue=rows.filter(x=>x.lead_quality==='long_term'&&x.next_follow_up_at&&new Date(x.next_follow_up_at).getTime()<todayStart).length
 const urgent=rows.filter(x=>x.sla_due_at&&!x.response_started_at).length
 const overdue=rows.filter(x=>x.sla_due_at&&!x.response_started_at&&new Date(x.sla_due_at)<=new Date()).length
 const visible=useMemo(()=>rows.filter(x=>{const searchOk=!q||`${x.username} ${x.display_name||''} ${x.original_text} ${x.interested_model||''} ${x.public_phone||''} ${x.public_whatsapp||''}`.toLowerCase().includes(q.toLowerCase());if(!searchOk)return false;if(role==='manager'&&view==='manager_queue')return x.manager_id===userId&&x.assigned_to===userId;if(role==='manager'&&view==='team')return x.manager_id===userId&&x.assigned_to!==userId;if(view==='followup_today')return x.lead_quality==='long_term'&&!!x.next_follow_up_at&&new Date(x.next_follow_up_at).getTime()>=todayStart&&new Date(x.next_follow_up_at).getTime()<todayEnd;if(view==='followup_overdue')return x.lead_quality==='long_term'&&!!x.next_follow_up_at&&new Date(x.next_follow_up_at).getTime()<todayStart;if(view==='all')return true;return inside(x.assigned_at,range,from,to)}),[rows,role,userId,range,view,from,to,q,todayStart,todayEnd])
 const managerAssignable=visible.filter(x=>role==='manager'&&x.assigned_to===userId&&x.manager_id===userId)
 const toggle=(id:string)=>setChecked(s=>{const n=new Set(s);n.has(id)?n.delete(id):n.add(id);return n})
 const toggleAll=()=>setChecked(s=>managerAssignable.length>0&&managerAssignable.every(x=>s.has(x.id))?new Set():new Set(managerAssignable.map(x=>x.id)))
 const bulkAssign=async()=>{if(!supabase||role!=='manager'||!bulkTarget||checked.size===0)return;setBusy(true);const r=await supabase.rpc('gfauto_manager_bulk_assign_social_leads',{p_lead_ids:Array.from(checked).slice(0,100),p_target_id:bulkTarget});setBusy(false);if(r.error){setError(r.error.message);return}setChecked(new Set());setBulkTarget('');await load()}
 const assign=async(id:string,target:string)=>{if(!supabase||!target)return;setBusy(true);const r=await supabase.rpc('gfauto_assign_social_lead',{p_lead_id:id,p_target_id:target});setBusy(false);if(r.error){setError(r.error.message);return}await load()}
 const classify=async(k:Exclude<Q,null>)=>{if(!supabase||!sel)return;if(k==='long_term'&&!follow)return;if(k==='invalid'&&!reason)return;setBusy(true);const r=await supabase.rpc('gfauto_classify_social_lead',{p_lead_id:sel.id,p_quality:k,p_next_follow_up_at:k==='long_term'?new Date(follow).toISOString():null,p_invalid_reason:k==='invalid'?reason:null});setBusy(false);if(r.error){setError(r.error.message);return}setSel(null);setFollow('');setReason('');await load()}
 const contact=async(l:Lead)=>{if(!supabase)return;setBusy(true);const r=await supabase.rpc('gfauto_mark_social_lead_contacted',{p_lead_id:l.id});setBusy(false);if(r.error){setError(r.error.message);return}window.open('https://www.tiktok.com/@'+encodeURIComponent(l.username),'_blank','noopener,noreferrer');await load()}
 return <section className="lead-radar"><div className="lr-head"><div><span className="eyebrow">CRM PROSPECTS · V0.6.10</span><h1>{role==='manager'?t('Centre prospects manager','经理潜客工作台'):t('Mes prospects','我的潜客户区')}</h1><p>{role==='manager'?t('Distribuer, superviser et relancer depuis un seul écran.','待分配、团队执行、今日跟进统一在一个经理工作台。'):t("Nouveaux prospects, SLA et relances du jour dans un seul espace.",'新分配、紧急响应、今日跟进和逾期跟进统一在一个工作台。')}</p></div><button className="lr-refresh" onClick={()=>void load()}><RefreshCw size={16}/>{t('Actualiser','刷新')}</button></div>
 {error&&<div className="error-banner">{error}</div>}
 <div className="lr-metrics"><Metric n={role==='manager'?managerQueue.length:rows.filter(x=>inside(x.assigned_at,'today','','')).length} label={role==='manager'?t('À distribuer','待分配'):t("Attribués aujourd'hui",'今日分配')}/><Metric n={role==='manager'?teamRows.length:urgent} label={role==='manager'?t('En traitement équipe','团队处理中'):t('SLA actifs','紧急待联系')}/><Metric n={followToday} label={t("Relances aujourd'hui",'今日需跟进')}/><Metric n={followOverdue} label={t('Relances en retard','逾期未跟进')}/><Metric n={overdue} label={t('SLA en retard','3分钟超时')}/></div>
 {role==='manager'&&<><div className="lr-tabs"><button className={view==='manager_queue'?'active':''} onClick={()=>{setView('manager_queue');setChecked(new Set())}}>{t('À distribuer','待分配')} · {managerQueue.length}</button><button className={view==='team'?'active':''} onClick={()=>{setView('team');setChecked(new Set())}}>{t('Équipe','团队潜客')} · {teamRows.length}</button><button className={view==='followup_today'?'active':''} onClick={()=>setView('followup_today')}>{t("Relances aujourd'hui",'今日跟进')} · {followToday}</button><button className={view==='followup_overdue'?'active':''} onClick={()=>setView('followup_overdue')}>{t('En retard','逾期跟进')} · {followOverdue}</button><button className={view==='all'?'active':''} onClick={()=>setView('all')}>{t('Tous','全部')}</button></div>{view==='manager_queue'&&<div className="lr-toolbar"><button className="ghost" onClick={toggleAll}>{managerAssignable.length>0&&managerAssignable.every(x=>checked.has(x.id))?t('Tout désélectionner','取消全选'):t('Tout sélectionner','全选待分配')}</button><strong>{t(`${checked.size} sélectionnés`,`已选择 ${checked.size} 个`)}</strong><select value={bulkTarget} onChange={e=>setBulkTarget(e.target.value)}><option value="">{t('Choisir vendeur','选择销售')}</option>{sales.map(s=><option key={s.id} value={s.id}>{s.full_name||s.id}</option>)}</select><button className="primary-action" disabled={busy||!bulkTarget||checked.size===0} onClick={()=>void bulkAssign()}>{t('Distribuer en lot','批量分配')}</button></div>}</>}
 {role!=='manager'&&<div className="lr-tabs"><button className={view==='assigned'?'active':''} onClick={()=>setView('assigned')}>{t('Nouveaux attribués','新分配')}</button><button className={view==='followup_today'?'active':''} onClick={()=>setView('followup_today')}>{t("À relancer aujourd'hui",'今日跟进')}</button><button className={view==='followup_overdue'?'active':''} onClick={()=>setView('followup_overdue')}>{t('En retard','逾期跟进')}</button><button className={view==='all'?'active':''} onClick={()=>setView('all')}>{t('Tous','全部')}</button></div>}
 <div className="lr-toolbar"><div className="lr-search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={t('Compte, commentaire, modèle, téléphone','账号、评论、车型、电话')}/></div>{role!=='manager'&&view==='assigned'&&<div className="lr-tabs">{(['today','yesterday','3d','7d','month','custom'] as Range[]).map(r=><button className={range===r?'active':''} key={r} onClick={()=>setRange(r)}>{r==='today'?t("Aujourd'hui",'今天'):r==='yesterday'?t('Hier','昨天'):r==='3d'?t('3 jours','3天'):r==='7d'?t('7 jours','7天'):r==='month'?t('Ce mois','本月'):t('Période','自定义')}</button>)}</div>}</div>
 {role!=='manager'&&view==='assigned'&&range==='custom'&&<div className="lr-toolbar"><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/><input type="date" value={to} onChange={e=>setTo(e.target.value)}/></div>}
 <div className="lr-table-wrap"><table className="lr-table"><thead><tr>{role==='manager'&&view==='manager_queue'&&<th>✓</th>}<th>{t('Compte','账号')}</th><th>{t('Attribué','分配时间')}</th><th>SLA</th><th>{t('Relance','跟进')}</th><th>{t('Commentaire','评论')}</th><th>{t('Score','评分')}</th><th>{t('Catégorie','分类')}</th><th></th></tr></thead><tbody>{visible.length===0?<tr><td className="empty" colSpan={role==='manager'&&view==='manager_queue'?9:8}>{t('Aucun prospect','暂无潜客')}</td></tr>:visible.map(l=>{const canManagerAssign=role==='manager'&&l.assigned_to===userId&&l.manager_id===userId;return <tr key={l.id}>{role==='manager'&&view==='manager_queue'&&<td>{canManagerAssign?<input type="checkbox" checked={checked.has(l.id)} onChange={()=>toggle(l.id)}/>:null}</td>}<td><b>@{l.username}</b><small>{l.display_name||'—'} · {l.source_type==='live'?'LIVE':'VIDEO'}</small></td><td>{l.assigned_at?new Date(l.assigned_at).toLocaleString(lang==='fr'?'fr-FR':'zh-CN'):'—'}</td><td><span className={`status ${l.sla_state==='overdue'?'invalid':l.response_started_at?'converted':''}`}>{sla(l,lang)}</span></td><td><span className={`status ${l.next_follow_up_at&&new Date(l.next_follow_up_at).getTime()<todayStart?'invalid':''}`}>{followState(l,lang)}</span></td><td className="quote">“{l.original_text}”</td><td><span className="score">{l.intent_score}</span></td><td>{l.lead_quality||t('Non classé','未分类')}</td><td>{canManagerAssign?<select defaultValue="" disabled={busy} onChange={e=>void assign(l.id,e.target.value)}><option value="">{t('Distribuer','分配销售')}</option>{sales.map(s=><option key={s.id} value={s.id}>{s.full_name||s.id}</option>)}</select>:<button className="ghost" onClick={()=>setSel(l)}>{t('Voir','查看')}</button>}</td></tr>})}</tbody></table></div>
 {sel&&<div className="lr-drawer-back" onClick={()=>setSel(null)}><aside className="lr-drawer" onClick={e=>e.stopPropagation()}><button className="drawer-close" onClick={()=>setSel(null)}>×</button><h2>@{sel.username}</h2><div className="intent-card"><p>“{sel.original_text}”</p><b>{sel.intent_score}/100 · {sla(sel,lang)}</b></div><button className="primary-action" disabled={busy} onClick={()=>void contact(sel)}><ExternalLink size={16}/>{t('Contacter maintenant','立即联系并开始计响应')}</button><button className="secondary-action" disabled={busy} onClick={()=>void classify('hot')}>🔥 {t('Forte intention','高意向')}</button><button className="secondary-action" disabled={busy} onClick={()=>void classify('valid')}>{t('Valide','有效')}</button><label>{t('Prochain suivi','下次跟进')}<input type="datetime-local" value={follow} onChange={e=>setFollow(e.target.value)}/></label><button className="secondary-action" disabled={busy||!follow} onClick={()=>void classify('long_term')}>{t('Suivi long terme','长期跟进')}</button><label>{t('Motif invalide','无效原因')}<select value={reason} onChange={e=>setReason(e.target.value)}><option value="">—</option><option value="not_buyer">{t('Pas acheteur','不是买家')}</option><option value="unreachable">{t('Injoignable','无法联系')}</option><option value="spam">{t('Non pertinent','乱评论')}</option><option value="duplicate">{t('Doublon','重复')}</option><option value="wrong_market">{t('Hors marché','地区不符')}</option></select></label><button className="secondary-action" disabled={busy||!reason} onClick={()=>void classify('invalid')}>{t('Invalide · purge 30j','无效 · 30天后清理')}</button></aside></div>}
 </section>
}
function Metric({n,label}:{n:number;label:string}){return <div className="lr-metric"><div><strong>{n}</strong><small>{label}</small></div></div>}
