import { useEffect,useState } from 'react'
import { Eye,Link2,RefreshCw,Video } from 'lucide-react'
import { supabase } from '../lib/supabase'
import type { Lang } from '../lib/modules'

type Row={customer_id:string;profile_id:string;captured_at:string;video_title:string|null;view_count:number|null;tracking_code:string|null;tracking_clicks:number|null;tiktok_display_name:string|null;tiktok_username:string|null}
type Customer={id:string;full_name:string;assigned_to:string|null;lead_source:string|null}
type Profile={id:string;full_name:string}
const compact=(n:number)=>new Intl.NumberFormat('en-US',{notation:n>=10000?'compact':'standard',maximumFractionDigits:1}).format(n)
export default function CrmTikTokSourceSummary({lang}:{lang:Lang}){
 const zh=lang==='zh';const[rows,setRows]=useState<Row[]>([]),[customers,setCustomers]=useState<Record<string,Customer>>({}),[profiles,setProfiles]=useState<Record<string,Profile>>({}),[loading,setLoading]=useState(true),[error,setError]=useState('')
 const load=async()=>{if(!supabase)return;setLoading(true);setError('');const[{data:r,error:re},{data:c,error:ce},{data:p,error:pe}]=await Promise.all([supabase.from('crm_tiktok_source_detail').select('customer_id,profile_id,captured_at,video_title,view_count,tracking_code,tracking_clicks,tiktok_display_name,tiktok_username').order('captured_at',{ascending:false}).limit(20),supabase.from('customers').select('id,full_name,assigned_to,lead_source'),supabase.from('profiles').select('id,full_name').eq('active',true)]);if(re||ce||pe)setError(re?.message||ce?.message||pe?.message||'');else{setRows((r||[]) as Row[]);setCustomers(Object.fromEntries(((c||[]) as Customer[]).map(x=>[x.id,x])));setProfiles(Object.fromEntries(((p||[]) as Profile[]).map(x=>[x.id,x])))}setLoading(false)}
 useEffect(()=>{void load()},[])
 return <section className="crm-tiktok-source-card"><header><div><span><Video size={14}/> TIKTOK → CRM</span><h3>{zh?'TikTok 客户来源':'Sources clients TikTok'}</h3><p>{zh?'账号级归因是基础；有追踪链接时进一步精确到具体视频。':'Attribution compte par défaut; attribution vidéo quand un lien traqué est disponible.'}</p></div><button onClick={()=>void load()}><RefreshCw size={14}/>{zh?'刷新':'Actualiser'}</button></header>{error&&<div className="error-banner">{error}</div>}{loading?<div className="crm-tiktok-empty">…</div>:rows.length===0?<div className="crm-tiktok-empty">{zh?'暂无通过追踪入口进入的 TikTok 客户。':'Aucun client TikTok capturé via le lien traqué.'}</div>:<div className="crm-tiktok-list">{rows.map((r,i)=>{const c=customers[r.customer_id],owner=profiles[r.profile_id]?.full_name||r.tiktok_display_name||'—';return <div className="crm-tiktok-row" key={`${r.customer_id}-${i}`}><div className="crm-tiktok-main"><b>{c?.full_name||r.customer_id.slice(0,8)}</b><span className="crm-source-pill">TikTok Content</span><small>{owner} · {r.tiktok_username?`@${r.tiktok_username}`:''}</small><p>{r.video_title|| (zh?'账号级来源，未锁定具体视频':'Source compte, vidéo non déterminée')}</p></div><div className="crm-tiktok-meta"><span><Eye size={12}/>{compact(r.view_count||0)} {zh?'播放':'vues'}</span><span><Link2 size={12}/>{r.tracking_code|| (zh?'账号级':'Compte')}</span><span>{new Date(r.captured_at).toLocaleString()}</span></div></div>})}</div>}</section>
}
