import { useCallback, useEffect, useMemo, useState } from 'react'
import { ArrowDown, ArrowUp, Eye, ImagePlus, Pencil, Plus, RefreshCw, Search, Trash2, X } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { modules, optionText, type Lang, type Role } from '../lib/modules'

type Row=Record<string,unknown>&{id:string}
const cfg=modules.inventory
const display=(value:unknown,lang:Lang)=>{if(value===null||value===undefined||value==='')return '—';if(typeof value==='number')return new Intl.NumberFormat(lang==='fr'?'fr-FR':'zh-CN').format(value);const key=String(value);return optionText[key]?.[lang]||key.split('_').join(' ')}
const photoUrls=(v:unknown)=>String(v||'').split(/\n|,/).map(x=>x.trim()).filter(x=>/^https?:\/\//.test(x))

export default function InventoryModule({lang,role,userId}:{lang:Lang;role:Role;userId:string}){
 const[rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[editing,setEditing]=useState<Row|null|undefined>(undefined),[viewing,setViewing]=useState<Row|null>(null)
 const relation=role==='sales'?'sales_vehicle_catalog':'vehicles';const canEdit=['owner','manager','delivery'].includes(role);const canCreate=['owner','manager'].includes(role);const canDelete=['owner','manager'].includes(role)
 const load=useCallback(async()=>{if(!supabase)return;setLoading(true);const{data,error}=await supabase.from(relation).select('*').order('created_at',{ascending:false});if(error)setError(error.message);else setRows((data||[]) as Row[]);setLoading(false)},[relation])
 useEffect(()=>{void load()},[load])
 const filtered=useMemo(()=>rows.filter(r=>Object.values(r).some(v=>String(v??'').toLowerCase().includes(query.toLowerCase()))),[rows,query])
 const fields=cfg.fields.filter(f=>!(f.sensitive&&role==='sales'))
 const remove=async(r:Row)=>{if(!supabase||!confirm(lang==='fr'?'Supprimer ce véhicule ?':'确认删除这辆车？'))return;const{error}=await supabase.from('vehicles').delete().eq('id',r.id);if(error)setError(error.message);else void load()}
 return <main className="main module-page"><section className="module-title"><div><p>GREEN FAST AUTO · STOCK</p><h1>{cfg.title[lang]}</h1><h2>{lang==='fr'?'Gérez le stock, les coûts et les photos des véhicules.':'管理库存、车辆成本和图片资料。'}</h2></div>{canCreate&&<button className="primary" onClick={()=>setEditing(null)}><Plus size={16}/>{lang==='fr'?'Nouveau véhicule':'新增车辆'}</button>}</section><div className="module-toolbar"><div className="search module-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={lang==='fr'?'Rechercher…':'搜索车辆…'}/></div><button className="secondary" onClick={()=>void load()}><RefreshCw size={15}/>{lang==='fr'?'Actualiser':'刷新'}</button></div>{error&&<div className="error-banner">{error}</div>}{loading?<div className="card loading-state">…</div>:<div className="card data-wrap"><table><thead><tr><th>{lang==='fr'?'Photo':'封面'}</th>{cfg.columns.map(k=><th key={k}>{fields.find(f=>f.key===k)?.[lang]||k}</th>)}<th>{lang==='fr'?'Actions':'操作'}</th></tr></thead><tbody>{filtered.map(r=>{const cover=photoUrls(r.photos)[0];return <tr key={r.id}><td>{cover?<img className="vehicle-cover" src={cover} alt="vehicle"/>:<div className="vehicle-cover placeholder">GF</div>}</td>{cfg.columns.map(k=><td key={k}>{display(r[k],lang)}</td>)}<td className="row-actions"><button onClick={()=>setViewing(r)}><Eye/></button>{canEdit&&<button onClick={()=>setEditing(r)}><Pencil/></button>}{canDelete&&<button onClick={()=>void remove(r)}><Trash2/></button>}</td></tr>})}</tbody></table></div>}{editing!==undefined&&<VehicleEditor lang={lang} role={role} userId={userId} row={editing} close={()=>setEditing(undefined)} saved={()=>{setEditing(undefined);void load()}}/>}{viewing&&<VehicleDetail lang={lang} role={role} row={viewing} close={()=>setViewing(null)}/>}</main>
}

function VehicleEditor({lang,role,userId,row,close,saved}:{lang:Lang;role:Role;userId:string;row:Row|null;close:()=>void;saved:()=>void}){
 const fields=cfg.fields.filter(f=>!(f.sensitive&&role==='sales')).filter(f=>!f.writeRoles||f.writeRoles.includes(role));const[form,setForm]=useState<Record<string,unknown>>(()=>Object.fromEntries(fields.filter(f=>f.key!=='photos').map(f=>[f.key,row?.[f.key]??(f.type==='checkbox'?false:'')])));const[existing,setExisting]=useState<string[]>(photoUrls(row?.photos));const[pending,setPending]=useState<File[]>([]);const[saving,setSaving]=useState(false),[error,setError]=useState('')
 const move=<T,>(arr:T[],i:number,d:number)=>{const j=i+d;if(j<0||j>=arr.length)return arr;const n=[...arr];[n[i],n[j]]=[n[j],n[i]];return n}
 const upload=async()=>{if(!supabase)return[];const urls:string[]=[];for(const file of pending){if(file.size>10*1024*1024)throw new Error(lang==='fr'?`${file.name} dépasse 10 Mo.`:`${file.name} 超过 10MB。`);const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=`vehicles/${row?.id||userId}/${Date.now()}-${Math.random().toString(36).slice(2,8)}-${safe}`;const{error}=await supabase.storage.from('vehicle-media').upload(path,file,{upsert:false});if(error)throw error;urls.push(supabase.storage.from('vehicle-media').getPublicUrl(path).data.publicUrl)}return urls}
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!supabase)return;setSaving(true);setError('');try{const uploaded=await upload();const clean=Object.fromEntries(Object.entries(form).map(([k,v])=>[k,v===''?null:v]));clean.photos=[...existing,...uploaded].join('\n')||null;const res=row?await supabase.from('vehicles').update(clean).eq('id',row.id):await supabase.from('vehicles').insert(clean);if(res.error)throw res.error;saved()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setSaving(false)}}
 return <div className="modal-layer"><div className="modal"><div className="modal-head"><div><small>VEHICLE</small><h2>{row?(lang==='fr'?'Modifier le véhicule':'编辑车辆'):(lang==='fr'?'Nouveau véhicule':'新增车辆')}</h2></div><button onClick={close}><X/></button></div><form onSubmit={submit}><div className="form-grid">{fields.filter(f=>f.key!=='photos').map(field=><label className={field.type==='textarea'?'wide':''} key={field.key}>{field[lang]}{field.required&&' *'}{field.type==='select'?<select required={field.required} value={String(form[field.key]??'')} onChange={e=>setForm({...form,[field.key]:e.target.value})}><option value="">—</option>{field.options?.map(o=><option key={o} value={o}>{display(o,lang)}</option>)}</select>:field.type==='textarea'?<textarea value={String(form[field.key]??'')} onChange={e=>setForm({...form,[field.key]:e.target.value})}/>:<input required={field.required} type={field.type||'text'} step={field.type==='number'?'any':undefined} value={String(form[field.key]??'')} onChange={e=>setForm({...form,[field.key]:field.type==='number'&&e.target.value!==''?Number(e.target.value):e.target.value})}/>}</label>)}</div><div className="photo-manager"><div className="photo-upload"><ImagePlus size={20}/><div><strong>{lang==='fr'?'Téléverser les photos':'上传车辆图片'}</strong><small>{lang==='fr'?'La première photo sera la couverture. Réorganisez avec ↑ ↓.':'第一张图片作为封面，可用 ↑ ↓ 调整顺序。'}</small></div><input type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" multiple onChange={e=>setPending(Array.from(e.target.files||[]).slice(0,10))}/></div>{existing.length>0&&<div className="ordered-photos">{existing.map((url,i)=><div className="ordered-photo" key={url}><img src={url}/><span>{i===0?(lang==='fr'?'Couverture':'封面'):`#${i+1}`}</span><button type="button" onClick={()=>setExisting(move(existing,i,-1))}><ArrowUp/></button><button type="button" onClick={()=>setExisting(move(existing,i,1))}><ArrowDown/></button><button type="button" onClick={()=>setExisting(existing.filter((_,j)=>j!==i))}><X/></button></div>)}</div>}{pending.length>0&&<div className="ordered-photos pending">{pending.map((file,i)=><div className="ordered-photo" key={`${file.name}-${i}`}><div className="file-tile">{file.name}</div><span>+{i+1}</span><button type="button" onClick={()=>setPending(move(pending,i,-1))}><ArrowUp/></button><button type="button" onClick={()=>setPending(move(pending,i,1))}><ArrowDown/></button><button type="button" onClick={()=>setPending(pending.filter((_,j)=>j!==i))}><X/></button></div>)}</div>}</div>{error&&<div className="error-banner">{error}</div>}<div className="form-actions"><button type="button" className="secondary" onClick={close}>{lang==='fr'?'Annuler':'取消'}</button><button className="primary" disabled={saving}>{saving?(lang==='fr'?'Téléversement…':'上传中…'):(lang==='fr'?'Enregistrer':'保存')}</button></div></form></div></div>
}

function VehicleDetail({lang,role,row,close}:{lang:Lang;role:Role;row:Row;close:()=>void}){const fields=cfg.fields.filter(f=>f.key!=='photos'&&!(f.sensitive&&role==='sales'));const photos=photoUrls(row.photos);const[current,setCurrent]=useState(0);return <div className="modal-layer"><div className="modal detail"><div className="modal-head"><div><small>VEHICLE</small><h2>{display(row.make,lang)} {display(row.model,lang)}</h2></div><button onClick={close}><X/></button></div>{photos.length>0&&<div className="vehicle-gallery"><div className="gallery-main"><img src={photos[current]}/><span>{current+1} / {photos.length}</span></div><div className="gallery-thumbs">{photos.map((p,i)=><button className={i===current?'active':''} onClick={()=>setCurrent(i)} key={p}><img src={p}/></button>)}</div></div>}<div className="detail-grid">{fields.map(f=><div key={f.key}><small>{f[lang]}</small><strong>{display(row[f.key],lang)}</strong></div>)}</div></div></div>}
