import { useEffect, useMemo, useState } from 'react'
import { Activity, ChevronRight, CircleDollarSign, Link2, Radio, RefreshCw, Target, Timer, Users, X } from 'lucide-react'
import type { Lang, Role } from '../lib/modules'
import { getLiveCommandCenter, getSellerLiveHistory, type SellerLiveRow, type SellerSessionHistoryRow } from '../lib/liveCommandCenter'
import LiveSessionDetailModal from './LiveSessionDetailModal'
import ContentCommandSummary from './ContentCommandSummary'
import ManagerSalesAI from './ManagerSalesAI'
import '../live-command-center.css'

type Props={lang:Lang;role:Role;managerScope?:string|null;onOpenCrm?:()=>void}

export default function LiveCommandCenter({lang,role,managerScope,onOpenCrm}:Props){
 const zh=lang==='zh',scopeLabel=role==='owner'?(zh?'全店经营总览':'Vue globale magasin'):managerScope==='store'?(zh?'全店经营作战盘':'Pilotage magasin'):(zh?'我的团队作战盘':'Mon équipe')
 const scopeCopy=role==='owner'?(zh?'Owner查看全店经营、内容、LIVE、成交与管理异常。':'Le Owner voit l’ensemble du magasin : exécution, contenu, LIVE, ventes et exceptions.'):managerScope==='store'?(zh?'店长查看全店执行、内容、LIVE与成交。':'Le manager magasin pilote l’ensemble du magasin.'):(zh?'销售经理查看自己与本组销售执行、内容、LIVE与成交。':'Le manager commercial voit son équipe selon son périmètre.')
 const [rows,setRows]=useState<SellerLiveRow[]>([]),[summary,setSummary]=useState({sellers:0,connected:0,liveNow:0,leads:0,appointments:0,visits:0,sales:0,revenue:0})
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[filter,setFilter]=useState<'all'|'live'|'offline'|'unconnected'>('all')
 const [selected,setSelected]=useState<SellerLiveRow|null>(null),[history,setHistory]=useState<SellerSessionHistoryRow[]>([]),[historyLoading,setHistoryLoading]=useState(false)
 const [selectedSession,setSelectedSession]=useState<string|null>(null)
 const load=async()=>{setLoading(true);setError('');try{const data=await getLiveCommandCenter();setRows(data.rows);setSummary(data.summary)}catch(e:any){setError(e?.message||String(e))}finally{setLoading(false)}}
 useEffect(()=>{void load();const id=window.setInterval(()=>void load(),15000);return()=>window.clearInterval(id)},[])
 const shown=useMemo(()=>rows.filter(r=>filter==='all'||(filter==='live'&&r.live)||(filter==='offline'&&!r.live&&r.connected)||(filter==='unconnected'&&!r.connected)),[rows,filter])
 const money=(n:number)=>n?`${Math.round(n/100000)/10} M CFA`:'0'
 const openSeller=async(r:SellerLiveRow)=>{setSelected(r);setSelectedSession(null);setHistory([]);setHistoryLoading(true);try{setHistory(await getSellerLiveHistory(r.profileId))}catch(e:any){setError(e?.message||String(e))}finally{setHistoryLoading(false)}}
 const date=(v:string|null)=>v?new Intl.DateTimeFormat(zh?'zh-CN':'fr-FR',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(v)):'—'
 const jump=(id:string)=>document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'})
 return <main className="lcc-page">
  <section className="lcc-hero"><div><span><Radio size={14}/> GREEN FAST • MANAGEMENT AI</span><h1>{scopeLabel}</h1><p>{scopeCopy}</p></div><button onClick={()=>void load()}><RefreshCw size={16}/>{zh?'刷新':'Actualiser'}</button></section>
  {error&&<div className="lcc-error">{error}</div>}
  <section id="lcc-overview" className="lcc-overview-block"><div className="lcc-section-title compact"><div><span><Activity size={14}/> {zh?'数据总览':'VUE D’ENSEMBLE'}</span><h2>{role==='owner'||managerScope==='store'?(zh?'全店核心数据':'Données clés magasin'):(zh?'本组核心数据':'Données clés équipe')}</h2></div><small>{zh?'总览始终保留在第一屏':'Toujours visible au premier écran'}</small></div><section className="lcc-kpis">{[[zh?'销售人数':'Vendeurs',summary.sellers,Users],[zh?'已连接TikTok':'TikTok connectés',summary.connected,Link2],[zh?'正在直播':'En LIVE',summary.liveNow,Radio],[zh?'LIVE线索':'Leads LIVE',summary.leads,Target],[zh?'预约':'RDV',summary.appointments,Timer],[zh?'到店':'Visites',summary.visits,Activity],[zh?'成交':'Ventes',summary.sales,CircleDollarSign],[zh?'归因成交额':'CA attribué',money(summary.revenue),CircleDollarSign]].map(([n,v,Icon]:any)=><div key={n}><Icon size={18}/><small>{n}</small><strong>{v}</strong></div>)}</section></section>
  <nav className="lcc-manager-nav">{[['lcc-exceptions',zh?'异常 / 今天该管谁':'Exceptions'],['lcc-content',zh?'内容数据':'Contenu'],['lcc-live',zh?'LIVE经营':'LIVE'],['lcc-results',zh?'成交结果':'Résultats']].map(([id,label])=><button key={id} onClick={()=>jump(id)}>{label}</button>)}</nav>
  <section id="lcc-exceptions"><ManagerSalesAI lang={lang}/></section><section id="lcc-content"><ContentCommandSummary lang={lang}/></section>
  <section id="lcc-live" className="lcc-section-title"><div><span><Radio size={14}/> LIVE SALES</span><h2>{zh?'直播经营与成交':'Performance LIVE & ventes'}</h2></div></section>
  <section className="lcc-toolbar"><div>{(['all','live','offline','unconnected'] as const).map(x=><button key={x} className={filter===x?'active':''} onClick={()=>setFilter(x)}>{x==='all'?(zh?'全部':'Tous'):x==='live'?(zh?'直播中':'LIVE'):x==='offline'?(zh?'已连接/未播':'Connecté / hors LIVE'):(zh?'未连接':'Non connecté')}</button>)}</div><span>{loading?(zh?'同步中…':'Synchronisation…'):`${shown.length}/${rows.length}`}</span></section>
  <section id="lcc-results" className="lcc-table-wrap"><table><thead><tr><th>{zh?'销售':'Vendeur'}</th><th>TikTok</th><th>{zh?'状态':'Statut'}</th><th>{zh?'在线':'Viewers'}</th><th>LIVE SCORE</th><th>{zh?'线索':'Leads'}</th><th>RDV</th><th>{zh?'到店':'Visites'}</th><th>{zh?'试驾':'Essais'}</th><th>{zh?'成交':'Ventes'}</th><th>0–30j</th><th>0–60j</th><th>0–90j</th><th>{zh?'平均成交周期':'Cycle moyen'}</th><th>{zh?'成交额':'CA'}</th><th></th></tr></thead><tbody>{shown.map(r=><tr key={r.profileId} className="lcc-row" onClick={()=>void openSeller(r)}><td><b>{r.name}</b><small>{r.profileId.slice(0,8)}</small></td><td><span className={r.connected?'lcc-conn ok':'lcc-conn'}>{r.connected?'●':'○'} {r.tiktokUsername?`@${r.tiktokUsername}`:r.tiktokName||(zh?'未连接':'Non connecté')}</span></td><td><span className={r.live?'lcc-live':'lcc-off'}>{r.live?(zh?'直播中':'LIVE'):(r.connected?(zh?'未直播':'OFFLINE'):(zh?'未连接':'NO LINK'))}</span></td><td>{r.live?<b>{r.viewers}</b>:'—'}</td><td>{r.live?<b>{r.liveScore}</b>:'—'}</td><td>{r.leads}</td><td>{r.appointments}</td><td>{r.visits}</td><td>{r.testDrives}</td><td><b>{r.sales}</b></td><td>{r.sold30}</td><td>{r.sold60}</td><td>{r.sold90}</td><td>{r.avgDaysToSale===null?'—':`${r.avgDaysToSale}j`}</td><td><b>{money(r.revenue)}</b></td><td><ChevronRight size={16}/></td></tr>)}</tbody></table>{!loading&&!shown.length&&<div className="lcc-empty">{zh?'暂无符合条件的数据':'Aucune donnée pour ce filtre'}</div>}</section>
  {selected&&<section className="lcc-detail"><header><div><small>{zh?'销售直播档案':'DOSSIER LIVE VENDEUR'}</small><h2>{selected.name}</h2><p>{selected.tiktokUsername?`@${selected.tiktokUsername}`:selected.tiktokName||(zh?'TikTok未连接':'TikTok non connecté')} · {selected.live?(zh?'当前正在直播':'LIVE maintenant'):(zh?'当前未直播':'hors LIVE')}</p></div><button onClick={()=>{setSelected(null);setSelectedSession(null)}}><X size={18}/></button></header><div className="lcc-detail-kpis"><div><small>{zh?'累计线索':'Leads'}</small><b>{selected.leads}</b></div><div><small>{zh?'预约':'RDV'}</small><b>{selected.appointments}</b></div><div><small>{zh?'成交':'Ventes'}</small><b>{selected.sales}</b></div><div><small>{zh?'成交额':'CA'}</small><b>{money(selected.revenue)}</b></div><div><small>0–30j</small><b>{selected.sold30}</b></div><div><small>0–90j</small><b>{selected.sold90}</b></div></div><div className="lcc-history"><h3>{zh?'最近直播历史':'Historique récent des LIVE'}</h3>{historyLoading?<div className="lcc-empty">{zh?'加载中…':'Chargement…'}</div>:history.length?<table><thead><tr><th>{zh?'开始':'Début'}</th><th>{zh?'车型/活动':'Véhicule / campagne'}</th><th>{zh?'状态':'Statut'}</th><th>Peak</th><th>Score</th><th>Leads</th><th>RDV</th><th>{zh?'到店':'Visites'}</th><th>{zh?'试驾':'Essais'}</th><th>{zh?'成交':'Ventes'}</th><th>0–30j</th><th>0–60j</th><th>0–90j</th><th>{zh?'晚成交':'Tardives'}</th><th>{zh?'周期':'Cycle'}</th><th>CA</th><th></th></tr></thead><tbody>{history.map(h=><tr key={h.sessionId} className="lcc-history-row" onClick={()=>setSelectedSession(h.sessionId)}><td><b>{date(h.startedAt)}</b><small>{h.accountName||'TikTok'}</small></td><td>{h.primaryVehicle||h.campaign||'—'}</td><td>{h.status==='live'?<span className="lcc-live">LIVE</span>:<span className="lcc-off">END</span>}</td><td>{h.peak||'—'}</td><td>{h.liveScore||'—'}</td><td>{h.leads}</td><td>{h.appointments}</td><td>{h.visits}</td><td>{h.testDrives}</td><td><b>{h.sales}</b></td><td>{h.sold30}</td><td>{h.sold60}</td><td>{h.sold90}</td><td>{h.lateSales}</td><td>{h.avgDaysToSale===null?'—':`${h.avgDaysToSale}j`}</td><td><b>{money(h.revenue)}</b></td><td><button className="lcc-detail-btn" onClick={e=>{e.stopPropagation();setSelectedSession(h.sessionId)}}>{zh?'详情':'Détails'}</button></td></tr>)}</tbody></table>:<div className="lcc-empty">{zh?'这个销售还没有直播历史':'Aucun historique LIVE pour ce vendeur'}</div>}</div></section>}
  {selectedSession&&<LiveSessionDetailModal lang={lang} sessionId={selectedSession} sellerName={selected?.name} onClose={()=>setSelectedSession(null)} onOpenCrm={onOpenCrm}/>}<section className="lcc-note"><b>{zh?'角色视角':'Vue par rôle'}</b><p>{zh?'销售看自己的作战台；销售经理看本组；店长看全店；Owner看全店并独享系统与上线配置。所有数据仍由现有RLS权限控制。':'Le vendeur voit son cockpit; le manager commercial son équipe; le manager magasin tout le magasin; le Owner voit tout et garde seul la configuration système/mise en production. Les données restent protégées par les RLS existantes.'}</p></section>
 </main>
}
