import { useEffect, useState } from 'react'
import { Activity, ArrowLeft, CircleDollarSign, Clock3, MessageCircle, Target, Users, X, Zap } from 'lucide-react'
import type { Lang } from '../lib/modules'
import { getLiveSessionDetail, type SessionDetail } from '../lib/liveSessionDetail'
import '../my-live-history.css'

type Props={lang:Lang;sessionId:string;onClose:()=>void;onOpenCrm?:()=>void;sellerName?:string}

export default function LiveSessionDetailModal({lang,sessionId,onClose,onOpenCrm,sellerName}:Props){
  const zh=lang==='zh'
  const [detail,setDetail]=useState<SessionDetail|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('')
  useEffect(()=>{setLoading(true);setError('');void getLiveSessionDetail(sessionId).then(setDetail).catch(e=>setError(String(e?.message||e))).finally(()=>setLoading(false))},[sessionId])
  const money=(n:number)=>n?`${Math.round(n/100000)/10} M CFA`:'0'
  const date=(s:string|null)=>s?new Date(s).toLocaleString(zh?'zh-CN':'fr-FR',{month:'short',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'—'
  return <div className="mlh-modal"><div className="mlh-backdrop" onClick={onClose}/><section className="mlh-detail"><header><div><button onClick={onClose}><ArrowLeft size={16}/></button><div><small>{sellerName?`${sellerName} · LIVE SESSION`:'LIVE SESSION'}</small><h2>{detail?date(detail.session.startedAt):(zh?'加载中…':'Chargement…')}</h2></div></div><button onClick={onClose}><X size={18}/></button></header>{error&&<div className="mlh-error">{error}</div>}{loading||!detail?<div className="mlh-detail-loading">{zh?'正在读取单场直播详情…':'Chargement du détail de la session…'}</div>:<>
    <div className="mlh-session-kpis">{[[zh?'峰值在线':'Pic',detail.session.peak,Users],['LIVE SCORE',detail.session.liveScore,Activity],[zh?'线索':'Leads',detail.session.leads,Target],[zh?'成交':'Ventes',detail.session.sales,CircleDollarSign],[zh?'成交额':'CA',money(detail.session.revenue),CircleDollarSign],[zh?'平均成交周期':'Cycle moyen',detail.session.avgDaysToSale===null?'—':`${detail.session.avgDaysToSale}j`,Clock3]].map(([n,v,Icon]:any)=><div key={n}><Icon size={17}/><small>{n}</small><strong>{v}</strong></div>)}</div>
    <div className="mlh-lag"><b>{zh?'延迟转化':'Conversion différée'}</b><span>0–30j <strong>{detail.session.sold30}</strong></span><span>0–60j <strong>{detail.session.sold60}</strong></span><span>0–90j <strong>{detail.session.sold90}</strong></span><span>{zh?'90天后':'Après 90j'} <strong>{detail.session.late}</strong></span></div>
    <section className="mlh-section"><header><div><Zap size={16}/><b>{zh?'AI Director动作':'Actions AI Director'}</b></div><span>{detail.actions.length}</span></header>{detail.actions.length?<div className="mlh-actions-list">{detail.actions.map(a=><article key={a.id}><div><small>{a.priority}</small><b>{a.actionType.split('_').join(' ')}</b><p>{zh?(a.scriptZh||a.scriptFr):(a.scriptFr||a.scriptZh)}</p></div><div className="mlh-deltas"><span>LIVE {a.liveScoreDelta>=0?'+':''}{a.liveScoreDelta}</span><span>Retention {a.retentionDelta>=0?'+':''}{a.retentionDelta}</span><span>Interaction {a.interactionDelta>=0?'+':''}{a.interactionDelta}</span><span>Leads {a.leadsDelta>=0?'+':''}{a.leadsDelta}</span></div></article>)}</div>:<p className="mlh-muted">{zh?'这场直播没有记录AI动作':'Aucune action AI Director enregistrée.'}</p>}</section>
    <section className="mlh-section"><header><div><MessageCircle size={16}/><b>{zh?'评论与意向识别':'Commentaires & intention'}</b></div><span>{detail.comments.length}</span></header>{detail.comments.length?<div className="mlh-comments-list">{detail.comments.map(c=><article key={c.id}><div><b>{c.user||'TikTok user'}</b><p>{c.text}</p><small>{c.intentTags.join(' · ')||'GENERAL'}</small></div><div><strong>{c.intentScore}</strong><span className={c.intentBand==='A'?'hot':''}>{c.intentBand||'C'}</span>{c.routed&&<em>CRM</em>}</div></article>)}</div>:<p className="mlh-muted">{zh?'暂无评论记录':'Aucun commentaire enregistré.'}</p>}</section>
    <section className="mlh-section"><header><div><Target size={16}/><b>{zh?'CRM后续与成交':'CRM → résultat commercial'}</b></div>{onOpenCrm&&<button className="mlh-crm" onClick={onOpenCrm}>{zh?'打开CRM':'Ouvrir CRM'}</button>}</header>{detail.leads.length?<div className="mlh-leads-list">{detail.leads.map(l=><article key={l.id}><div><b>{l.user||'Lead TikTok'}</b><small>{l.model||'—'} · {l.band||'C'} · {l.score}/100</small></div><div className="mlh-stage"><span>{l.status}</span>{l.conversionDays!==null&&<small>{l.conversionDays}j</small>}</div><strong>{l.wonAt?money(l.salePrice):'—'}</strong></article>)}</div>:<p className="mlh-muted">{zh?'这场直播还没有CRM线索':'Aucun lead CRM pour cette session.'}</p>}</section>
  </>}</section></div>
}
