import { useCallback, useEffect, useMemo, useState } from 'react'
import { Eye, Pencil, RefreshCw, Search, X } from 'lucide-react'
import { supabase } from '../lib/supabase'
import type { Lang } from '../lib/modules'

type Row={id:string;stock_number:string|null;make:string|null;model:string|null;trim:string|null;year:number|null;vin:string|null;exterior_color:string|null;interior_color:string|null;mileage:number|null;fuel_type:string|null;shipping_date:string|null;eta_abidjan:string|null;arrival_date:string|null;status:string|null;asking_price:number|null;final_sale_price:number|null;photos:string|null;documents:string|null;created_at:string}
const money=(n:number|null)=>n==null?'—':new Intl.NumberFormat('fr-FR').format(n)+' XOF'
const urls=(v:string|null)=>String(v||'').split(/\n|,/).map(x=>x.trim()).filter(x=>/^https?:\/\//.test(x))
export default function ManagerInventoryModule({lang}:{lang:Lang}){
 const[rows,setRows]=useState<Row[]>([]),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[viewing,setViewing]=useState<Row|null>(null),[editing,setEditing]=useState<Row|null>(null)
 const load=useCallback(async()=>{if(!supabase)return;setLoading(true);const{data,error}=await supabase.from('manager_vehicle_catalog').select('*').order('created_at',{ascending:false});if(error)setError(error.message);else setRows((data||[]) as Row[]);setLoading(false)},[]);useEffect(()=>{void load()},[load])
 const filtered=useMemo(()=>rows.filter(r=>`${r.stock_number||''} ${r.make||''} ${r.model||''} ${r.trim||''} ${r.status||''}`.toLowerCase().includes(query.toLowerCase())),[rows,query])
 return <main className="main module-page"><section className="module-title"><div><p>GREEN FAST AUTO · MANAGER STOCK</p><h1>{lang==='fr'?'Parc véhicules':'车辆库存'}</h1><h2>{lang==='fr'?'Vue commerciale : stock, prix, disponibilité et véhicules en transit.':'经理销售视图：库存、销售价格、现车与在途状态；不显示任何成本数据。'}</h2></div></section><div className="module-toolbar"><div className="search module-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={lang==='fr'?'Rechercher…':'搜索车辆…'}/></div><button className="secondary" onClick={()=>void load()}><RefreshCw size={15}/>{lang==='fr'?'Actualiser':'刷新'}</button></div>{error&&<div className="error-banner">{error}</div>}{loading?<div className="card loading-state">…</div>:<div className="card data-wrap"><table><thead><tr><th>{lang==='fr'?'Photo':'封面'}</th><th>{lang==='fr'?'Stock':'库存编号'}</th><th>{lang==='fr'?'Véhicule':'车辆'}</th><th>{lang==='fr'?'Statut':'状态'}</th><th>ETA Abidjan</th><th>{lang==='fr'?'Prix affiché':'销售标价'}</th><th>{lang==='fr'?'Prix final':'最终售价'}</th><th>{lang==='fr'?'Actions':'操作'}</th></tr></thead><tbody>{filtered.map(r=>{const cover=urls(r.photos)[0];return <tr key={r.id}><td>{cover?<img className="vehicle-cover" src={cover}/>:<div className="vehicle-cover placeholder">GF</div>}</td><td>{r.stock_number||'—'}</td><td><strong>{r.make} {r.model}</strong><small className="cell-sub">{r.trim||''} {r.year||''}</small></td><td>{r.status||'—'}</td><td>{r.eta_abidjan||'—'}</td><td>{money(r.asking_price)}</td><td>{money(r.final_sale_price)}</td><td className="row-actions"><button onClick={()=>setViewing(r)}><Eye/></button><button onClick={()=>setEditing(r)}><Pencil/></button></td></tr>})}</tbody></table></div>}{viewing&&<Detail row={viewing} lang={lang} close={()=>setViewing(null)}/>} {editing&&<Edit row={editing} lang={lang} close={()=>setEditing(null)} saved={()=>{setEditing(null);void load()}}/>}</main>
}
function Detail({row,lang,close}:{row:Row;lang:Lang;close:()=>void}){const ps=urls(row.photos);return <div className="modal-layer"><div className="modal detail"><div className="modal-head"><div><small>MANAGER VIEW</small><h2>{row.make} {row.model}</h2></div><button onClick={close}><X/></button></div>{ps[0]&&<div className="vehicle-gallery"><div className="gallery-main"><img src={ps[0]}/></div></div>}<div className="detail-grid"><div><small>VIN</small><strong>{row.vin||'—'}</strong></div><div><small>{lang==='fr'?'Statut':'状态'}</small><strong>{row.status||'—'}</strong></div><div><small>{lang==='fr'?'Expédition':'发运日期'}</small><strong>{row.shipping_date||'—'}</strong></div><div><small>ETA Abidjan</small><strong>{row.eta_abidjan||'—'}</strong></div><div><small>{lang==='fr'?'Arrivée':'到港日期'}</small><strong>{row.arrival_date||'—'}</strong></div><div><small>{lang==='fr'?'Prix affiché':'销售标价'}</small><strong>{money(row.asking_price)}</strong></div><div><small>{lang==='fr'?'Prix final':'最终售价'}</small><strong>{money(row.final_sale_price)}</strong></div></div></div></div>}
function Edit({row,lang,close,saved}:{row:Row;lang:Lang;close:()=>void;saved:()=>void}){const[status,setStatus]=useState(row.status||''),[asking,setAsking]=useState(String(row.asking_price??'')),[finalPrice,setFinalPrice]=useState(String(row.final_sale_price??'')),[eta,setEta]=useState(row.eta_abidjan||''),[error,setError]=useState(''),[busy,setBusy]=useState(false);const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!supabase)return;setBusy(true);const{error}=await supabase.from('vehicles').update({status,asking_price:asking?Number(asking):null,final_sale_price:finalPrice?Number(finalPrice):null,eta_abidjan:eta||null}).eq('id',row.id);setBusy(false);if(error)setError(error.message);else saved()};return <div className="modal-layer"><div className="modal"><div className="modal-head"><div><small>MANAGER EDIT</small><h2>{row.make} {row.model}</h2></div><button onClick={close}><X/></button></div><form onSubmit={submit}><div className="form-grid"><label>{lang==='fr'?'Statut':'状态'}<select value={status} onChange={e=>setStatus(e.target.value)}><option value="ordered">ordered</option><option value="in_transit">in_transit</option><option value="port">port</option><option value="customs">customs</option><option value="in_stock">in_stock</option><option value="reserved">reserved</option><option value="sold">sold</option><option value="delivered">delivered</option></select></label><label>ETA Abidjan<input type="date" value={eta} onChange={e=>setEta(e.target.value)}/></label><label>{lang==='fr'?'Prix affiché':'销售标价'}<input type="number" value={asking} onChange={e=>setAsking(e.target.value)}/></label><label>{lang==='fr'?'Prix final':'最终售价'}<input type="number" value={finalPrice} onChange={e=>setFinalPrice(e.target.value)}/></label></div>{error&&<div className="error-banner">{error}</div>}<div className="form-actions"><button type="button" className="secondary" onClick={close}>{lang==='fr'?'Annuler':'取消'}</button><button className="primary" disabled={busy}>{lang==='fr'?'Enregistrer':'保存'}</button></div></form></div></div>}
