import './marketplaceHomeAdvisor.css'

type Use='family'|'ride'|'business'|'long'|'city'
const clean=(v:string)=>(v||'').replace(/\s+/g,' ').trim()
const zh=()=>document.documentElement.lang==='zh'||/选车|车型|预算|智能/.test(document.body.textContent||'')
const money=(v:string)=>{const m=v.match(/([0-9]+(?:[.,][0-9]+)?)\s*(m|million|百万)/i);if(m)return Number(m[1].replace(',','.'))*1e6;const wan=v.match(/([0-9]+)\s*万/);return wan?Number(wan[1])*10000:0}
const useOf=(s:string):Use=>/网约|vtc|uber|taxi|运营/.test(s)?'ride':/商务|接待|business|affaire/.test(s)?'business':/长途|跨城|longue|route/.test(s)?'long':/市区|通勤|ville|urbain/.test(s)?'city':'family'
const labels:Record<Use,{z:string;f:string}>={family:{z:'家庭',f:'famille'},ride:{z:'网约车/高频运营',f:'VTC / usage intensif'},business:{z:'商务接待',f:'business'},long:{z:'长途跨城',f:'longue distance'},city:{z:'市区通勤',f:'ville'}}

function cards(){return Array.from(document.querySelectorAll<HTMLElement>('#cars .market-card')).map((el,i)=>{const text=clean(el.textContent||'');const title=clean(el.querySelector('h3,h4,strong')?.textContent||'')||`Véhicule ${i+1}`;const p=Number((text.match(/([0-9][0-9\s.,]{4,})\s*(?:FCFA|CFA)/i)?.[1]||'').replace(/[^0-9]/g,''))||0;return{el,title,text:text.toLowerCase(),price:p}}).filter(x=>x.title)}
function score(c:ReturnType<typeof cards>[number],use:Use,budget:number){let s=50;const t=c.text;if(budget&&c.price){const d=(c.price-budget)/budget;s+=d<=0?18:Math.max(-25,10-d*50)}if(/en stock|现车/.test(t))s+=8;if(use==='family'){if(/7 places|7座|7 seat/.test(t))s+=18;if(/suv/.test(t))s+=8}if(use==='ride'){if(/hybrid|hybride|hev|phev|混动|electric|électrique|纯电/.test(t))s+=18;if(c.price&&c.price<=20000000)s+=8}if(use==='business'){if(/premium|luxury|商务|cuir|leather/.test(t))s+=12;if(/suv|sedan/.test(t))s+=5}if(use==='long'){if(/suv|4x4/.test(t))s+=8;if(/hybrid|diesel|混动/.test(t))s+=5}if(use==='city'){if(c.price&&c.price<=20000000)s+=8;if(/hybrid|electric|混动|纯电/.test(t))s+=12}return s}
function reason(c:ReturnType<typeof cards>[number],use:Use,budget:number,isZh:boolean){const r:string[]=[];if(/en stock|现车/.test(c.text))r.push(isZh?'现车优先':'disponible en stock');if(budget&&c.price)r.push(c.price<=budget?(isZh?'预算内':'dans le budget'):(isZh?`超预算约${Math.round((c.price-budget)/1e6)}M`:`environ ${Math.round((c.price-budget)/1e6)}M au-dessus`));if(use==='ride'&&/hybrid|hybride|hev|phev|混动|electric|électrique|纯电/.test(c.text))r.push(isZh?'更适合高频运营能耗':'énergie adaptée à un usage intensif');if(use==='family'&&/7 places|7座|7 seat/.test(c.text))r.push(isZh?'多人家庭空间更合适':'7 places pour la famille');if(/suv/.test(c.text))r.push('SUV');return r.slice(0,3).join(' · ')||(isZh?'当前公开数据匹配度较高':'bon équilibre avec les données disponibles')}
function enhance(){const host=document.querySelector<HTMLElement>('#ai-advisor');if(!host||host.dataset.homeAdvisor==='1')return;host.dataset.homeAdvisor='1';const isZh=zh();const box=document.createElement('section');box.className='home-decision-advisor';box.innerHTML=`<div class="hda-head"><small>GREEN FAST SMART ADVISOR</small><h3>${isZh?'直接告诉我你怎么用车':'Dites-moi simplement comment vous allez utiliser la voiture'}</h3><p>${isZh?'例如：我做网约车，预算1800万，每天跑200公里。':'Ex. : Je fais du VTC, budget 18M, environ 200 km par jour.'}</p></div><div class="hda-input"><input placeholder="${isZh?'用途 + 预算 + 每天里程…':'Usage + budget + km par jour…'}"><button>${isZh?'帮我选':'Conseiller'}</button></div><div class="hda-result"></div>`;host.prepend(box);const input=box.querySelector('input') as HTMLInputElement,button=box.querySelector('button')!,result=box.querySelector('.hda-result')!;const run=()=>{const raw=clean(input.value);if(!raw)return;const use=useOf(raw.toLowerCase()),budget=money(raw.toLowerCase()),all=cards().map(c=>({...c,score:score(c,use,budget)})).sort((a,b)=>b.score-a.score).slice(0,3);result.innerHTML='';const intro=document.createElement('p');intro.className='hda-understood';intro.textContent=isZh?`已理解：${labels[use].z}${budget?` · 预算约${Math.round(budget/1e6)}M FCFA`:''}`:`Compris : ${labels[use].f}${budget?` · budget env. ${Math.round(budget/1e6)}M FCFA`:''}`;result.append(intro);all.forEach((c,i)=>{const a=document.createElement('article');a.innerHTML=`<b>#${i+1}</b><div><strong>${c.title}</strong><p>${reason(c,use,budget,isZh)}</p>${i===0?`<small>${isZh?'为什么第一：在当前公开车型数据里，它与你的用途和预算综合匹配度最高。':'Pourquoi n°1 : meilleur équilibre entre votre usage et votre budget dans les données actuellement disponibles.'}</small>`:''}</div>`;a.onclick=()=>c.el.scrollIntoView({behavior:'smooth',block:'center'});result.append(a)});if(all.length<2){const n=document.createElement('small');n.className='hda-caution';n.textContent=isZh?'当前符合条件的公开车型较少，可以放宽预算或用途条件。':'Peu de véhicules correspondent actuellement ; essayez d’élargir le budget ou l’usage.';result.append(n)}};button.onclick=run;input.onkeydown=e=>{if(e.key==='Enter')run()}}
function scan(){enhance()}if(typeof window!=='undefined'){window.addEventListener('DOMContentLoaded',scan,{once:true});new MutationObserver(scan).observe(document.documentElement,{childList:true,subtree:true})}
