import {useEffect,useMemo,useState} from 'react'
import {CarFront,ChevronLeft,Filter,Flame,Search,Star,X} from 'lucide-react'
import {supabase} from '../lib/supabase'
import './MarketplaceV1.css'

type Lang='fr'|'zh'
type Catalog={id:string;slug:string;brand:string;model:string;title_fr:string|null;title_zh:string|null;subtitle_fr:string|null;subtitle_zh:string|null;body_type:string|null;fuel_type:string|null;transmission:string|null;seats:number|null;cover_url:string|null;photos:string|null;price_from_xof:number|null;price_to_xof:number|null;availability:'en_stock'|'arrive_bientot'|'sur_commande';lead_time_min_days:number|null;lead_time_max_days:number|null;featured:boolean;sort_order:number}
type Variant={id:string;catalog_id:string;name_fr:string;name_zh:string|null;transmission:string|null;fuel_type:string|null;drivetrain:string|null;price_xof:number|null;deposit_xof:number|null;feature_summary:string|null;specs:Record<string,unknown>|null;sort_order:number}
type Inventory={id:string;make:string|null;model:string|null;trim:string|null;status:string|null;price_xof:number|null;photos:string|null;marketing_cover_url?:string|null;fuel_type?:string|null;transmission?:string|null;year?:number|null}
type Banner={id:string;title:string|null;title_fr?:string|null;title_zh?:string|null;subtitle:string|null;subtitle_fr?:string|null;subtitle_zh?:string|null;badge:string|null;badge_fr?:string|null;badge_zh?:string|null;cta_label:string|null;cta_label_fr?:string|null;cta_label_zh?:string|null;background_image:string|null;sort_order:number}
type MarketItem={key:string;kind:'catalog'|'inventory';catalog?:Catalog;inventory?:Inventory;brand:string;model:string;title:string;subtitle:string;price:number|null;fuel:string|null;transmission:string|null;seats:number|null;bodyType:string|null;image:string;availability:'en_stock'|'arrive_bientot'|'sur_commande';featured:boolean;score:number}

const COMPANY_WA='2250700737118'
const money=(n:number|null|undefined)=>n?new Intl.NumberFormat('fr-FR').format(Number(n))+' FCFA':'Prix sur demande'
const pics=(v:unknown)=>String(v||'').split(/\n|,/).map(x=>x.trim()).filter(x=>/^https?:\/\//.test(x))
const norm=(v:unknown)=>String(v||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()
const labels={
 fr:{title:'Trouvez votre prochaine voiture',sub:'Découvrez toute la sélection Green Fast Auto : en stock, en arrivage et sur commande.',search:'Rechercher une marque ou un modèle…',all:'Toutes les marques',price:'Prix',fuel:'Énergie',allPrice:'Tous les prix',allFuel:'Toutes',detail:'Voir le véhicule',reserve:'Réserver',from:'À partir de',stock:'En stock',soon:'Arrive bientôt',order:'Sur commande',delivery:'Délai estimé',days:'jours',config:'Choisissez une version',name:'Nom complet',phone:'Téléphone / WhatsApp',color:'Couleur souhaitée',notes:'Message / préférence',submit:'Envoyer la réservation',sent:'Réservation enregistrée',sentSub:'Notre équipe va confirmer le prix, la disponibilité et le délai.',whatsapp:'Continuer sur WhatsApp',back:'Retour aux véhicules',no:'Aucun véhicule ne correspond à vos filtres.',deposit:'Acompte indicatif',allCars:'Tous les véhicules',allCarsSub:'Notre sélection complète, avec stock réel et modèles sur commande.',choose:'Choisir une voiture',hot:'À la une',hotSub:'Les véhicules à voir en premier',suv:'SUV populaires',suvSub:'Nos SUV les plus attractifs du moment'},
 zh:{title:'选你的下一辆车',sub:'Green Fast Auto 全部车型都在这里：现车、在途、可订，一站式查看和预订。',search:'搜索品牌 / 车型…',all:'全部品牌',price:'价格',fuel:'动力',allPrice:'全部价格',allFuel:'全部动力',detail:'查看车型',reserve:'在线预订',from:'起售价',stock:'现车',soon:'即将到港',order:'可订',delivery:'预计交付',days:'天',config:'选择配置',name:'姓名',phone:'电话 / WhatsApp',color:'意向颜色',notes:'备注 / 配置需求',submit:'提交预订',sent:'预订已提交',sentSub:'销售会确认最终价格、库存和交期。',whatsapp:'继续 WhatsApp 沟通',back:'返回选车',no:'没有符合当前筛选条件的车型。',deposit:'参考订金',allCars:'全部车型',allCarsSub:'真实库存和可订车型放在一起，更容易找到适合你的车。',choose:'快速选车',hot:'热门推荐',hotSub:'先看最值得关注的车型',suv:'热销 SUV',suvSub:'当前更受欢迎的 SUV 车型'}
}
const btxt=(b:Banner,k:'title'|'subtitle'|'badge'|'cta_label',lang:Lang)=>String((b as any)[`${k}_${lang}`]||b[k]||'')
const availabilityText=(a:MarketItem['availability'],lang:Lang)=>a==='en_stock'?labels[lang].stock:a==='arrive_bientot'?labels[lang].soon:labels[lang].order
const statusClass=(a:MarketItem['availability'])=>a==='en_stock'?'stock':a==='arrive_bientot'?'soon':'order'
const invAvailability=(s:string|null):MarketItem['availability']=>['in_stock','reserved'].includes(String(s))?'en_stock':['in_transit','port','customs','ordered'].includes(String(s))?'arrive_bientot':'sur_commande'

export default function MarketplaceV1(){
 const[lang,setLang]=useState<Lang>('fr'),[catalog,setCatalog]=useState<Catalog[]>([]),[variants,setVariants]=useState<Variant[]>([]),[inventory,setInventory]=useState<Inventory[]>([]),[banners,setBanners]=useState<Banner[]>([]),[hero,setHero]=useState(0),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[brand,setBrand]=useState(''),[price,setPrice]=useState(''),[fuel,setFuel]=useState(''),[selected,setSelected]=useState<Catalog|null>(null),[reserve,setReserve]=useState(false)
 const x=labels[lang]
 useEffect(()=>{void(async()=>{if(!supabase)return;setLoading(true);const[{data:c},{data:v},{data:i},{data:b}]=await Promise.all([supabase.from('vehicle_catalog').select('*').eq('published',true).order('sort_order'),supabase.from('vehicle_catalog_variants').select('*').eq('active',true).order('sort_order'),supabase.from('public_vehicle_catalog').select('id,make,model,trim,status,price_xof,photos,marketing_cover_url,fuel_type,transmission,year').order('created_at',{ascending:false}),supabase.from('showroom_banners').select('id,title,title_fr,title_zh,subtitle,subtitle_fr,subtitle_zh,badge,badge_fr,badge_zh,cta_label,cta_label_fr,cta_label_zh,background_image,sort_order').eq('enabled',true).order('sort_order')]);setCatalog((c||[])as Catalog[]);setVariants((v||[])as Variant[]);setInventory((i||[])as Inventory[]);setBanners((b||[])as Banner[]);setLoading(false)})()},[])
 useEffect(()=>{if(banners.length<2)return;const timer=window.setInterval(()=>setHero(h=>(h+1)%banners.length),6500);return()=>window.clearInterval(timer)},[banners.length])
 const stockFor=(c:Catalog)=>inventory.filter(i=>{const cm=norm(c.model),im=norm(i.model),make=norm(i.make);return Boolean(cm)&&(im.includes(cm)||cm.includes(im)||make.includes(norm(c.brand))&&im.includes(cm.split(' ')[0]))}).filter(i=>['in_stock','reserved','in_transit','port','customs','ordered'].includes(String(i.status)))
 const allItems=useMemo<MarketItem[]>(()=>{
   const used=new Set<string>()
   const catalogItems=catalog.map(c=>{const inv=stockFor(c);inv.forEach(i=>used.add(i.id));const realStock=inv.some(i=>['in_stock','reserved'].includes(String(i.status)));const arriving=inv.length>0&&!realStock;const image=c.cover_url||pics(c.photos)[0]||inv.map(i=>i.marketing_cover_url||pics(i.photos)[0]).find(Boolean)||'';const availability:MarketItem['availability']=realStock?'en_stock':arriving?'arrive_bientot':c.availability;const score=(realStock?90:arriving?72:48)+(c.featured?20:0)+(image?12:0)-Math.min(c.sort_order||100,100)/20;return{key:`c-${c.id}`,kind:'catalog' as const,catalog:c,brand:c.brand,model:c.model,title:lang==='fr'?(c.title_fr||`${c.brand} ${c.model}`):(c.title_zh||`${c.brand} ${c.model}`),subtitle:(lang==='fr'?c.subtitle_fr:c.subtitle_zh)||'',price:c.price_from_xof,fuel:c.fuel_type,transmission:c.transmission,seats:c.seats,bodyType:c.body_type,image,availability,featured:c.featured,score}})
   const inventoryItems=inventory.filter(i=>!used.has(i.id)&&pics(i.marketing_cover_url||i.photos).length>0).map((i,idx)=>{const availability=invAvailability(i.status);const score=(availability==='en_stock'?100:82)+(i.marketing_cover_url?8:4)-idx*.2;return{key:`i-${i.id}`,kind:'inventory' as const,inventory:i,brand:String(i.make||'Green Fast'),model:String(i.model||''),title:[i.make,i.model].filter(Boolean).join(' '),subtitle:[i.trim,i.year].filter(Boolean).join(' · '),price:i.price_xof,image:i.marketing_cover_url||pics(i.photos)[0]||'',fuel:i.fuel_type||null,transmission:i.transmission||null,seats:null,bodyType:'SUV',availability,featured:false,score}})
   const a=[...catalogItems].sort((m,n)=>n.score-m.score),b=[...inventoryItems].sort((m,n)=>n.score-m.score),out:MarketItem[]=[];let ci=0,ii=0,turn=inventoryItems.length>0&&catalogItems.some(i=>!i.image)?'inventory':'catalog';while(ci<a.length||ii<b.length){if(turn==='inventory'&&ii<b.length){out.push(b[ii++]);turn='catalog'}else if(ci<a.length){out.push(a[ci++]);turn='inventory'}else if(ii<b.length)out.push(b[ii++])}return out
 },[catalog,inventory,lang])
 const brands=useMemo(()=>Array.from(new Set(allItems.map(c=>c.brand))).filter(Boolean).sort(),[allItems])
 const visible=useMemo(()=>allItems.filter(c=>{const q=query.trim().toLowerCase();if(q&&!`${c.brand} ${c.model} ${c.title}`.toLowerCase().includes(q))return false;if(brand&&c.brand!==brand)return false;const p=Number(c.price||0);if(price==='lt15'&&p>=15000000)return false;if(price==='15to20'&&(p<15000000||p>=20000000))return false;if(price==='20to25'&&(p<20000000||p>=25000000))return false;if(price==='25to30'&&(p<25000000||p>=30000000))return false;if(price==='30plus'&&p<30000000)return false;if(fuel&&c.fuel!==fuel)return false;return true}),[allItems,query,brand,price,fuel])
 const hot=useMemo(()=>allItems.filter(i=>i.image).slice(0,6),[allItems])
 const suv=useMemo(()=>allItems.filter(i=>/suv|4x4|crossover|t2|cs55|cs75|gs3/i.test(`${i.bodyType||''} ${i.model}`)&&i.image).slice(0,6),[allItems])
 if(selected)return <VehiclePage lang={lang} catalog={selected} variants={variants.filter(v=>v.catalog_id===selected.id)} inventory={stockFor(selected)} back={()=>{setSelected(null);setReserve(false)}} reserve={reserve} setReserve={setReserve}/>
 const hasFilters=Boolean(query||brand||price||fuel),activeBanner=banners[hero]
 const openItem=(item:MarketItem,wantsReserve=false)=>{if(item.catalog){setSelected(item.catalog);setReserve(wantsReserve)}else if(item.inventory){window.location.href=`https://wa.me/${COMPANY_WA}?text=${encodeURIComponent(`${lang==='fr'?'Bonjour, je souhaite des informations sur':'你好，我想咨询'} ${item.title}`)}`}}
 const Cards=({items,compact=false}:{items:MarketItem[];compact?:boolean})=><section className={compact?'market-grid discovery-grid':'market-grid'}>{items.map(item=><article key={item.key} className="market-card"><div className="card-media" onClick={()=>openItem(item)}>{item.image?<img src={item.image}/>:<div className="car-placeholder"><CarFront/></div>}<span className={`availability ${statusClass(item.availability)}`}>{availabilityText(item.availability,lang)}</span></div><div className="card-copy"><small>{item.brand}</small><h2>{item.title}</h2>{item.subtitle&&<p>{item.subtitle}</p>}<div className="price-line"><span>{x.from}</span><strong>{money(item.price)}</strong></div><div className="mini-specs">{item.transmission&&<span>{item.transmission}</span>}{item.fuel&&<span>{item.fuel}</span>}{item.seats&&<span>{item.seats} {lang==='fr'?'places':'座'}</span>}</div><div className="card-actions"><button onClick={()=>openItem(item)}>{x.detail}</button><button className="primary" onClick={()=>openItem(item,true)}>{item.kind==='inventory'?(lang==='fr'?'WhatsApp':'WhatsApp'):x.reserve}</button></div></div></article>)}</section>
 return <div className="market-v1">
  <header className="market-nav"><div className="market-logo"><span><CarFront/></span><div><strong>GREEN FAST</strong><small>AUTO</small></div></div><div className="market-nav-actions"><a href="#cars">{lang==='fr'?'Véhicules':'选车'}</a><button onClick={()=>setLang(lang==='fr'?'zh':'fr')}>{lang==='fr'?'中文':'FR'}</button><a className="wa" href={`https://wa.me/${COMPANY_WA}`}>WhatsApp</a></div></header>
  {activeBanner?<section className="market-banner" style={{backgroundImage:`linear-gradient(90deg,rgba(8,18,12,.74),rgba(8,18,12,.12)),url(${activeBanner.background_image||''})`}}><div className="banner-copy">{btxt(activeBanner,'badge',lang)&&<span>{btxt(activeBanner,'badge',lang)}</span>}<h1>{btxt(activeBanner,'title',lang)||x.title}</h1><p>{btxt(activeBanner,'subtitle',lang)||x.sub}</p><a href="#cars">{btxt(activeBanner,'cta_label',lang)||x.choose}</a></div>{banners.length>1&&<div className="banner-dots">{banners.map((b,i)=><button key={b.id} className={i===hero?'active':''} onClick={()=>setHero(i)} aria-label={`banner ${i+1}`}/>)}</div>}</section>:<section className="market-banner fallback"><div className="banner-copy"><span>GREEN FAST AUTO · ABIDJAN</span><h1>{x.title}</h1><p>{x.sub}</p></div></section>}
  <section className="market-chooser"><div><div className="hero-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={x.search}/></div><div className="chooser-filters"><label><select aria-label={lang==='fr'?'Marque':'品牌'} value={brand} onChange={e=>setBrand(e.target.value)}><option value="">{x.all}</option>{brands.map(b=><option key={b} value={b}>{b}</option>)}</select></label><label><select aria-label={x.price} value={price} onChange={e=>setPrice(e.target.value)}><option value="">{x.allPrice}</option><option value="lt15">&lt; 15M</option><option value="15to20">15–20M</option><option value="20to25">20–25M</option><option value="25to30">25–30M</option><option value="30plus">30M+</option></select></label><label><select aria-label={x.fuel} value={fuel} onChange={e=>setFuel(e.target.value)}><option value="">{x.allFuel}</option><option value="petrol">{lang==='fr'?'Essence':'汽油'}</option><option value="hybrid">{lang==='fr'?'Hybride':'混动'}</option><option value="electric">{lang==='fr'?'Électrique':'纯电'}</option><option value="diesel">Diesel</option></select></label>{hasFilters&&<button className="clear-filters" onClick={()=>{setQuery('');setBrand('');setPrice('');setFuel('')}}>{lang==='fr'?'Réinitialiser':'清除'}</button>}</div></div></section>
  {!hasFilters&&hot.length>0&&<section className="discovery-section"><div className="discovery-head"><div><Flame/><span>{x.hotSub}</span><h2>{x.hot}</h2></div></div><Cards items={hot}/></section>}
  {!hasFilters&&suv.length>1&&<section className="discovery-section suv-section"><div className="discovery-head"><div><Star/><span>{x.suvSub}</span><h2>{x.suv}</h2></div></div><Cards items={suv}/></section>}
  <main id="cars" className="market-main"><div className="market-section-head"><div><span>GREEN FAST SELECT</span><h2>{x.allCars}</h2><p>{x.allCarsSub}</p></div><div className="market-count"><b>{loading?'…':visible.length}</b><span>{lang==='fr'?'modèles disponibles':'款车型可选'}</span></div></div>{loading?<div className="market-loading">Loading…</div>:visible.length===0?<div className="market-empty"><Filter/><p>{x.no}</p></div>:<Cards items={visible}/>}</main>
 </div>
}

function VehiclePage({lang,catalog,variants,inventory,back,reserve,setReserve}:{lang:Lang;catalog:Catalog;variants:Variant[];inventory:Inventory[];back:()=>void;reserve:boolean;setReserve:(v:boolean)=>void}){
 const x=labels[lang],[variantId,setVariantId]=useState(variants[0]?.id||''),[photo,setPhoto]=useState(0);const variant=variants.find(v=>v.id===variantId)||variants[0];const gallery=Array.from(new Set([catalog.cover_url,...pics(catalog.photos),...inventory.flatMap(i=>[i.marketing_cover_url,...pics(i.photos)])].filter(Boolean) as string[]));const stock=inventory.filter(i=>i.status==='in_stock').length
 return <div className="market-v1"><header className="market-nav"><button className="market-back" onClick={back}><ChevronLeft/>{x.back}</button><button onClick={()=>setReserve(true)} className="nav-reserve">{x.reserve}</button></header><main className="vehicle-page"><section className="vehicle-gallery-v1"><div className="vehicle-main-photo">{gallery[photo]?<img src={gallery[photo]}/>:<CarFront/>}</div>{gallery.length>1&&<div className="vehicle-thumbs">{gallery.map((p,i)=><button className={photo===i?'active':''} key={p} onClick={()=>setPhoto(i)}><img src={p}/></button>)}</div>}</section><aside className="vehicle-buybox"><span className={`availability ${stock?'stock':catalog.availability==='arrive_bientot'?'soon':'order'}`}>{stock?x.stock:catalog.availability==='arrive_bientot'?x.soon:x.order}</span><small>{catalog.brand}</small><h1>{lang==='fr'?(catalog.title_fr||`${catalog.brand} ${catalog.model}`):(catalog.title_zh||`${catalog.brand} ${catalog.model}`)}</h1><p>{lang==='fr'?catalog.subtitle_fr:catalog.subtitle_zh}</p><div className="buy-price"><span>{x.from}</span><strong>{money(variant?.price_xof||catalog.price_from_xof)}</strong></div>{variants.length>0&&<div className="variant-picker"><label>{x.config}</label>{variants.map(v=><button className={variantId===v.id?'active':''} key={v.id} onClick={()=>setVariantId(v.id)}><span>{lang==='fr'?v.name_fr:(v.name_zh||v.name_fr)}</span><b>{money(v.price_xof)}</b></button>)}</div>}<div className="delivery-box"><div><span>{x.delivery}</span><b>{catalog.lead_time_min_days||30}–{catalog.lead_time_max_days||45} {x.days}</b></div><div><span>{x.deposit}</span><b>{money(variant?.deposit_xof||200000)}</b></div></div><button className="reserve-big" onClick={()=>setReserve(true)}>{x.reserve}</button><a className="whatsapp-big" href={`https://wa.me/${COMPANY_WA}?text=${encodeURIComponent(`${lang==='fr'?'Bonjour, je souhaite des informations sur':'你好，我想咨询'} ${catalog.brand} ${catalog.model}`)}`}>WhatsApp</a></aside></main>{reserve&&<ReservationModal lang={lang} catalog={catalog} variant={variant||null} close={()=>setReserve(false)}/>}</div>
}

function ReservationModal({lang,catalog,variant,close}:{lang:Lang;catalog:Catalog;variant:Variant|null;close:()=>void}){const x=labels[lang],[form,setForm]=useState({name:'',phone:'',color:'',notes:''}),[busy,setBusy]=useState(false),[done,setDone]=useState(false),[ref,setRef]=useState(''),[error,setError]=useState('');const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!supabase)return;setBusy(true);setError('');const{data,error}=await supabase.rpc('create_vehicle_catalog_reservation',{p_catalog_id:catalog.id,p_variant_id:variant?.id||null,p_customer_name:form.name,p_phone:form.phone,p_whatsapp:form.phone,p_preferred_color:form.color||null,p_notes:form.notes||null});setBusy(false);if(error)setError(error.message);else{setRef(String(data||''));setDone(true)}};const wa=`https://wa.me/${COMPANY_WA}?text=${encodeURIComponent(`${lang==='fr'?'Bonjour, je viens de réserver':'你好，我刚刚预订了'} ${catalog.brand} ${catalog.model}${variant?` · ${lang==='fr'?variant.name_fr:(variant.name_zh||variant.name_fr)}`:''}${ref?` · Ref ${ref.slice(0,8)}`:''}`)}`;return <div className="reservation-layer"><div className="reservation-modal"><button className="reservation-close" onClick={close}><X/></button>{done?<div className="reservation-done"><div>✓</div><h2>{x.sent}</h2><p>{x.sentSub}</p><strong>{catalog.brand} {catalog.model}</strong>{variant&&<span>{lang==='fr'?variant.name_fr:(variant.name_zh||variant.name_fr)} · {money(variant.price_xof)}</span>}<a href={wa}>{x.whatsapp}</a></div>:<form onSubmit={submit}><small>GREEN FAST AUTO · RÉSERVATION</small><h2>{catalog.brand} {catalog.model}</h2>{variant&&<p>{lang==='fr'?variant.name_fr:(variant.name_zh||variant.name_fr)} · {money(variant.price_xof)}</p>}<label>{x.name}<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>{x.phone}<input required inputMode="tel" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>{x.color}<input value={form.color} onChange={e=>setForm({...form,color:e.target.value})}/></label><label>{x.notes}<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label>{error&&<div className="reserve-error">{error}</div>}<button disabled={busy}>{busy?'…':x.submit}</button></form>}</div></div>}
