import {useEffect,useMemo,useState} from 'react'
import {BriefcaseBusiness,CarFront,ChevronLeft,Clock3,Filter,Flame,Leaf,Mic,Mountain,Search,Sparkles,Star,UsersRound,WalletCards,X} from 'lucide-react'
import {supabase} from '../lib/supabase'
import './MarketplaceV1.css'

type Lang='fr'|'zh'
type Intent=''|'family'|'hybrid'|'adventure'|'business'
type Condition='all'|'new'|'used'
type Catalog={id:string;slug:string;brand:string;model:string;title_fr:string|null;title_zh:string|null;subtitle_fr:string|null;subtitle_zh:string|null;body_type:string|null;fuel_type:string|null;transmission:string|null;seats:number|null;cover_url:string|null;photos:string|null;price_from_xof:number|null;price_to_xof:number|null;availability:'en_stock'|'arrive_bientot'|'sur_commande';lead_time_min_days:number|null;lead_time_max_days:number|null;featured:boolean;sort_order:number;vehicle_condition?:'new'|'used'|null}
type Variant={id:string;catalog_id:string;name_fr:string;name_zh:string|null;transmission:string|null;fuel_type:string|null;drivetrain:string|null;price_xof:number|null;deposit_xof:number|null;feature_summary:string|null;specs:Record<string,unknown>|null;sort_order:number}
type Inventory={id:string;make:string|null;model:string|null;trim:string|null;status:string|null;price_xof:number|null;photos:string|null;marketing_cover_url?:string|null;fuel_type?:string|null;transmission?:string|null;year?:number|null;mileage?:number|null;body_type?:string|null;seats?:number|null;eta_abidjan?:string|null;arrival_date?:string|null;created_at?:string|null;vehicle_condition?:'new'|'used'|null}
type Banner={id:string;title:string|null;title_fr?:string|null;title_zh?:string|null;subtitle:string|null;subtitle_fr?:string|null;subtitle_zh?:string|null;badge:string|null;badge_fr?:string|null;badge_zh?:string|null;cta_label:string|null;cta_label_fr?:string|null;cta_label_zh?:string|null;background_image:string|null;sort_order:number}
type MarketItem={key:string;kind:'catalog'|'inventory';catalog?:Catalog;inventory?:Inventory;brand:string;model:string;title:string;subtitle:string;price:number|null;fuel:string|null;transmission:string|null;seats:number|null;bodyType:string|null;image:string;availability:'en_stock'|'arrive_bientot'|'sur_commande';featured:boolean;score:number;date:string|null;condition:'new'|'used'|null;mileage:number|null}

const COMPANY_WA='2250700737118'
const money=(n:number|null|undefined)=>n?new Intl.NumberFormat('fr-FR').format(Number(n))+' FCFA':'Prix sur demande'
const pics=(v:unknown)=>String(v||'').split(/\n|,/).map(x=>x.trim()).filter(x=>/^https?:\/\//.test(x))
const norm=(v:unknown)=>String(v||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()
const isSuv=(i:MarketItem)=>/suv|4x4|crossover|t2|cs55|cs75|gs3|r08|tai 7|钛7/i.test(`${i.bodyType||''} ${i.model}`)
const isChinese=(i:MarketItem)=>/changan|jetour|gac|chery|rely|byd|geely|lynk|formula|长安|捷途|广汽|奇瑞|威麟|比亚迪|吉利|领克|方程豹/i.test(`${i.brand} ${i.model}`)
const isHybrid=(i:MarketItem)=>/hybrid|hev|phev|hybride|混动/i.test(`${i.fuel||''} ${i.model} ${i.subtitle}`)
const isAdventure=(i:MarketItem)=>/4x4|offroad|off-road|t2|r08|pickup|越野|皮卡/i.test(`${i.bodyType||''} ${i.model} ${i.subtitle}`)
const shortTitle=(brand:string,model:string)=>{const first=String(model||'').split('/')[0].replace(/\s+/g,' ').trim();const raw=`${brand} ${first}`.replace(new RegExp(`^${brand}\\s+${brand}\\s+`,'i'),`${brand} `);return raw.length>48?`${raw.slice(0,47).trim()}…`:raw}
const labels={
 fr:{title:'Trouvez votre prochaine voiture',sub:'Découvrez toute la sélection Green Fast Auto : en stock, en arrivage et sur commande.',search:'Décrivez votre besoin : “SUV familial autour de 20M, économique…”',all:'Toutes les marques',price:'Prix',fuel:'Énergie',allPrice:'Tous les prix',allFuel:'Toutes',detail:'Voir le véhicule',reserve:'Réserver',from:'À partir de',stock:'En stock',soon:'Arrive bientôt',order:'Sur commande',delivery:'Délai estimé',days:'jours',config:'Choisissez une version',name:'Nom complet',phone:'Téléphone / WhatsApp',color:'Couleur souhaitée',notes:'Message / préférence',submit:'Envoyer la réservation',sent:'Réservation enregistrée',sentSub:'Notre équipe va confirmer le prix, la disponibilité et le délai.',whatsapp:'Continuer sur WhatsApp',back:'Retour aux véhicules',no:'Aucun véhicule ne correspond à vos filtres.',deposit:'Acompte indicatif',allCars:'Tous les véhicules',allCarsSub:'Notre sélection complète, avec stock réel et modèles sur commande.',choose:'Choisir une voiture',hot:'À la une',hotSub:'Les véhicules à voir en premier',newCars:'Nouveautés',newSub:'Stock disponible et prochains arrivages',budget:'Choisir par budget',budgetSub:'Commencez par votre budget, pas par une marque',chinaSuv:'SUV chinois populaires',chinaSuvSub:'Une sélection SUV pensée pour le marché d’Abidjan',useTitle:'Choisir selon votre usage',useSub:'Pas besoin de connaître les marques : partez de votre vrai besoin.',aiTitle:'Recherche intelligente',aiHint:'Parlez ou écrivez votre besoin. Nous transformons votre phrase en critères de sélection.',allCondition:'Tous',newCondition:'Neufs',usedCondition:'Occasion'},
 zh:{title:'选你的下一辆车',sub:'Green Fast Auto 全部车型都在这里：现车、在途、可订，一站式查看和预订。',search:'直接说需求：例如“2000万左右、省油、家用SUV”',all:'全部品牌',price:'价格',fuel:'动力',allPrice:'全部价格',allFuel:'全部动力',detail:'查看车型',reserve:'在线预订',from:'起售价',stock:'现车',soon:'即将到港',order:'可订',delivery:'预计交付',days:'天',config:'选择配置',name:'姓名',phone:'电话 / WhatsApp',color:'意向颜色',notes:'备注 / 配置需求',submit:'提交预订',sent:'预订已提交',sentSub:'销售会确认最终价格、库存和交期。',whatsapp:'继续 WhatsApp 沟通',back:'返回选车',no:'没有符合当前筛选条件的车型。',deposit:'参考订金',allCars:'全部车型',allCarsSub:'真实库存和可订车型放在一起，更容易找到适合你的车。',choose:'快速选车',hot:'热门推荐',hotSub:'先看最值得关注的车型',newCars:'新到车辆',newSub:'现车和即将到港的车优先看',budget:'预算选车',budgetSub:'不懂品牌也没关系，先从预算开始',chinaSuv:'热门中国 SUV',chinaSuvSub:'更适合阿比让客户继续比较的中国 SUV',useTitle:'按用途找车',useSub:'不用先懂品牌，先告诉我们你准备怎么用这辆车。',aiTitle:'AI 智能选车',aiHint:'可以直接说人话，系统会把预算、用途、动力和车型要求转成筛选条件。',allCondition:'全部',newCondition:'新车',usedCondition:'二手车'}
}
const btxt=(b:Banner,k:'title'|'subtitle'|'badge'|'cta_label',lang:Lang)=>String((b as any)[`${k}_${lang}`]||b[k]||'')
const availabilityText=(a:MarketItem['availability'],lang:Lang)=>a==='en_stock'?labels[lang].stock:a==='arrive_bientot'?labels[lang].soon:labels[lang].order
const statusClass=(a:MarketItem['availability'])=>a==='en_stock'?'stock':a==='arrive_bientot'?'soon':'order'
const invAvailability=(s:string|null):MarketItem['availability']=>['in_stock','reserved'].includes(String(s))?'en_stock':['in_transit','port','customs','ordered'].includes(String(s))?'arrive_bientot':'sur_commande'

export default function MarketplaceV1(){
 const[lang,setLang]=useState<Lang>('fr'),[catalog,setCatalog]=useState<Catalog[]>([]),[variants,setVariants]=useState<Variant[]>([]),[inventory,setInventory]=useState<Inventory[]>([]),[banners,setBanners]=useState<Banner[]>([]),[hero,setHero]=useState(0),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[aiPrompt,setAiPrompt]=useState(''),[aiNote,setAiNote]=useState(''),[aiSuv,setAiSuv]=useState(false),[listening,setListening]=useState(false),[brand,setBrand]=useState(''),[price,setPrice]=useState(''),[fuel,setFuel]=useState(''),[intent,setIntent]=useState<Intent>(''),[condition,setCondition]=useState<Condition>('all'),[selected,setSelected]=useState<Catalog|null>(null),[selectedInventory,setSelectedInventory]=useState<Inventory|null>(null),[reserve,setReserve]=useState(false)
 const x=labels[lang]
 useEffect(()=>{void(async()=>{if(!supabase)return;setLoading(true);const[{data:c},{data:v},{data:i},{data:b}]=await Promise.all([supabase.from('vehicle_catalog').select('*').eq('published',true).order('sort_order'),supabase.from('vehicle_catalog_variants').select('*').eq('active',true).order('sort_order'),supabase.from('public_vehicle_catalog').select('id,make,model,trim,status,price_xof,photos,marketing_cover_url,fuel_type,transmission,year,mileage,body_type,seats,eta_abidjan,arrival_date,created_at,vehicle_condition').order('created_at',{ascending:false}),supabase.from('showroom_banners').select('id,title,title_fr,title_zh,subtitle,subtitle_fr,subtitle_zh,badge,badge_fr,badge_zh,cta_label,cta_label_fr,cta_label_zh,background_image,sort_order').eq('enabled',true).order('sort_order')]);setCatalog((c||[])as Catalog[]);setVariants((v||[])as Variant[]);setInventory((i||[])as Inventory[]);setBanners((b||[])as Banner[]);setLoading(false)})()},[])
 useEffect(()=>{if(banners.length<2)return;const timer=window.setInterval(()=>setHero(h=>(h+1)%banners.length),6500);return()=>window.clearInterval(timer)},[banners.length])
 const stockFor=(c:Catalog)=>inventory.filter(i=>{const cm=norm(c.model),im=norm(i.model),make=norm(i.make);return Boolean(cm)&&(im.includes(cm)||cm.includes(im)||make.includes(norm(c.brand))&&im.includes(cm.split(' ')[0]))}).filter(i=>['in_stock','reserved','in_transit','port','customs','ordered'].includes(String(i.status)))
 const allItems=useMemo<MarketItem[]>(()=>{
   const used=new Set<string>()
   const catalogItems=catalog.map(c=>{const inv=stockFor(c);inv.forEach(i=>used.add(i.id));const realStock=inv.some(i=>['in_stock','reserved'].includes(String(i.status)));const arriving=inv.length>0&&!realStock;const image=c.cover_url||pics(c.photos)[0]||inv.map(i=>i.marketing_cover_url||pics(i.photos)[0]).find(Boolean)||'';const availability:MarketItem['availability']=realStock?'en_stock':arriving?'arrive_bientot':c.availability;const score=(realStock?90:arriving?72:48)+(c.featured?20:0)+(image?12:0)-Math.min(c.sort_order||100,100)/20;const dated=inv.map(i=>i.arrival_date||i.eta_abidjan||i.created_at||'').filter(Boolean).sort().reverse()[0]||null;return{key:`c-${c.id}`,kind:'catalog' as const,catalog:c,brand:c.brand,model:c.model,title:shortTitle(c.brand,c.model),subtitle:(lang==='fr'?c.subtitle_fr:c.subtitle_zh)||'',price:c.price_from_xof,fuel:c.fuel_type,transmission:c.transmission,seats:c.seats,bodyType:c.body_type,image,availability,featured:c.featured,score,date:dated,condition:c.vehicle_condition||'new',mileage:null}})
   const inventoryItems=inventory.filter(i=>!used.has(i.id)&&pics(i.marketing_cover_url||i.photos).length>0).map((i,idx)=>{const availability=invAvailability(i.status);const score=(availability==='en_stock'?100:82)+(i.marketing_cover_url?8:4)-idx*.2;const make=String(i.make||'Green Fast'),model=String(i.model||'');return{key:`i-${i.id}`,kind:'inventory' as const,inventory:i,brand:make,model,title:shortTitle(make,model),subtitle:[i.trim,i.year].filter(Boolean).join(' · '),price:i.price_xof,image:i.marketing_cover_url||pics(i.photos)[0]||'',fuel:i.fuel_type||null,transmission:i.transmission||null,seats:i.seats||null,bodyType:i.body_type||'SUV',availability,featured:false,score,date:i.arrival_date||i.eta_abidjan||i.created_at||null,condition:i.vehicle_condition||null,mileage:i.mileage??null}})
   const a=[...catalogItems].sort((m,n)=>n.score-m.score),b=[...inventoryItems].sort((m,n)=>n.score-m.score),out:MarketItem[]=[];let ci=0,ii=0,turn=inventoryItems.length>0&&catalogItems.some(i=>!i.image)?'inventory':'catalog';while(ci<a.length||ii<b.length){if(turn==='inventory'&&ii<b.length){out.push(b[ii++]);turn='catalog'}else if(ci<a.length){out.push(a[ci++]);turn='inventory'}else if(ii<b.length)out.push(b[ii++])}return out
 },[catalog,inventory,lang])
 const brands=useMemo(()=>Array.from(new Set(allItems.map(c=>c.brand))).filter(Boolean).sort(),[allItems])
 const visible=useMemo(()=>allItems.filter(c=>{const q=query.trim().toLowerCase();if(q&&!`${c.brand} ${c.model} ${c.title} ${c.bodyType||''}`.toLowerCase().includes(q))return false;if(brand&&c.brand!==brand)return false;if(condition!=='all'&&c.condition!==condition)return false;if(aiSuv&&!isSuv(c))return false;const p=Number(c.price||0);if(price==='lt15'&&p>=15000000)return false;if(price==='15to20'&&(p<15000000||p>=20000000))return false;if(price==='20to25'&&(p<20000000||p>=25000000))return false;if(price==='25to30'&&(p<25000000||p>=30000000))return false;if(price==='30plus'&&p<30000000)return false;if(price==='around20suv'&&(p<17000000||p>23000000||!isSuv(c)))return false;if(fuel&&c.fuel!==fuel)return false;if(intent==='family'&&!((c.seats||0)>=7||/7.?seat|7.?place|7座|family/i.test(`${c.subtitle} ${c.model}`)))return false;if(intent==='hybrid'&&!isHybrid(c))return false;if(intent==='adventure'&&!isAdventure(c))return false;if(intent==='business'&&!(/sedan|suv|business|executive|premium/i.test(`${c.bodyType||''} ${c.subtitle}`)&&Number(c.price||0)>=18000000))return false;return true}),[allItems,query,brand,price,fuel,intent,condition,aiSuv])
 const hot=useMemo(()=>allItems.filter(i=>i.image).slice(0,6),[allItems])
 const arrivals=useMemo(()=>allItems.filter(i=>i.image&&i.availability!=='sur_commande').sort((a,b)=>{const av=a.availability==='en_stock'?2:1,bv=b.availability==='en_stock'?2:1;if(av!==bv)return bv-av;const ad=a.date?Date.parse(a.date):0,bd=b.date?Date.parse(b.date):0;return bd-ad||b.score-a.score}).slice(0,6),[allItems])
 const chinaSuv=useMemo(()=>allItems.filter(i=>i.image&&isSuv(i)&&isChinese(i)).sort((a,b)=>b.score-a.score).slice(0,6),[allItems])
 const hybridCars=useMemo(()=>allItems.filter(i=>i.image&&isHybrid(i)).sort((a,b)=>b.score-a.score).slice(0,6),[allItems])
 const advisorResults=useMemo(()=>visible.filter(i=>i.image).sort((a,b)=>b.score-a.score).slice(0,3),[visible])
 const budgetOptions=lang==='fr'?[{label:'Moins de 15M',sub:'Pratique & accessible',value:'lt15'},{label:'15–20M',sub:'Le cœur du marché SUV',value:'15to20'},{label:'Autour de 20M',sub:'SUV 17–23M',value:'around20suv'},{label:'25M+',sub:'Premium & aventure',value:'30plus'}]:[{label:'15M以内',sub:'实用、好入手',value:'lt15'},{label:'15–20M',sub:'主流 SUV 预算',value:'15to20'},{label:'20M左右SUV',sub:'17–23M 快速筛选',value:'around20suv'},{label:'25M以上',sub:'高端 / 越野',value:'30plus'}]
 const useOptions=lang==='fr'?[{key:'family' as Intent,label:'Famille / 7 places',sub:'Plus d’espace pour toute la famille',icon:UsersRound},{key:'hybrid' as Intent,label:'Économique / Hybride',sub:'Réduire la consommation au quotidien',icon:Leaf},{key:'adventure' as Intent,label:'4x4 / Aventure',sub:'Routes difficiles, look plus robuste',icon:Mountain},{key:'business' as Intent,label:'Business / Réception',sub:'Image, confort et rendez-vous clients',icon:BriefcaseBusiness}]:[{key:'family' as Intent,label:'家庭 / 7座 SUV',sub:'空间更大，适合全家出行',icon:UsersRound},{key:'hybrid' as Intent,label:'省油 / 混动车',sub:'更适合高频日常用车',icon:Leaf},{key:'adventure' as Intent,label:'越野 / 硬派 SUV',sub:'烂路、长途和更强通过性',icon:Mountain},{key:'business' as Intent,label:'商务 / 接待用车',sub:'形象、舒适和客户接待',icon:BriefcaseBusiness}]
 const advisorReason=(item:MarketItem)=>{const reasons:string[]=[];if(item.availability==='en_stock')reasons.push(lang==='fr'?'disponible en stock':'现车可提');else if(item.availability==='arrive_bientot')reasons.push(lang==='fr'?'arrivage proche':'即将到港');if(aiSuv&&isSuv(item))reasons.push('SUV');if(intent==='hybrid'&&isHybrid(item))reasons.push(lang==='fr'?'économie de carburant':'更省油');if(intent==='family'&&((item.seats||0)>=7||/family|7.?place|7座/i.test(`${item.subtitle} ${item.model}`)))reasons.push(lang==='fr'?'adapté à la famille':'适合家庭');if(intent==='adventure'&&isAdventure(item))reasons.push(lang==='fr'?'adapté aux routes difficiles':'更适合复杂路况');if(item.condition==='used')reasons.push(lang==='fr'?`${item.inventory?.year||''} · ${item.mileage!=null?new Intl.NumberFormat('fr-FR').format(item.mileage)+' km':'occasion'}`:`${item.inventory?.year||''} · ${item.mileage!=null?new Intl.NumberFormat('zh-CN').format(item.mileage)+'km':'二手车'}`);if(item.price)reasons.push(lang==='fr'?`budget ${Math.round(item.price/1000000)}M`:`约${Math.round(item.price/1000000)}M预算`);return reasons.slice(0,3).join(' · ')|| (lang==='fr'?'Bon équilibre prix, disponibilité et usage.':'价格、库存和用途匹配度较均衡。')}
 if(selectedInventory)return <InventoryPage lang={lang} vehicle={selectedInventory} back={()=>setSelectedInventory(null)}/>
 if(selected)return <VehiclePage lang={lang} catalog={selected} variants={variants.filter(v=>v.catalog_id===selected.id)} inventory={stockFor(selected)} back={()=>{setSelected(null);setReserve(false)}} reserve={reserve} setReserve={setReserve}/>
 const hasFilters=Boolean(query||brand||price||fuel||intent||condition!=='all'||aiSuv),activeBanner=banners[hero]
 const openItem=(item:MarketItem,wantsReserve=false)=>{if(item.catalog){setSelectedInventory(null);setSelected(item.catalog);setReserve(wantsReserve)}else if(item.inventory){if(wantsReserve){window.location.href=`https://wa.me/${COMPANY_WA}?text=${encodeURIComponent(`${lang==='fr'?'Bonjour, je souhaite des informations sur':'你好，我想咨询'} ${item.title}`)}`} `}else{setSelected(null);setSelectedInventory(item.inventory)}}}
 const applyBudget=(value:string)=>{setQuery('');setBrand('');setFuel('');setIntent('');setAiSuv(false);setPrice(value);window.setTimeout(()=>document.getElementById('cars')?.scrollIntoView({behavior:'smooth',block:'start'}),80)}
 const applyIntent=(value:Intent)=>{setQuery('');setBrand('');setFuel('');setPrice('');setAiSuv(false);setIntent(value);window.setTimeout(()=>document.getElementById('cars')?.scrollIntoView({behavior:'smooth',block:'start'}),80)}
 const clearFilters=()=>{setQuery('');setBrand('');setPrice('');setFuel('');setIntent('');setCondition('all');setAiSuv(false);setAiNote('')}
 const runSmartSearch=(text:string)=>{const raw=text.trim();if(!raw){clearFilters();return}const s=raw.toLowerCase();setQuery('');setBrand('');setPrice('');setFuel('');setIntent('');setAiSuv(false);let nextCondition:Condition='all';const notes:string[]=[];if(/occasion|used|seconde main|二手/.test(s)){nextCondition='used';notes.push(lang==='fr'?'Occasion':'二手车')}else if(/neuf|nouveau|new car|新车/.test(s)){nextCondition='new';notes.push(lang==='fr'?'Neuf':'新车')}setCondition(nextCondition);if(/suv|4x4|越野车|运动型多用途/.test(s)){setAiSuv(true);notes.push('SUV')}if(/famille|familial|7 places|七座|7座|家用|家庭/.test(s)){setIntent('family');notes.push(lang==='fr'?'Famille':'家庭')}else if(/hybride|hybrid|phev|hev|混动|省油|économique|economique/.test(s)){setIntent('hybrid');notes.push(lang==='fr'?'Hybride / économique':'混动 / 省油')}else if(/aventure|off.?road|terrain|越野|硬派|烂路/.test(s)){setIntent('adventure');notes.push(lang==='fr'?'Aventure':'越野')}else if(/business|affaires|réception|reception|商务|接待/.test(s)){setIntent('business');notes.push(lang==='fr'?'Business':'商务')}const range=s.match(/(1[0-9]|2[0-9]|3[0-9])\s*[-–~到至]\s*(1[0-9]|2[0-9]|3[0-9])\s*m/);if(range){const a=Number(range[1]),b=Number(range[2]);if(a<=15&&b<=20)setPrice('15to20');else if(a>=20&&b<=25)setPrice('20to25');else if(a>=25&&b<=30)setPrice('25to30');notes.push(`${a}–${b}M`)}else if(/15\s*m?.{0,4}(以内|以下|moins|under)/.test(s)){setPrice('lt15');notes.push('<15M')}else if(/20\s*m|2000\s*万|20\s*million|20\s*millions/.test(s)){setPrice(/suv/.test(s)?'around20suv':'20to25');notes.push(lang==='fr'?'Autour de 20M':'20M左右')}else if(/25\s*m|2500\s*万/.test(s)){setPrice('25to30');notes.push(lang==='fr'?'Autour de 25M':'25M左右')}else if(/30\s*m\+|3000\s*万以上|plus de 30/.test(s)){setPrice('30plus');notes.push('30M+')}const detectedBrand=brands.find(b=>s.includes(b.toLowerCase()));if(detectedBrand){setBrand(detectedBrand);notes.push(detectedBrand)}const detectedModel=allItems.find(i=>i.model&&s.includes(String(i.model).toLowerCase().split('/')[0].slice(0,18)));if(detectedModel){setQuery(detectedModel.model.split('/')[0].slice(0,24));notes.push(detectedModel.model.split('/')[0].slice(0,24))}else if(notes.length===0)setQuery(raw);setAiNote(notes.length?(lang==='fr'?`Compris : ${notes.join(' · ')}`:`已理解：${notes.join(' · ')}`):(lang==='fr'?'Recherche par mot-clé':'按关键词搜索'));window.setTimeout(()=>document.getElementById('ai-advisor')?.scrollIntoView({behavior:'smooth',block:'start'}),120)}
 const startVoice=()=>{const w=window as any;const SR=w.SpeechRecognition||w.webkitSpeechRecognition;if(!SR){setAiNote(lang==='fr'?'La saisie vocale n’est pas prise en charge sur ce navigateur. Vous pouvez continuer en texte.':'当前浏览器暂不支持网页语音识别，可以继续文字输入。');return}const r=new SR();r.lang=lang==='fr'?'fr-FR':'zh-CN';r.interimResults=false;r.maxAlternatives=1;r.onstart=()=>setListening(true);r.onend=()=>setListening(false);r.onerror=()=>{setListening(false);setAiNote(lang==='fr'?'Impossible de reconnaître la voix. Réessayez ou écrivez votre demande.':'没有识别到语音，请重试或直接输入文字。')};r.onresult=(e:any)=>{const t=String(e.results?.[0]?.[0]?.transcript||'').trim();if(t){setAiPrompt(t);runSmartSearch(t)}};r.start()}
 const Cards=({items,compact=false}:{items:MarketItem[];compact?:boolean})=><section className={compact?'market-grid discovery-grid':'market-grid'}>{items.map(item=><article key={item.key} className="market-card"><div className="card-media" onClick={()=>openItem(item)}>{item.image?<img src={item.image}/>:<div className="car-placeholder"><CarFront/></div>}<span className={`availability ${statusClass(item.availability)}`}>{availabilityText(item.availability,lang)}</span>{item.condition&&<span className={`condition-badge ${item.condition}`}>{item.condition==='used'?(lang==='fr'?'Occasion':'二手'):(lang==='fr'?'Neuf':'新车')}</span>}</div><div className="card-copy"><small>{item.brand}</small><h2>{item.title}</h2>{item.subtitle&&<p>{item.subtitle}</p>}<div className="price-line"><span>{x.from}</span><strong>{money(item.price)}</strong></div><div className="mini-specs">{item.inventory?.year&&<span>{item.inventory.year}</span>}{item.condition==='used'&&item.mileage!=null&&<span>{new Intl.NumberFormat('fr-FR').format(item.mileage)} km</span>}{item.transmission&&<span>{item.transmission}</span>}{item.fuel&&<span>{item.fuel}</span>}{item.seats&&<span>{item.seats} {lang==='fr'?'places':'座'}</span>}</div><div className="card-actions"><button onClick={()=>openItem(item)}>{x.detail}</button><button className="primary" onClick={()=>openItem(item,true)}>{item.kind==='inventory'?'WhatsApp':x.reserve}</button></div></div></article>)}</section>
 return <div className="market-v1">
  <header className="market-nav"><div className="market-logo"><span><CarFront/></span><div><strong>GREEN FAST</strong><small>AUTO</small></div></div><div className="market-nav-actions"><a href="#cars">{lang==='fr'?'Véhicules':'选车'}</a><button onClick={()=>setLang(lang==='fr'?'zh':'fr')}>{lang==='fr'?'中文':'FR'}</button><a className="wa" href={`https://wa.me/${COMPANY_WA}`}>WhatsApp</a></div></header>
  {activeBanner?<section className="market-banner" style={{backgroundImage:`linear-gradient(90deg,rgba(8,18,12,.74),rgba(8,18,12,.12)),url(${activeBanner.background_image||''})`}}><div className="banner-copy">{btxt(activeBanner,'badge',lang)&&<span>{btxt(activeBanner,'badge',lang)}</span>}<h1>{btxt(activeBanner,'title',lang)||x.title}</h1><p>{btxt(activeBanner,'subtitle',lang)||x.sub}</p><a href="#cars">{btxt(activeBanner,'cta_label',lang)||x.choose}</a></div>{banners.length>1&&<div className="banner-dots">{banners.map((b,i)=><button key={b.id} className={i===hero?'active':''} onClick={()=>setHero(i)} aria-label={`banner ${i+1}`}/>)}</div>}</section>:<section className="market-banner fallback"><div className="banner-copy"><span>GREEN FAST AUTO · ABIDJAN</span><h1>{x.title}</h1><p>{x.sub}</p></div></section>}
  <section className="market-chooser"><div><div className="ai-search-head"><span><Sparkles/>{x.aiTitle}</span><small>{x.aiHint}</small></div><form className="hero-search ai-search" onSubmit={e=>{e.preventDefault();runSmartSearch(aiPrompt)}}><Search/><input value={aiPrompt} onChange={e=>setAiPrompt(e.target.value)} placeholder={x.search}/><button type="button" className={listening?'voice-btn listening':'voice-btn'} onClick={startVoice} aria-label={lang==='fr'?'Recherche vocale':'语音搜索'}><Mic/></button><button className="ai-submit" type="submit">{lang==='fr'?'Trouver':'帮我选'}</button></form>{aiNote&&<div className="ai-note"><Sparkles/>{aiNote}</div>}<div className="market-condition-tabs"><button className={condition==='all'?'active':''} onClick={()=>setCondition('all')}>{x.allCondition}</button><button className={condition==='new'?'active':''} onClick={()=>setCondition('new')}>{x.newCondition}</button><button className={condition==='used'?'active':''} onClick={()=>setCondition('used')}>{x.usedCondition}</button></div><div className="chooser-filters"><label><select aria-label={lang==='fr'?'Marque':'品牌'} value={brand} onChange={e=>setBrand(e.target.value)}><option value="">{x.all}</option>{brands.map(b=><option key={b} value={b}>{b}</option>)}</select></label><label><select aria-label={x.price} value={price} onChange={e=>setPrice(e.target.value)}><option value="">{x.allPrice}</option><option value="lt15">&lt; 15M</option><option value="15to20">15–20M</option><option value="20to25">20–25M</option><option value="25to30">25–30M</option><option value="30plus">30M+</option><option value="around20suv">{lang==='fr'?'SUV 17–23M':'20M左右SUV'}</option></select></label><label><select aria-label={x.fuel} value={fuel} onChange={e=>setFuel(e.target.value)}><option value="">{x.allFuel}</option><option value="petrol">{lang==='fr'?'Essence':'汽油'}</option><option value="hybrid">{lang==='fr'?'Hybride':'混动'}</option><option value="electric">{lang==='fr'?'Électrique':'纯电'}</option><option value="diesel">Diesel</option></select></label>{hasFilters&&<button className="clear-filters" onClick={clearFilters}>{lang==='fr'?'Réinitialiser':'清除'}</button>}</div></div></section>
  {(aiPrompt||aiNote)&&advisorResults.length>0&&<section id="ai-advisor" className="ai-advisor-section"><div className="ai-advisor-head"><div><Sparkles/><span>{lang==='fr'?'CONSEILLER GREEN FAST':'GREEN FAST 智能顾问'}</span><h2>{lang==='fr'?'Mes 3 recommandations pour vous':'根据你的需求，优先看这 3 台'}</h2><p>{lang==='fr'?'Classées à partir de votre besoin, du prix, de la disponibilité et de l’usage.':'按照你的预算、用途、动力需求和库存状态综合排序。'}</p></div></div><div className="ai-advisor-grid">{advisorResults.map((item,idx)=><article key={item.key} className="ai-advisor-card" onClick={()=>openItem(item)}><div className="ai-rank">#{idx+1}</div><img src={item.image}/><div><small>{item.brand}</small><h3>{item.title}</h3><strong>{money(item.price)}</strong><p><Sparkles/>{advisorReason(item)}</p><button>{lang==='fr'?'Voir pourquoi / détails':'查看推荐理由 / 车型详情'}</button></div></article>)}</div></section>}
  {!hasFilters&&hot.length>0&&<section className="discovery-section"><div className="discovery-head"><div><Flame/><span>{x.hotSub}</span><h2>{x.hot}</h2></div></div><Cards items={hot} compact/></section>}
  {!hasFilters&&arrivals.length>0&&<section className="discovery-section new-section"><div className="discovery-head"><div><Clock3/><span>{x.newSub}</span><h2>{x.newCars}</h2></div></div><Cards items={arrivals} compact/></section>}
  {!hasFilters&&<section className="discovery-section budget-section"><div className="discovery-head"><div><WalletCards/><span>{x.budgetSub}</span><h2>{x.budget}</h2></div></div><div className="budget-grid">{budgetOptions.map(o=><button key={o.value} onClick={()=>applyBudget(o.value)}><strong>{o.label}</strong><span>{o.sub}</span><b>→</b></button>)}</div></section>}
  {!hasFilters&&<section className="discovery-section use-section"><div className="discovery-head"><div><UsersRound/><span>{x.useSub}</span><h2>{x.useTitle}</h2></div></div><div className="use-grid">{useOptions.map(o=>{const Icon=o.icon;return <button key={o.key} onClick={()=>applyIntent(o.key)}><span className="use-icon"><Icon/></span><span><strong>{o.label}</strong><small>{o.sub}</small></span><b>→</b></button>})}</div></section>}
  {!hasFilters&&hybridCars.length>0&&<section className="discovery-section eco-section"><div className="discovery-head"><div><Leaf/><span>{lang==='fr'?'Moins de carburant, plus de choix':'更省油，也更适合日常高频用车'}</span><h2>{lang==='fr'?'Hybrides à découvrir':'混动车型推荐'}</h2></div></div><Cards items={hybridCars} compact/></section>}
  {!hasFilters&&chinaSuv.length>0&&<section className="discovery-section suv-section"><div className="discovery-head"><div><Star/><span>{x.chinaSuvSub}</span><h2>{x.chinaSuv}</h2></div></div><Cards items={chinaSuv} compact/></section>}
  <main id="cars" className="market-main"><div className="market-section-head"><div><span>GREEN FAST SELECT</span><h2>{intent||aiSuv?(lang==='fr'?'Sélection pour vous':'为你筛选'):x.allCars}</h2><p>{x.allCarsSub}</p></div><div className="market-count"><b>{loading?'…':visible.length}</b><span>{lang==='fr'?'modèles disponibles':'款车型可选'}</span></div></div>{loading?<div className="market-loading">Loading…</div>:visible.length===0?<div className="market-empty"><Filter/><p>{x.no}</p><button className="empty-reset" onClick={clearFilters}>{lang==='fr'?'Voir tous les véhicules':'查看全部车型'}</button></div>:<Cards items={visible}/>}</main>
 </div>
}

function InventoryPage({lang,vehicle,back}:{lang:Lang;vehicle:Inventory;back:()=>void}){
 const x=labels[lang],[photo,setPhoto]=useState(0);const gallery=Array.from(new Set([vehicle.marketing_cover_url,...pics(vehicle.photos)].filter(Boolean) as string[]));const availability=invAvailability(vehicle.status);const title=shortTitle(String(vehicle.make||'Green Fast'),String(vehicle.model||''));const wa=`https://wa.me/${COMPANY_WA}?text=${encodeURIComponent(`${lang==='fr'?'Bonjour, je souhaite des informations sur':'你好，我想咨询'} ${title}`)}`
 return <div className="market-v1"><header className="market-nav"><button className="market-back" onClick={back}><ChevronLeft/>{x.back}</button><a className="nav-reserve inventory-wa" href={wa}>WhatsApp</a></header><main className="vehicle-page"><section className="vehicle-gallery-v1"><div className="vehicle-main-photo">{gallery[photo]?<img src={gallery[photo]}/>:<CarFront/>}</div>{gallery.length>1&&<div className="vehicle-thumbs">{gallery.map((p,i)=><button className={photo===i?'active':''} key={p} onClick={()=>setPhoto(i)}><img src={p}/></button>)}</div>}</section><aside className="vehicle-buybox"><div className="inventory-badges"><span className={`availability ${statusClass(availability)}`}>{availabilityText(availability,lang)}</span>{vehicle.vehicle_condition&&<span className={`detail-condition ${vehicle.vehicle_condition}`}>{vehicle.vehicle_condition==='used'?(lang==='fr'?'Occasion':'二手车'):(lang==='fr'?'Neuf':'新车')}</span>}</div><small>{vehicle.make||'GREEN FAST AUTO'}</small><h1>{title}</h1>{vehicle.trim&&<p>{vehicle.trim}</p>}<div className="buy-price"><span>{x.from}</span><strong>{money(vehicle.price_xof)}</strong></div><div className="inventory-detail-grid">{vehicle.year&&<div><span>{lang==='fr'?'Année':'年份'}</span><b>{vehicle.year}</b></div>}{vehicle.mileage!=null&&<div><span>{lang==='fr'?'Kilométrage':'里程'}</span><b>{new Intl.NumberFormat(lang==='fr'?'fr-FR':'zh-CN').format(vehicle.mileage)} km</b></div>}{vehicle.fuel_type&&<div><span>{lang==='fr'?'Énergie':'动力'}</span><b>{vehicle.fuel_type}</b></div>}{vehicle.transmission&&<div><span>{lang==='fr'?'Boîte':'变速箱'}</span><b>{vehicle.transmission}</b></div>}{vehicle.seats&&<div><span>{lang==='fr'?'Places':'座位'}</span><b>{vehicle.seats}</b></div>}{vehicle.body_type&&<div><span>{lang==='fr'?'Type':'车型'}</span><b>{vehicle.body_type}</b></div>}</div><a className="whatsapp-big inventory-primary" href={wa}>{lang==='fr'?'Demander disponibilité et prix final':'WhatsApp 咨询库存与最终价格'}</a><p className="detail-footnote">{lang==='fr'?'Les photos ouvrent maintenant cette fiche véhicule. WhatsApp est réservé à l’étape de contact.':'现在点击车辆图片或“查看车型”会先进入详情页，只有咨询按钮才会进入 WhatsApp。'}</p></aside></main></div>
}

function VehiclePage({lang,catalog,variants,inventory,back,reserve,setReserve}:{lang:Lang;catalog:Catalog;variants:Variant[];inventory:Inventory[];back:()=>void;reserve:boolean;setReserve:(v:boolean)=>void}){
 const x=labels[lang],[variantId,setVariantId]=useState(variants[0]?.id||''),[photo,setPhoto]=useState(0);const variant=variants.find(v=>v.id===variantId)||variants[0];const gallery=Array.from(new Set([catalog.cover_url,...pics(catalog.photos),...inventory.flatMap(i=>[i.marketing_cover_url,...pics(i.photos)])].filter(Boolean) as string[]));const stock=inventory.filter(i=>i.status==='in_stock').length
 return <div className="market-v1"><header className="market-nav"><button className="market-back" onClick={back}><ChevronLeft/>{x.back}</button><button onClick={()=>setReserve(true)} className="nav-reserve">{x.reserve}</button></header><main className="vehicle-page"><section className="vehicle-gallery-v1"><div className="vehicle-main-photo">{gallery[photo]?<img src={gallery[photo]}/>:<CarFront/>}</div>{gallery.length>1&&<div className="vehicle-thumbs">{gallery.map((p,i)=><button className={photo===i?'active':''} key={p} onClick={()=>setPhoto(i)}><img src={p}/></button>)}</div>}</section><aside className="vehicle-buybox"><span className={`availability ${stock?'stock':catalog.availability==='arrive_bientot'?'soon':'order'}`}>{stock?x.stock:catalog.availability==='arrive_bientot'?x.soon:x.order}</span><small>{catalog.brand}</small><h1>{lang==='fr'?(catalog.title_fr||`${catalog.brand} ${catalog.model}`):(catalog.title_zh||`${catalog.brand} ${catalog.model}`)}</h1><p>{lang==='fr'?catalog.subtitle_fr:catalog.subtitle_zh}</p><div className="buy-price"><span>{x.from}</span><strong>{money(variant?.price_xof||catalog.price_from_xof)}</strong></div>{variants.length>0&&<div className="variant-picker"><label>{x.config}</label>{variants.map(v=><button className={variantId===v.id?'active':''} key={v.id} onClick={()=>setVariantId(v.id)}><span>{lang==='fr'?v.name_fr:(v.name_zh||v.name_fr)}</span><b>{money(v.price_xof)}</b></button>)}</div>}<div className="delivery-box"><div><span>{x.delivery}</span><b>{catalog.lead_time_min_days||30}–{catalog.lead_time_max_days||45} {x.days}</b></div><div><span>{x.deposit}</span><b>{money(variant?.deposit_xof||200000)}</b></div></div><button className="reserve-big" onClick={()=>setReserve(true)}>{x.reserve}</button><a className="whatsapp-big" href={`https://wa.me/${COMPANY_WA}?text=${encodeURIComponent(`${lang==='fr'?'Bonjour, je souhaite des informations sur':'你好，我想咨询'} ${catalog.brand} ${catalog.model}`)}`}>WhatsApp</a></aside></main>{reserve&&<ReservationModal lang={lang} catalog={catalog} variant={variant||null} close={()=>setReserve(false)}/>}</div>
}

function ReservationModal({lang,catalog,variant,close}:{lang:Lang;catalog:Catalog;variant:Variant|null;close:()=>void}){const x=labels[lang],[form,setForm]=useState({name:'',phone:'',color:'',notes:''}),[busy,setBusy]=useState(false),[done,setDone]=useState(false),[ref,setRef]=useState(''),[error,setError]=useState('');const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!supabase)return;setBusy(true);setError('');const{data,error}=await supabase.rpc('create_vehicle_catalog_reservation',{p_catalog_id:catalog.id,p_variant_id:variant?.id||null,p_customer_name:form.name,p_phone:form.phone,p_whatsapp:form.phone,p_preferred_color:form.color||null,p_notes:form.notes||null});setBusy(false);if(error)setError(error.message);else{setRef(String(data||''));setDone(true)}};const wa=`https://wa.me/${COMPANY_WA}?text=${encodeURIComponent(`${lang==='fr'?'Bonjour, je viens de réserver':'你好，我刚刚预订了'} ${catalog.brand} ${catalog.model}${variant?` · ${lang==='fr'?variant.name_fr:(variant.name_zh||variant.name_fr)}`:''}${ref?` · Ref ${ref.slice(0,8)}`:''}`)}`;return <div className="reservation-layer"><div className="reservation-modal"><button className="reservation-close" onClick={close}><X/></button>{done?<div className="reservation-done"><div>✓</div><h2>{x.sent}</h2><p>{x.sentSub}</p><strong>{catalog.brand} {catalog.model}</strong>{variant&&<span>{lang==='fr'?variant.name_fr:(variant.name_zh||variant.name_fr)} · {money(variant.price_xof)}</span>}<a href={wa}>{x.whatsapp}</a></div>:<form onSubmit={submit}><small>GREEN FAST AUTO · RÉSERVATION</small><h2>{catalog.brand} {catalog.model}</h2>{variant&&<p>{lang==='fr'?variant.name_fr:(variant.name_zh||variant.name_fr)} · {money(variant.price_xof)}</p>}<label>{x.name}<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>{x.phone}<input required inputMode="tel" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>{x.color}<input value={form.color} onChange={e=>setForm({...form,color:e.target.value})}/></label><label>{x.notes}<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label>{error&&<div className="reserve-error">{error}</div>}<button disabled={busy}>{busy?'…':x.submit}</button></form>}</div></div>}
