import {useEffect,useMemo,useState} from 'react'
import {CarFront,ChevronLeft,Filter,Search,SlidersHorizontal,X} from 'lucide-react'
import {supabase} from '../lib/supabase'
import './MarketplaceV1.css'

type Lang='fr'|'zh'
type Catalog={id:string;slug:string;brand:string;model:string;title_fr:string|null;title_zh:string|null;subtitle_fr:string|null;subtitle_zh:string|null;body_type:string|null;fuel_type:string|null;transmission:string|null;seats:number|null;cover_url:string|null;photos:string|null;price_from_xof:number|null;price_to_xof:number|null;availability:'en_stock'|'arrive_bientot'|'sur_commande';lead_time_min_days:number|null;lead_time_max_days:number|null;featured:boolean;sort_order:number}
type Variant={id:string;catalog_id:string;name_fr:string;name_zh:string|null;transmission:string|null;fuel_type:string|null;drivetrain:string|null;price_xof:number|null;deposit_xof:number|null;feature_summary:string|null;specs:Record<string,unknown>|null;sort_order:number}
type Inventory={id:string;make:string|null;model:string|null;trim:string|null;status:string|null;price_xof:number|null;photos:string|null;marketing_cover_url?:string|null}

const COMPANY_WA='2250700737118'
const money=(n:number|null|undefined)=>n?new Intl.NumberFormat('fr-FR').format(Number(n))+' FCFA':'Prix sur demande'
const pics=(v:unknown)=>String(v||'').split(/\n|,/).map(x=>x.trim()).filter(x=>/^https?:\/\//.test(x))
const labels={
 fr:{title:'Trouvez votre prochaine voiture',sub:'Découvrez toute la sélection Green Fast Auto : en stock, en arrivage et sur commande.',search:'Rechercher une marque ou un modèle…',all:'Toutes les marques',price:'Prix',fuel:'Énergie',allPrice:'Tous les prix',allFuel:'Toutes',detail:'Voir le véhicule',reserve:'Réserver',from:'À partir de',stock:'En stock',soon:'Arrive bientôt',order:'Sur commande',delivery:'Délai estimé',days:'jours',config:'Choisissez une version',name:'Nom complet',phone:'Téléphone / WhatsApp',color:'Couleur souhaitée',notes:'Message / préférence',submit:'Envoyer la réservation',sent:'Réservation enregistrée',sentSub:'Notre équipe va confirmer le prix, la disponibilité et le délai.',whatsapp:'Continuer sur WhatsApp',back:'Retour aux véhicules',no:'Aucun véhicule ne correspond à vos filtres.',deposit:'Acompte indicatif',allCars:'Tous les véhicules',allCarsSub:'Parcourez toute notre sélection. Utilisez la recherche ou les filtres pour affiner.',quick:'Disponibilité'},
 zh:{title:'选你的下一辆车',sub:'Green Fast Auto 全部车型都在这里：现车、在途、可订，一站式查看和预订。',search:'搜索品牌 / 车型…',all:'全部品牌',price:'价格',fuel:'动力',allPrice:'全部价格',allFuel:'全部动力',detail:'查看车型',reserve:'在线预订',from:'起售价',stock:'现车',soon:'即将到港',order:'可订',delivery:'预计交付',days:'天',config:'选择配置',name:'姓名',phone:'电话 / WhatsApp',color:'意向颜色',notes:'备注 / 配置需求',submit:'提交预订',sent:'预订已提交',sentSub:'销售会确认最终价格、库存和交期。',whatsapp:'继续 WhatsApp 沟通',back:'返回选车',no:'没有符合当前筛选条件的车型。',deposit:'参考订金',allCars:'全部车型',allCarsSub:'首页先展示完整车型，再通过搜索和筛选快速找到目标车型。',quick:'车辆状态'}
}

function availabilityText(v:Catalog,stockCount:number,lang:Lang){const x=labels[lang];if(stockCount>0)return x.stock;if(v.availability==='arrive_bientot')return x.soon;return x.order}
function statusClass(v:Catalog,stockCount:number){if(stockCount>0)return'stock';if(v.availability==='arrive_bientot')return'soon';return'order'}

export default function MarketplaceV1(){
 const[lang,setLang]=useState<Lang>('fr'),[catalog,setCatalog]=useState<Catalog[]>([]),[variants,setVariants]=useState<Variant[]>([]),[inventory,setInventory]=useState<Inventory[]>([]),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[brand,setBrand]=useState(''),[price,setPrice]=useState(''),[fuel,setFuel]=useState(''),[selected,setSelected]=useState<Catalog|null>(null),[reserve,setReserve]=useState(false)
 const x=labels[lang]
 useEffect(()=>{void(async()=>{if(!supabase)return;setLoading(true);const[{data:c},{data:v},{data:i}]=await Promise.all([supabase.from('vehicle_catalog').select('*').eq('published',true).order('sort_order'),supabase.from('vehicle_catalog_variants').select('*').eq('active',true).order('sort_order'),supabase.from('public_vehicle_catalog').select('id,make,model,trim,status,price_xof,photos,marketing_cover_url')]);setCatalog((c||[])as Catalog[]);setVariants((v||[])as Variant[]);setInventory((i||[])as Inventory[]);setLoading(false)})()},[])
 const brands=useMemo(()=>Array.from(new Set(catalog.map(c=>c.brand))).sort(),[catalog])
 const stockFor=(c:Catalog)=>inventory.filter(i=>`${i.make||''} ${i.model||''}`.toLowerCase().includes(c.model.toLowerCase())).filter(i=>['in_stock','reserved','in_transit','port','customs','ordered'].includes(String(i.status)))
 const visible=useMemo(()=>catalog.filter(c=>{const q=query.trim().toLowerCase();if(q&&!`${c.brand} ${c.model} ${c.title_fr||''} ${c.title_zh||''}`.toLowerCase().includes(q))return false;if(brand&&c.brand!==brand)return false;const p=Number(c.price_from_xof||0);if(price==='lt15'&&p>=15000000)return false;if(price==='15to20'&&(p<15000000||p>=20000000))return false;if(price==='20to25'&&(p<20000000||p>=25000000))return false;if(price==='25to30'&&(p<25000000||p>=30000000))return false;if(price==='30plus'&&p<30000000)return false;if(fuel&&c.fuel_type!==fuel)return false;return true}),[catalog,query,brand,price,fuel])
 const availabilityCounts=useMemo(()=>catalog.reduce((acc,c)=>{const count=stockFor(c).length;if(count>0)acc.stock++;else if(c.availability==='arrive_bientot')acc.soon++;else acc.order++;return acc},{stock:0,soon:0,order:0}),[catalog,inventory])
 if(selected)return <VehiclePage lang={lang} catalog={selected} variants={variants.filter(v=>v.catalog_id===selected.id)} inventory={stockFor(selected)} back={()=>{setSelected(null);setReserve(false)}} reserve={reserve} setReserve={setReserve}/>
 const hasFilters=Boolean(query||brand||price||fuel)
 return <div className="market-v1">
  <header className="market-nav"><div className="market-logo"><span><CarFront/></span><div><strong>GREEN FAST</strong><small>AUTO</small></div></div><div className="market-nav-actions"><a href="#cars">{lang==='fr'?'Véhicules':'选车'}</a><button onClick={()=>setLang(lang==='fr'?'zh':'fr')}>{lang==='fr'?'中文':'FR'}</button><a className="wa" href={`https://wa.me/${COMPANY_WA}`}>WhatsApp</a></div></header>
  <section className="market-hero"><div><span>GREEN FAST AUTO · ABIDJAN</span><h1>{x.title}</h1><p>{x.sub}</p><div className="hero-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={x.search}/></div></div></section>
  <section className="market-status-strip"><div><small>{x.quick}</small><div className="status-summary"><button><b>{catalog.length}</b><span>{lang==='fr'?'Tous':'全部车型'}</span></button><button><b>{availabilityCounts.stock}</b><span>{x.stock}</span></button><button><b>{availabilityCounts.soon}</b><span>{x.soon}</span></button><button><b>{availabilityCounts.order}</b><span>{x.order}</span></button></div></div></section>
  <main id="cars" className="market-main">
   <div className="market-section-head"><div><span>GREEN FAST SELECT</span><h2>{x.allCars}</h2><p>{x.allCarsSub}</p></div><div className="market-count"><b>{loading?'…':visible.length}</b><span>{lang==='fr'?'modèles disponibles':'款车型可选'}</span></div></div>
   <section className="market-filters compact"><div className="filter-title"><SlidersHorizontal/><b>{lang==='fr'?'Rechercher & filtrer':'搜索与筛选'}</b></div><div className="filter-row filter-row-4"><label><span>{lang==='fr'?'Marque':'品牌'}</span><select value={brand} onChange={e=>setBrand(e.target.value)}><option value="">{x.all}</option>{brands.map(b=><option key={b} value={b}>{b}</option>)}</select></label><label><span>{x.price}</span><select value={price} onChange={e=>setPrice(e.target.value)}><option value="">{x.allPrice}</option><option value="lt15">&lt; 15M</option><option value="15to20">15–20M</option><option value="20to25">20–25M</option><option value="25to30">25–30M</option><option value="30plus">30M+</option></select></label><label><span>{x.fuel}</span><select value={fuel} onChange={e=>setFuel(e.target.value)}><option value="">{x.allFuel}</option><option value="petrol">{lang==='fr'?'Essence':'汽油'}</option><option value="hybrid">{lang==='fr'?'Hybride':'混动'}</option><option value="electric">{lang==='fr'?'Électrique':'纯电'}</option><option value="diesel">Diesel</option></select></label>{hasFilters&&<button className="clear-filters" onClick={()=>{setQuery('');setBrand('');setPrice('');setFuel('')}}>{lang==='fr'?'Réinitialiser':'清除筛选'}</button>}</div></section>
   {loading?<div className="market-loading">Loading…</div>:visible.length===0?<div className="market-empty"><Filter/><p>{x.no}</p></div>:<section className="market-grid">{visible.map(c=>{const inv=stockFor(c),cover=c.cover_url||pics(c.photos)[0]||inv.map(i=>i.marketing_cover_url||pics(i.photos)[0]).find(Boolean)||'';return <article key={c.id} className="market-card"><div className="card-media" onClick={()=>setSelected(c)}>{cover?<img src={cover}/>:<div className="car-placeholder"><CarFront/></div>}<span className={`availability ${statusClass(c,inv.length)}`}>{availabilityText(c,inv.length,lang)}</span></div><div className="card-copy"><small>{c.brand}</small><h2>{lang==='fr'?(c.title_fr||`${c.brand} ${c.model}`):(c.title_zh||`${c.brand} ${c.model}`)}</h2><p>{lang==='fr'?c.subtitle_fr:c.subtitle_zh}</p><div className="price-line"><span>{x.from}</span><strong>{money(c.price_from_xof)}</strong></div><div className="mini-specs"><span>{c.transmission||'—'}</span><span>{c.fuel_type||'—'}</span><span>{c.seats?`${c.seats} ${lang==='fr'?'places':'座'}`:'SUV'}</span></div><div className="card-actions"><button onClick={()=>setSelected(c)}>{x.detail}</button><button className="primary" onClick={()=>{setSelected(c);setReserve(true)}}>{x.reserve}</button></div></div></article>})}</section>}
  </main>
 </div>
}

function VehiclePage({lang,catalog,variants,inventory,back,reserve,setReserve}:{lang:Lang;catalog:Catalog;variants:Variant[];inventory:Inventory[];back:()=>void;reserve:boolean;setReserve:(v:boolean)=>void}){
 const x=labels[lang],[variantId,setVariantId]=useState(variants[0]?.id||''),[photo,setPhoto]=useState(0);const variant=variants.find(v=>v.id===variantId)||variants[0];const gallery=Array.from(new Set([catalog.cover_url,...pics(catalog.photos),...inventory.flatMap(i=>[i.marketing_cover_url,...pics(i.photos)])].filter(Boolean) as string[]));const stock=inventory.filter(i=>i.status==='in_stock').length
 return <div className="market-v1"><header className="market-nav"><button className="market-back" onClick={back}><ChevronLeft/>{x.back}</button><button onClick={()=>setReserve(true)} className="nav-reserve">{x.reserve}</button></header><main className="vehicle-page"><section className="vehicle-gallery-v1"><div className="vehicle-main-photo">{gallery[photo]?<img src={gallery[photo]}/>:<CarFront/>}</div>{gallery.length>1&&<div className="vehicle-thumbs">{gallery.map((p,i)=><button className={photo===i?'active':''} key={p} onClick={()=>setPhoto(i)}><img src={p}/></button>)}</div>}</section><aside className="vehicle-buybox"><span className={`availability ${stock?'stock':catalog.availability==='arrive_bientot'?'soon':'order'}`}>{availabilityText(catalog,inventory.length,lang)}</span><small>{catalog.brand}</small><h1>{lang==='fr'?(catalog.title_fr||`${catalog.brand} ${catalog.model}`):(catalog.title_zh||`${catalog.brand} ${catalog.model}`)}</h1><p>{lang==='fr'?catalog.subtitle_fr:catalog.subtitle_zh}</p><div className="buy-price"><span>{x.from}</span><strong>{money(variant?.price_xof||catalog.price_from_xof)}</strong></div>{variants.length>0&&<div className="variant-picker"><label>{x.config}</label>{variants.map(v=><button className={variantId===v.id?'active':''} key={v.id} onClick={()=>setVariantId(v.id)}><span>{lang==='fr'?v.name_fr:(v.name_zh||v.name_fr)}</span><b>{money(v.price_xof)}</b></button>)}</div>}<div className="delivery-box"><div><span>{x.delivery}</span><b>{catalog.lead_time_min_days||30}–{catalog.lead_time_max_days||45} {x.days}</b></div><div><span>{x.deposit}</span><b>{money(variant?.deposit_xof||200000)}</b></div></div><button className="reserve-big" onClick={()=>setReserve(true)}>{x.reserve}</button><a className="whatsapp-big" href={`https://wa.me/${COMPANY_WA}?text=${encodeURIComponent(`${lang==='fr'?'Bonjour, je souhaite des informations sur':'你好，我想咨询'} ${catalog.brand} ${catalog.model}`)}`}>WhatsApp</a></aside></main>{reserve&&<ReservationModal lang={lang} catalog={catalog} variant={variant||null} close={()=>setReserve(false)}/>}</div>
}

function ReservationModal({lang,catalog,variant,close}:{lang:Lang;catalog:Catalog;variant:Variant|null;close:()=>void}){const x=labels[lang],[form,setForm]=useState({name:'',phone:'',color:'',notes:''}),[busy,setBusy]=useState(false),[done,setDone]=useState(false),[ref,setRef]=useState(''),[error,setError]=useState('');const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!supabase)return;setBusy(true);setError('');const{data,error}=await supabase.rpc('create_vehicle_catalog_reservation',{p_catalog_id:catalog.id,p_variant_id:variant?.id||null,p_customer_name:form.name,p_phone:form.phone,p_whatsapp:form.phone,p_preferred_color:form.color||null,p_notes:form.notes||null});setBusy(false);if(error)setError(error.message);else{setRef(String(data||''));setDone(true)}};const wa=`https://wa.me/${COMPANY_WA}?text=${encodeURIComponent(`${lang==='fr'?'Bonjour, je viens de réserver':'你好，我刚刚预订了'} ${catalog.brand} ${catalog.model}${variant?` · ${lang==='fr'?variant.name_fr:(variant.name_zh||variant.name_fr)}`:''}${ref?` · Ref ${ref.slice(0,8)}`:''}`)}`;return <div className="reservation-layer"><div className="reservation-modal"><button className="reservation-close" onClick={close}><X/></button>{done?<div className="reservation-done"><div>✓</div><h2>{x.sent}</h2><p>{x.sentSub}</p><strong>{catalog.brand} {catalog.model}</strong>{variant&&<span>{lang==='fr'?variant.name_fr:(variant.name_zh||variant.name_fr)} · {money(variant.price_xof)}</span>}<a href={wa}>{x.whatsapp}</a></div>:<form onSubmit={submit}><small>GREEN FAST AUTO · RÉSERVATION</small><h2>{catalog.brand} {catalog.model}</h2>{variant&&<p>{lang==='fr'?variant.name_fr:(variant.name_zh||variant.name_fr)} · {money(variant.price_xof)}</p>}<label>{x.name}<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>{x.phone}<input required inputMode="tel" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>{x.color}<input value={form.color} onChange={e=>setForm({...form,color:e.target.value})}/></label><label>{x.notes}<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label>{error&&<div className="reserve-error">{error}</div>}<button disabled={busy}>{busy?'…':x.submit}</button></form>}</div></div>}
