import { useEffect, useMemo, useState } from 'react'
import { Activity, ArrowLeft, CircleDollarSign, Clock3, MessageCircle, Radio, RefreshCw, Target, Timer, Users, X, Zap } from 'lucide-react'
import type { Lang } from '../lib/modules'
import { getLiveSessionDetail, getMyLiveHistory, type MyLiveSessionRow, type SessionDetail } from '../lib/liveSessionDetail'
import '../my-live-history.css'

type Props={lang:Lang;userId:string;onOpenCrm?:()=>void}

export default function MyLiveHistory({lang,userId,onOpenCrm}:Props){
  const zh=lang==='zh'
  const [rows,setRows]=useState<MyLiveSessionRow[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('')
  const [selected,setSelected]=useState<string|null>(null),[detail,setDetail]=useState<SessionDetail|null>(null),[detailLoading,setDetailLoading]=useState(false)
  const load=async()=>{setLoading(true);setError('');try{setRows(await getMyLiveHistory(userId))}catch(e:any){setError(e?.message||String(e))}finally{setLoading(false)}}
  useEffect(()=>{void load()},[userId])
  useEffect(()=>{if(!selected){setDetail(null);return}setDetailLoading(true);void getLiveSessionDetail(selected).then(setDetail).catch(e=>setError(String(e?.message||e))).finally(()=>setDetailLoading(false))},[selected])
  const total=useMemo(()=>rows.reduce((a,r)=>({sessions:a.sessions+1,leads:a.leads+r.leads,sales:a.sales+r.sales,revenue:a.revenue+r.revenue,avgDaysTotal:a.avgDaysTotal+(r.avgDaysToSale||0),avgDaysCount:a.avgDaysCount+(r.avgDaysToSale===null?0:1)}),{sessions:0,leads:0,sales:0,revenue:0,avgDaysTotal:0,avgDaysCount:0}),[rows])
  const avgDays=total.avgDaysCount?Math.round(total.avgDaysTotal/total.avgDaysCount*10)/10:null
  const money=(n:number)=>n?`${Math.round(n/100000)/10} M CFA`:'0'
  const date=(s:string|null)=>s?new Date(s).toLocaleString(zh?'zh-CN':'fr-FR',{month:'short',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'—'
  return <main className="mlh-page">
    <section className="mlh-hero"><div><span><Radio size={14}/> LIVE SALES AI • MY HISTORY V0.4.3</span><h1>{zh?'我的直播历史':'Mon historique LIVE'}</h1><p>{zh?'查看每场直播从实时表现到30/60/90天后成交的完整结果。':'Suivez chaque LIVE, du signal temps réel jusqu’aux ventes à 30/60/90 jours.'}</p></div><button onClick={()=>void load()}><RefreshCw size={16}/>{zh?'刷新':'Actualiser'}</button></section>
    {error&&<div className="mlh-error">{error}</div>}
    <section className="mlh-kpis">{[[zh?'直播场次':'Sessions',total.sessions,Radio],[zh?'累计线索':'Leads',total.leads,Target],[zh?'累计成交':'Ventes',total.sales,CircleDollarSign],[zh?'归因成交额':'CA attribué',money(total.revenue),CircleDollarSign],[zh?'平均成交周期':'Cycle moyen',avgDays===null?'—':`${avgDays}j`,Timer]].map(([n,v,Icon]:any)=><div key={n}><Icon size={18}/><small>{n}</small><strong>{v}</strong></div>)}</section>
    <section className="mlh-table-wrap"><table><thead><tr><th>{zh?'时间':'Date'}</th><th>{zh?'状态':'Statut'}</th><th>{zh?'峰值在线':'Pic'}</th><th>LIVE SCORE</th><th>Leads</th><th>RDV</th><th>{zh?'到店':'Visites'}</th><th>{zh?'试驾':'Essais'}</th><th>{zh?'成交':'Ventes'}</th><th>0–30j</th><th>0–60j</th><th>0–90j</th><th>{zh?'晚成交':'Tardif'}</th><th>{zh?'成交额':'CA'}</th><th></th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b>{date(r.startedAt)}</b><small>{r.accountName||'TikTok'}</small></td><td><span className={r.status==='live'?'mlh-live':'mlh-ended'}>{r.status==='live'?(zh?'直播中':'LIVE'):(zh?'已结束':'TERMINÉ')}</span></td><td>{r.peak}</td><td><b>{r.liveScore||'—'}</b></td><td>{r.leads}</td><td>{r.appointments}</td><td>{r.visits}</td><td>{r.testDrives}</td><td><b>{r.sales}</b></td><td>{r.sold30}</td><td>{r.sold60}</td><td>{r.sold90}</td><td>{r.late}</td><td><b>{money(r.revenue)}</b></td><td><button className="mlh-open" onClick={()=>setSelected(r.id)}>{zh?'详情':'Détails'}</button></td></tr>)}</tbody></table>{!loading&&!rows.length&&<div className="mlh-empty">{zh?'还没有直播历史':'Aucun historique LIVE pour le moment'}</div>}{loading&&<div className="mlh-empty">{zh?'正在加载…':'Chargement…'}</div>}</section>
    {selected&&<div className="mlh-modal"><div className="mlh-backdrop" onClick={()=>setSelected(null)}/><section className="mlh-detail"><header><div><button onClick={()=>setSelected(null)}><ArrowLeft size={16}/></button><div><small>LIVE SESSION</small><h2>{detail?date(detail.session.startedAt):(zh?'加载中…':'Chargement…')}</h2></div></div><button onClick={()=>setSelected(null)}><X size={18}/></button></header>{detailLoading||!detail?<div className="mlh-detail-loading">{zh?'正在读取单场直播详情…':'Chargement du détail de la session…'}</div>:<>
      <div className="mlh-session-kpis">{[[zh?'峰值在线':'Pic',detail.session.peak,Users],['LIVE SCORE',detail.session.liveScore,Activity],[zh?'线索':'Leads',detail.session.leads,Target],[zh?'成交':'Ventes',detail.session.sales,CircleDollarSign],[zh?'成交额':'CA',money(detail.session.revenue),CircleDollarSign],[zh?'平均成交周期':'Cycle moyen',detail.session.avgDaysToSale===null?'—':`${detail.session.avgDaysToSale}j`,Clock3]].map(([n,v,Icon]:any)=><div key={n}><Icon size={17}/><small>{n}</small><strong>{v}</strong></div>)}</div>
      <div className="mlh-lag"><b>{zh?'延迟转化':'Conversion différée'}</b><span>0–30j <strong>{detail.session.sold30}</strong></span><span>0–60j <strong>{detail.session.sold60}</strong></span><span>0–90j <strong>{detail.session.sold90}</strong></span><span>{zh?'90天后':'Après 90j'} <strong>{detail.session.late}</strong></span></div>
      <section className="mlh-section"><header><div><Zap size={16}/><b>{zh?'AI Director动作':'Actions AI Director'}</b></div><span>{detail.actions.length}</span></header>{detail.actions.length?<div className="mlh-actions-list">{detail.actions.map(a=><article key={a.id}><div><small>{a.priority}</small><b>{a.actionType.split('_').join(' ')}</b><p>{zh?(a.scriptZh||a.scriptFr):(a.scriptFr||a.scriptZh)}</p></div><div className="mlh-deltas"><span>LIVE {a.liveScoreDelta>=0?'+':''}{a.liveScoreDelta}</span><span>Retention {a.retentionDelta>=0?'+':''}{a.retentionDelta}</span><span>Interaction {a.interactionDelta>=0?'+':''}{a.interactionDelta}</span><span>Leads {a.leadsDelta>=0?'+':''}{a.leadsDelta}</span></div></article>)}</div>:<p className="mlh-muted">{zh?'这场直播没有记录AI动作':'Aucune action AI Director enregistrée.'}</p>}</section>
      <section className="mlh-section"><header><div><MessageCircle size={16}/><b>{zh?'评论与意向识别':'Commentaires & intention'}</b></div><span>{detail.comments.length}</span></header>{detail.comments.length?<div className="mlh-comments-list">{detail.comments.map(c=><article key={c.id}><div><b>{c.user||'TikTok user'}</b><p>{c.text}</p><small>{c.intentTags.join(' · ')||'GENERAL'}</small></div><div><strong>{c.intentScore}</strong><span className={c.intentBand==='A'?'hot':''}>{c.intentBand||'C'}</span>{c.routed&&<em>CRM</em>}</div></article>)}</div>:<p className="mlh-muted">{zh?'暂无评论记录':'Aucun commentaire enregistré.'}</p>}</section>
      <section className="mlh-section"><header><div><Target size={16}/><b>{zh?'CRM后续与成交':'CRM → résultat commercial'}</b></div><button className="mlh-crm" onClick={onOpenCrm}>{zh?'打开CRM':'Ouvrir CRM'}</button></header>{detail.leads.length?<div className="mlh-leads-list">{detail.leads.map(l=><article key={l.id}><div><b>{l.user||'Lead TikTok'}</b><small>{l.model||'—'} · {l.band||'C'} · {l.score}/100</small></div><div className="mlh-stage"><span>{l.status}</span>{l.conversionDays!==null&&<small>{l.conversionDays}j</small>}</div><strong>{l.wonAt?money(l.salePrice):'—'}</strong></article>)}</div>:<p className="mlh-muted">{zh?'这场直播还没有CRM线索':'Aucun lead CRM pour cette session.'}</p>}</section>
    </>}</section></div>}
  </main>
}
