import {useEffect,useMemo,useState} from 'react'
import {RefreshCw,Search} from 'lucide-react'
import {supabase} from '../lib/supabase'
import type {Lang} from '../lib/modules'
import './TikTokLeadRadar.css'

type Lead={id:string;username:string;display_name:string|null;original_text:string;intent_score:number;first_seen_at:string;assigned_at:string|null;assigned_to:string|null;assignment_target_role:string|null;status:string}
type Person={id:string;full_name:string|null;role:string}
export default function OwnerRadarAssignmentQueue({lang}:{lang:Lang}){
  const t=(fr:string,zh:string)=>lang==='fr'?fr:zh
  const[leads,setLeads]=useState<Lead[]>([]),[people,setPeople]=useState<Person[]>([]),[q,setQ]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState<string[]>([]),[bulkTarget,setBulkTarget]=useState('')
  const load=async()=>{if(!supabase)return;const[{data:l},{data:p}]=await Promise.all([supabase.from('social_leads').select('id,username,display_name,original_text,intent_score,first_seen_at,assigned_at,assigned_to,assignment_target_role,status').not('status','in','(converted,invalid)').order('first_seen_at',{ascending:false}).limit(100),supabase.from('profiles').select('id,full_name,role').in('role',['manager','sales']).eq('active',true).order('role').order('full_name')]);setLeads((l||[]) as Lead[]);setPeople((p||[]) as Person[])}
  useEffect(()=>{void load()},[])
  const names=useMemo(()=>new Map(people.map(x=>[x.id,x])),[people])
  const visible=leads.filter(x=>!q||`${x.username} ${x.display_name||''} ${x.original_text}`.toLowerCase().includes(q.toLowerCase()))
  const visibleIds=visible.map(x=>x.id),allVisible=visibleIds.length>0&&visibleIds.every(id=>selected.includes(id))
  const toggle=(id:string)=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id])
  const toggleAll=()=>setSelected(s=>allVisible?s.filter(id=>!visibleIds.includes(id)):Array.from(new Set([...s,...visibleIds])))
  const assignOne=async(id:string,target:string)=>{if(!supabase||!target)return;setBusy(true);await supabase.rpc('gfauto_assign_social_lead',{p_lead_id:id,p_target_id:target});setBusy(false);await load()}
  const bulkAssign=async()=>{if(!supabase||!bulkTarget||selected.length===0)return;setBusy(true);const ids=selected.slice(0,100);await supabase.rpc('gfauto_bulk_assign_social_leads',{p_lead_ids:ids,p_target_id:bulkTarget});setSelected([]);setBulkTarget('');setBusy(false);await load()}
  return <section className="wl-panel"><div className="wl-head"><div><span className="eyebrow">OWNER · ASSIGNMENT V0.6.8</span><h2>{t('Distribution des prospects Radar','Radar潜客分配')}</h2><p>{t('Sélectionnez plusieurs prospects ici et attribuez-les en une fois à un manager ou à un vendeur.','无需进入详情页；可在当前页面批量勾选潜客，一次分配给经理或销售。')}</p></div><button className="lr-refresh" onClick={()=>void load()}><RefreshCw size={16}/>{t('Actualiser','刷新')}</button></div><div className="lr-toolbar"><div className="lr-search wl-search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={t('Rechercher un prospect','搜索潜客')}/></div><div style={{display:'flex',gap:8,alignItems:'center',flexWrap:'wrap'}}><b>{t('Sélectionnés','已选择')} {selected.length}</b><select value={bulkTarget} onChange={e=>setBulkTarget(e.target.value)}><option value="">{t('Choisir manager / vendeur','选择经理 / 销售')}</option><optgroup label={t('Managers','经理')}>{people.filter(x=>x.role==='manager').map(x=><option key={x.id} value={x.id}>经理 · {x.full_name||x.id}</option>)}</optgroup><optgroup label={t('Vendeurs','销售')}>{people.filter(x=>x.role==='sales').map(x=><option key={x.id} value={x.id}>销售 · {x.full_name||x.id}</option>)}</optgroup></select><button className="primary-action" disabled={busy||selected.length===0||!bulkTarget} onClick={()=>void bulkAssign()}>{t('Attribuer en lot','批量分配')}</button>{selected.length>0&&<button className="ghost" onClick={()=>setSelected([])}>{t('Effacer','取消选择')}</button>}</div></div><div className="lr-table-wrap"><table className="lr-table"><thead><tr><th><input type="checkbox" checked={allVisible} onChange={toggleAll}/></th><th>{t('Prospect','潜客')}</th><th>{t('Commentaire','评论')}</th><th>{t('Score','评分')}</th><th>{t('Attribue a','当前分配')}</th><th>{t('Reattribuer','单独分配')}</th></tr></thead><tbody>{visible.length===0?<tr><td className="empty" colSpan={6}>{t('Aucun prospect','暂无潜客')}</td></tr>:visible.map(l=>{const p=l.assigned_to?names.get(l.assigned_to):null;return <tr key={l.id}><td><input type="checkbox" checked={selected.includes(l.id)} onChange={()=>toggle(l.id)}/></td><td><b>@{l.username}</b><small>{l.display_name||'—'}</small></td><td className="quote">“{l.original_text}”</td><td><span className="score">{l.intent_score}</span></td><td>{p?(p.role==='manager'?t('Manager','经理'):t('Vendeur','销售'))+' · '+(p.full_name||p.id):t('Non attribue','未分配')}</td><td><select disabled={busy} defaultValue="" onChange={e=>void assignOne(l.id,e.target.value)}><option value="">{t('Choisir','选择')}</option><optgroup label={t('Managers','经理')}>{people.filter(x=>x.role==='manager').map(x=><option key={x.id} value={x.id}>{x.full_name||x.id}</option>)}</optgroup><optgroup label={t('Vendeurs','销售')}>{people.filter(x=>x.role==='sales').map(x=><option key={x.id} value={x.id}>{x.full_name||x.id}</option>)}</optgroup></select></td></tr>})}</tbody></table></div></section>
}
