import { useCallback, useEffect, useMemo, useState } from 'react'
import { Check, Plus, RefreshCw, X, XCircle } from 'lucide-react'
import { supabase } from '../lib/supabase'
import type { Lang, Role } from '../lib/modules'

type Approval={id:string;vehicle_id:string|null;vehicle_label:string|null;customer_id:string|null;customer_name:string|null;asking_price:number|null;requested_price:number|null;requested_price_xof:number|null;reason:string|null;status:string|null;manager_status:string|null;manager_note:string|null;owner_status:string|null;owner_note:string|null;discount_amount_xof:number|null;created_at:string;requested_by:string|null}
type Vehicle={id:string;make:string|null;model:string|null;trim:string|null;asking_price:number|null}
type Customer={id:string;full_name:string;phone:string|null;assigned_to:string|null}
const fmt=(n:number|null|undefined)=>n==null?'—':new Intl.NumberFormat('fr-FR').format(n)+' XOF'

export default function PriceApprovalModule({lang,role,userId}:{lang:Lang;role:Role;userId:string}){
 const admin=role==='owner'||role==='manager',owner=role==='owner'
 const[rows,setRows]=useState<Approval[]>([]),[vehicles,setVehicles]=useState<Vehicle[]>([]),[customers,setCustomers]=useState<Customer[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[creating,setCreating]=useState(false),[limit,setLimit]=useState(500000),[savingLimit,setSavingLimit]=useState(false)
 const load=useCallback(async()=>{if(!supabase)return;setLoading(true);setError('');let q=supabase.from('price_approvals').select('*').order('created_at',{ascending:false});if(role==='sales')q=q.eq('requested_by',userId);const vehicleRelation=role==='owner'?'vehicles':role==='manager'?'manager_vehicle_catalog':'sales_vehicle_catalog';let cq=supabase.from('customers').select('id,full_name,phone,assigned_to').order('created_at',{ascending:false});if(role==='sales')cq=cq.eq('assigned_to',userId);const[{data,error},{data:vs},{data:cs},{data:setting}]=await Promise.all([q,supabase.from(vehicleRelation).select('id,make,model,trim,asking_price'),cq,admin?supabase.from('pricing_settings').select('manager_discount_limit_xof').eq('id',true).maybeSingle():Promise.resolve({data:null})]);if(error)setError(error.message);else setRows((data||[]) as Approval[]);setVehicles((vs||[]) as Vehicle[]);setCustomers((cs||[]) as Customer[]);if(setting?.manager_discount_limit_xof!=null)setLimit(Number(setting.manager_discount_limit_xof));setLoading(false)},[role,userId,admin])
 useEffect(()=>{void load()},[load])
 const pending=useMemo(()=>rows.filter(r=>role==='manager'?r.manager_status==='pending':role==='owner'?r.owner_status==='pending':r.status==='pending'),[rows,role])
 const decide=async(r:Approval,decision:'approved'|'rejected')=>{if(!supabase||!admin)return;const note=prompt(lang==='fr'?'Note de décision (optionnel)':'审批备注（可选）')||'';const{data,error}=await supabase.functions.invoke('price-approval-decision',{body:{id:r.id,decision,note}});if(error||data?.error)setError(error?.message||data?.error);else void load()}
 const saveLimit=async()=>{if(!supabase||!owner)return;setSavingLimit(true);const{error}=await supabase.from('pricing_settings').update({manager_discount_limit_xof:limit,updated_by:userId,updated_at:new Date().toISOString()}).eq('id',true);setSavingLimit(false);if(error)setError(error.message)}
 return <main className="main module-page"><section className="module-title"><div><p>GREEN FAST AUTO · PRICING</p><h1>{lang==='fr'?'Validation des prix':'价格审批'}</h1><h2>{lang==='fr'?'Les commerciaux demandent, le manager valide dans sa limite, le propriétaire décide au-delà.':'销售提交申请，经理在权限内审批，超出权限自动升级至 Owner。'}</h2></div><button className="primary" onClick={()=>setCreating(true)}><Plus size={16}/>{lang==='fr'?'Nouvelle demande':'新建价格申请'}</button></section>
 {admin&&<div className="card" style={{marginBottom:16,padding:16,display:'flex',gap:12,alignItems:'center',flexWrap:'wrap'}}><strong>{lang==='fr'?'Limite de remise manager':'经理可审批优惠额度'}</strong><span>{fmt(limit)}</span>{owner&&<><input type="number" value={limit} onChange={e=>setLimit(Number(e.target.value)||0)} style={{height:38,border:'1px solid #dfe6e2',borderRadius:8,padding:'0 10px'}}/><button className="secondary" onClick={()=>void saveLimit()} disabled={savingLimit}>{lang==='fr'?'Enregistrer':'保存额度'}</button></>}</div>}
 <div className="module-toolbar"><button className="secondary" onClick={()=>void load()}><RefreshCw size={15}/>{lang==='fr'?'Actualiser':'刷新'}</button>{admin&&<span style={{fontSize:12,color:'#65736d'}}>{lang==='fr'?`${pending.length} demande(s) à traiter`:`${pending.length} 条待审批`}</span>}</div>{error&&<div className="error-banner">{error}</div>}
 {loading?<div className="card loading-state">…</div>:<div className="card data-wrap"><table><thead><tr><th>{lang==='fr'?'Véhicule':'车辆'}</th><th>{lang==='fr'?'Client':'客户'}</th><th>{lang==='fr'?'Prix affiché':'标价'}</th><th>{lang==='fr'?'Prix demandé':'申请售价'}</th><th>{lang==='fr'?'Remise':'优惠金额'}</th><th>Manager</th><th>Owner</th><th>{lang==='fr'?'Statut':'状态'}</th><th>{lang==='fr'?'Actions':'操作'}</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.vehicle_label||'—'}</td><td>{r.customer_name||'—'}</td><td>{fmt(r.asking_price)}</td><td>{fmt(r.requested_price??r.requested_price_xof)}</td><td>{fmt(r.discount_amount_xof)}</td><td>{r.manager_status||'—'}</td><td>{r.owner_status||'—'}</td><td>{r.status||'—'}</td><td className="row-actions">{role==='manager'&&r.manager_status==='pending'&&<><button title="Approve" onClick={()=>void decide(r,'approved')}><Check/></button><button title="Reject" onClick={()=>void decide(r,'rejected')}><XCircle/></button></>}{role==='owner'&&r.owner_status==='pending'&&<><button title="Approve" onClick={()=>void decide(r,'approved')}><Check/></button><button title="Reject" onClick={()=>void decide(r,'rejected')}><XCircle/></button></>}</td></tr>)}</tbody></table></div>}
 {creating&&<RequestModal lang={lang} userId={userId} vehicles={vehicles} customers={customers} close={()=>setCreating(false)} saved={()=>{setCreating(false);void load()}}/>}</main>
}

function RequestModal({lang,userId,vehicles,customers,close,saved}:{lang:Lang;userId:string;vehicles:Vehicle[];customers:Customer[];close:()=>void;saved:()=>void}){
 const[vehicleId,setVehicleId]=useState(''),[customerId,setCustomerId]=useState(''),[price,setPrice]=useState(''),[reason,setReason]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState('');const vehicle=vehicles.find(v=>v.id===vehicleId),customer=customers.find(c=>c.id===customerId)
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!supabase||!vehicle)return;setSaving(true);setError('');const requested=Number(price);const label=[vehicle.make,vehicle.model,vehicle.trim].filter(Boolean).join(' ');const{error}=await supabase.from('price_approvals').insert({vehicle_id:vehicle.id,vehicle_label:label,customer_id:customer?.id||null,customer_name:customer?.full_name||null,asking_price:vehicle.asking_price,requested_price:requested,requested_price_xof:requested,requested_by:userId,reason,status:'pending',manager_status:'pending'});setSaving(false);if(error)setError(error.message);else saved()}
 return <div className="modal-layer"><div className="modal"><div className="modal-head"><div><small>PRICE APPROVAL</small><h2>{lang==='fr'?'Nouvelle demande':'新建价格申请'}</h2></div><button onClick={close}><X/></button></div><form onSubmit={submit}><div className="form-grid"><label className="wide">{lang==='fr'?'Véhicule':'车辆'}<select required value={vehicleId} onChange={e=>{setVehicleId(e.target.value);const v=vehicles.find(x=>x.id===e.target.value);if(v?.asking_price!=null)setPrice(String(v.asking_price))}}><option value="">—</option>{vehicles.map(v=><option value={v.id} key={v.id}>{[v.make,v.model,v.trim].filter(Boolean).join(' ')} · {fmt(v.asking_price)}</option>)}</select></label><label className="wide">{lang==='fr'?'Client':'客户'}<select value={customerId} onChange={e=>setCustomerId(e.target.value)}><option value="">—</option>{customers.map(c=><option value={c.id} key={c.id}>{c.full_name} · {c.phone||''}</option>)}</select></label><label>{lang==='fr'?'Prix affiché':'标价'}<input disabled value={vehicle?.asking_price??''}/></label><label>{lang==='fr'?'Prix demandé':'申请售价'}<input required type="number" value={price} onChange={e=>setPrice(e.target.value)}/></label><label className="wide">{lang==='fr'?'Motif':'申请原因'}<textarea required value={reason} onChange={e=>setReason(e.target.value)}/></label></div>{error&&<div className="error-banner">{error}</div>}<div className="form-actions"><button type="button" className="secondary" onClick={close}>{lang==='fr'?'Annuler':'取消'}</button><button className="primary" disabled={saving}>{saving?'…':lang==='fr'?'Envoyer':'提交审批'}</button></div></form></div></div>
}
