import {useEffect,useMemo,useState} from 'react'
import {RefreshCw} from 'lucide-react'
import {supabase} from '../lib/supabase'
import type {Lang} from '../lib/modules'

type Lead={id:string;username:string;display_name:string|null;source_type:string;intent_score:number;assigned_to:string|null;assigned_at:string|null;sla_due_at:string|null;reclaim_at:string|null;response_started_at:string|null;sla_state:string|null;reassignment_count:number}
type P={id:string;full_name:string|null}
const fields='id,username,display_name,source_type,intent_score,assigned_to,assigned_at,sla_due_at,reclaim_at,response_started_at,sla_state,reassignment_count'
export default function ProspectSlaBoard({lang}:{lang:Lang}){const t=(fr:string,zh:string)=>lang==='fr'?fr:zh;const[rows,setRows]=useState<Lead[]>([]),[names,setNames]=useState<Record<string,string>>({});const load=async()=>{if(!supabase)return;const[{data:l},{data:p}]=await Promise.all([supabase.from('social_leads').select(fields).not('sla_due_at','is',null).order('assigned_at',{ascending:false}).limit(100),supabase.from('profiles').select('id,full_name').eq('active',true)]);setRows((l||[]) as Lead[]);setNames(Object.fromEntries(((p||[]) as P[]).map(x=>[x.id,x.full_name||x.id.slice(0,8)])))};useEffect(()=>{void load();const x=window.setInterval(()=>void load(),30_000);return()=>window.clearInterval(x)},[]);const pending=useMemo(()=>rows.filter(x=>!x.response_started_at),[rows]);const overdue=pending.filter(x=>x.sla_due_at&&new Date(x.sla_due_at)<=new Date());const critical=pending.filter(x=>x.reclaim_at&&new Date(x.reclaim_at)<=new Date());return <section className="radar-owner-controls"><div className="roc-head"><div><span className="eyebrow">OWNER · RESPONSE SLA V0.6.7</span><h2>{t('Vitesse de traitement prospects','潜客响应速度')}</h2><p>{t('LIVE/A: rappel 3 min, reprise et réattribution à 10 min.','LIVE/A级：3分钟提醒，10分钟自动回收重分配。')}</p></div><button className="lr-refresh" onClick={()=>void load()}><RefreshCw size={16}/>{t('Actualiser','刷新')}</button></div><div className="lr-metrics"><Metric n={pending.length} label={t('Urgents en attente','紧急待联系')}/><Metric n={overdue.length} label={t('Retard >3 min','超3分钟')}/><Metric n={critical.length} label={t('À reprendre','到10分钟待回收')}/><Metric n={rows.filter(x=>x.reassignment_count>0).length} label={t('Réattribués','已重分配')}/></div><div className="lr-table-wrap"><table className="lr-table"><thead><tr><th>{t('Prospect','潜客')}</th><th>{t('Vendeur','销售')}</th><th>{t('Type','类型')}</th><th>{t('Score','评分')}</th><th>SLA</th><th>{t('Réattributions','重分配')}</th></tr></thead><tbody>{pending.slice(0,30).map(l=>{const due=l.sla_due_at?Math.ceil((new Date(l.sla_due_at).getTime()-Date.now())/60000):0;const rec=l.reclaim_at?Math.ceil((new Date(l.reclaim_at).getTime()-Date.now())/60000):0;return <tr key={l.id}><td><b>@{l.username}</b><small>{l.display_name||'—'}</small></td><td>{l.assigned_to?names[l.assigned_to]||'—':'—'}</td><td>{l.source_type==='live'?'LIVE':'VIDEO'}</td><td>{l.intent_score}</td><td><span className={`status ${due<=0?'invalid':''}`}>{due>0?t(`${due} min`,`剩${due}分钟`):rec>0?t(`Retard · reprise ${rec} min`,`已超时 · ${rec}分钟后回收`):t('Reprise en cours','回收处理中')}</span></td><td>{l.reassignment_count}</td></tr>})}{pending.length===0&&<tr><td colSpan={6} className="empty">{t('Aucun prospect urgent en attente.','没有紧急待处理潜客。')}</td></tr>}</tbody></table></div></section>}
function Metric({n,label}:{n:number;label:string}){return <div className="lr-metric"><div><strong>{n}</strong><small>{label}</small></div></div>}
