import {useEffect,useState} from 'react'
import {RefreshCw} from 'lucide-react'
import {supabase} from '../lib/supabase'
import type {Lang} from '../lib/modules'
import './TikTokLeadRadar.css'

type Row={sales_id:string;sales_name:string|null;assigned_count:number;urgent_count:number;responded_count:number;response_within_3m_count:number;contacted_count:number;hot_count:number;valid_count:number;long_term_count:number;invalid_count:number;crm_converted_count:number;signed_count:number}
type Period='today'|'7d'|'month'|'all'
function bounds(p:Period){const n=new Date(),s=new Date(n.getFullYear(),n.getMonth(),n.getDate());if(p==='today')return[s.toISOString(),null];if(p==='7d')return[new Date(s.getTime()-6*86400000).toISOString(),null];if(p==='month')return[new Date(n.getFullYear(),n.getMonth(),1).toISOString(),null];return[null,null]}
export default function ProspectFunnelBoard({lang,titleMode='team'}:{lang:Lang;titleMode?:'team'|'owner'}){const t=(fr:string,zh:string)=>lang==='fr'?fr:zh;const[rows,setRows]=useState<Row[]>([]),[period,setPeriod]=useState<Period>('month');const load=async()=>{if(!supabase)return;const[f,to]=bounds(period);const{data}=await supabase.rpc('gfauto_social_lead_funnel',{p_from:f,p_to:to});setRows((data||[]) as Row[])};useEffect(()=>{void load()},[period]);return <section className="wl-panel"><div className="wl-head"><div><span className="eyebrow">PROSPECT FUNNEL · V0.6.9</span><h2>{titleMode==='owner'?t('Performance des vendeurs','销售潜客漏斗作战盘'):t('Performance de mon équipe','团队销售漏斗')}</h2><p>{t('Mesure la vitesse de réponse, la qualité, le passage CRM et les ventes signées.','看每个销售的响应、有效、高意向、转CRM和最终签单。')}</p></div><button className="lr-refresh" onClick={()=>void load()}><RefreshCw size={16}/>{t('Actualiser','刷新')}</button></div><div className="lr-tabs">{(['today','7d','month','all'] as Period[]).map(p=><button key={p} className={period===p?'active':''} onClick={()=>setPeriod(p)}>{p==='today'?t("Aujourd'hui",'今天'):p==='7d'?t('7 jours','7天'):p==='month'?t('Ce mois','本月'):t('Tout','全部')}</button>)}</div><div className="lr-table-wrap"><table className="lr-table"><thead><tr><th>{t('Vendeur','销售')}</th><th>{t('Attribués','分配')}</th><th>{t('Réponse ≤3m','3分钟响应')}</th><th>{t('Contactés','已联系')}</th><th>{t('Forte intention','高意向')}</th><th>{t('Valides','有效')}</th><th>{t('Long terme','长期')}</th><th>{t('Invalides','无效')}</th><th>{t('CRM','转CRM')}</th><th>{t('Signés','成交')}</th></tr></thead><tbody>{rows.length===0?<tr><td className="empty" colSpan={10}>{t('Aucune donnée','暂无数据')}</td></tr>:rows.map(r=>{const rate=r.urgent_count?Math.round(r.response_within_3m_count*100/r.urgent_count):0;return <tr key={r.sales_id}><td><b>{r.sales_name||'—'}</b></td><td>{r.assigned_count}</td><td><span className="score">{rate}%</span><small>{r.response_within_3m_count}/{r.urgent_count}</small></td><td>{r.contacted_count}</td><td>{r.hot_count}</td><td>{r.valid_count}</td><td>{r.long_term_count}</td><td>{r.invalid_count}</td><td>{r.crm_converted_count}</td><td><b>{r.signed_count}</b></td></tr>})}</tbody></table></div></section>}
