import { useEffect, useMemo, useState } from 'react'
import { CalendarDays, CarFront, ChevronLeft, Heart, MapPin, Phone, Search, Sparkles, X } from 'lucide-react'
import { supabase } from '../lib/supabase'

type Lang='fr'|'zh'
type Vehicle={id:string;make:string|null;model:string|null;trim:string|null;year:number|null;mileage:number|null;exterior_color:string|null;interior_color:string|null;fuel_type:string|null;status:string|null;price_xof:number|null;photos:string|null;eta_abidjan:string|null;arrival_date:string|null;created_at:string}
type LeadType='viewing'|'test_drive'|'callback'

const urls=(v:string|null)=>String(v||'').split(/\n|,/).map(x=>x.trim()).filter(x=>/^https?:\/\//.test(x))
const money=(n:number|null)=>n?new Intl.NumberFormat('fr-FR').format(n)+' FCFA':'Prix sur demande'
const txt={
 fr:{title:'Trouvez votre prochaine voiture',sub:'Stock Green Fast Auto · véhicules disponibles et en arrivage',search:'Rechercher une marque ou un modèle…',all:'Tous',fav:'Favoris',view:'Voir le véhicule',book:'Réserver une visite',test:'Réserver un essai',call:'Être rappelé',spec:'Points forts',form:'Votre demande',name:'Nom complet',phone:'Téléphone / WhatsApp',email:'E-mail (optionnel)',date:'Date souhaitée',time:'Heure souhaitée',notes:'Message (optionnel)',send:'Envoyer la demande',sent:'Demande envoyée. Notre équipe vous contactera rapidement.',back:'Retour au stock',available:'Disponible',arrival:'En arrivage',cover:'Affiche automatique'},
 zh:{title:'找到你的下一台车',sub:'Green Fast Auto 在库与在途车辆',search:'搜索品牌或车型…',all:'全部',fav:'收藏',view:'查看车辆',book:'预约看车',test:'预约试驾',call:'请求回电',spec:'核心卖点',form:'提交预约',name:'姓名',phone:'电话 / WhatsApp',email:'邮箱（选填）',date:'预约日期',time:'预约时间',notes:'备注（选填）',send:'提交预约',sent:'预约已提交，我们会尽快联系你。',back:'返回库存',available:'现车',arrival:'在途',cover:'自动海报'}
}

function sellingPoints(v:Vehicle,lang:Lang){
 const points:string[]=[]
 if(v.year)points.push(lang==='fr'?`Millésime ${v.year}`:`${v.year} 年款`)
 if(v.trim)points.push(v.trim)
 if(v.fuel_type)points.push(lang==='fr'?`Motorisation ${v.fuel_type}`:`${v.fuel_type} 动力`)
 if(v.mileage!==null&&v.mileage!==undefined)points.push(v.mileage===0?(lang==='fr'?'Véhicule neuf':'全新车辆'):(lang==='fr'?`${new Intl.NumberFormat('fr-FR').format(v.mileage)} km`:`${new Intl.NumberFormat('zh-CN').format(v.mileage)} 公里`))
 if(v.exterior_color)points.push(lang==='fr'?`Couleur ${v.exterior_color}`:`${v.exterior_color} 外观`)
 if(v.status==='in_transit'||v.status==='ordered')points.push(lang==='fr'?'Arrivage prochain à Abidjan':'即将抵达阿比让')
 return points.slice(0,5)
}

export default function PublicShowroom(){
 const[lang,setLang]=useState<Lang>('fr'),[vehicles,setVehicles]=useState<Vehicle[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[selected,setSelected]=useState<Vehicle|null>(null),[lead,setLead]=useState<{vehicle:Vehicle;type:LeadType}|null>(null),[favorites,setFavorites]=useState<string[]>(()=>{try{return JSON.parse(localStorage.getItem('gf_favorites')||'[]')}catch{return[]}})
 const t=txt[lang]
 useEffect(()=>{void(async()=>{if(!supabase){setError('Service indisponible');setLoading(false);return}const{data,error}=await supabase.from('public_vehicle_catalog').select('*').order('created_at',{ascending:false});if(error)setError(error.message);else setVehicles((data||[]) as Vehicle[]);setLoading(false)})()},[])
 useEffect(()=>{localStorage.setItem('gf_favorites',JSON.stringify(favorites))},[favorites])
 const filtered=useMemo(()=>vehicles.filter(v=>`${v.make||''} ${v.model||''} ${v.trim||''}`.toLowerCase().includes(query.toLowerCase())),[vehicles,query])
 const toggle=(id:string)=>setFavorites(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id])
 if(selected)return <VehiclePage vehicle={selected} lang={lang} favorite={favorites.includes(selected.id)} toggle={()=>toggle(selected.id)} back={()=>setSelected(null)} book={type=>setLead({vehicle:selected,type})} lead={lead} closeLead={()=>setLead(null)}/>
 return <div className="public-showroom"><header className="public-head"><div className="public-brand"><span><CarFront/></span><div><strong>GREEN FAST AUTO</strong><small>ABIDJAN · CÔTE D’IVOIRE</small></div></div><div className="public-head-actions"><button onClick={()=>setLang(lang==='fr'?'zh':'fr')}>{lang==='fr'?'中文':'FR'}</button><button className="fav-link"><Heart size={17}/>{t.fav} <b>{favorites.length}</b></button></div></header><main className="showroom-main"><section className="showroom-hero"><div><small>GREEN FAST AUTO · SHOWROOM</small><h1>{t.title}</h1><p>{t.sub}</p></div><div className="showroom-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.search}/></div></section>{error&&<div className="showroom-error">{error}</div>}{loading?<div className="showroom-loading">Chargement…</div>:<section className="vehicle-public-grid">{filtered.map(v=><VehicleCard key={v.id} v={v} lang={lang} fav={favorites.includes(v.id)} toggle={()=>toggle(v.id)} open={()=>setSelected(v)}/>)}</section>}</main><footer className="showroom-footer"><div><strong>GREEN FAST AUTO</strong><span><MapPin size={14}/> Abidjan, Côte d’Ivoire</span></div><span>Stock mis à jour depuis Green Fast Auto Management</span></footer></div>
}

function VehicleCard({v,lang,fav,toggle,open}:{v:Vehicle;lang:Lang;fav:boolean;toggle:()=>void;open:()=>void}){const t=txt[lang],photo=urls(v.photos)[0],pts=sellingPoints(v,lang);return <article className="public-car"><div className="poster-card" onClick={open}>{photo?<img src={photo} alt={`${v.make||''} ${v.model||''}`}/>:<div className="poster-placeholder"><CarFront/></div>}<div className="poster-shade"/><div className="poster-top"><span>{t.cover}</span><b>GREEN FAST</b></div><div className="poster-copy"><small>{v.year||''} {v.make||''}</small><h2>{v.model||''} {v.trim||''}</h2><strong>{money(v.price_xof)}</strong><div>{pts.slice(0,3).map(p=><span key={p}>{p}</span>)}</div></div></div><div className="public-car-body"><div className="public-car-title"><div><h3>{v.make} {v.model}</h3><p>{v.trim||'—'}</p></div><button onClick={e=>{e.stopPropagation();toggle()}} className={fav?'liked':''}><Heart fill={fav?'currentColor':'none'}/></button></div><div className="public-tags"><span>{v.status==='in_transit'||v.status==='ordered'?t.arrival:t.available}</span>{v.year&&<span>{v.year}</span>}{v.fuel_type&&<span>{v.fuel_type}</span>}</div><button className="public-primary" onClick={open}>{t.view}</button></div></article>}

function VehiclePage({vehicle,lang,favorite,toggle,back,book,lead,closeLead}:{vehicle:Vehicle;lang:Lang;favorite:boolean;toggle:()=>void;back:()=>void;book:(t:LeadType)=>void;lead:{vehicle:Vehicle;type:LeadType}|null;closeLead:()=>void}){const t=txt[lang],photos=urls(vehicle.photos),[current,setCurrent]=useState(0),pts=sellingPoints(vehicle,lang);return <div className="public-showroom"><header className="public-head"><div className="public-brand"><span><CarFront/></span><div><strong>GREEN FAST AUTO</strong><small>ABIDJAN · CÔTE D’IVOIRE</small></div></div></header><main className="vehicle-public-detail"><button className="public-back" onClick={back}><ChevronLeft/>{t.back}</button><div className="vehicle-detail-layout"><section><div className="detail-poster poster-card">{photos[current]?<img src={photos[current]}/>:<div className="poster-placeholder"><CarFront/></div>}<div className="poster-shade"/><div className="poster-top"><span>{t.cover}</span><b>GREEN FAST</b></div><div className="poster-copy"><small>{vehicle.year||''} {vehicle.make||''}</small><h2>{vehicle.model||''} {vehicle.trim||''}</h2><strong>{money(vehicle.price_xof)}</strong><div>{pts.slice(0,3).map(p=><span key={p}>{p}</span>)}</div></div></div>{photos.length>1&&<div className="public-thumbs">{photos.map((p,i)=><button key={p} className={i===current?'active':''} onClick={()=>setCurrent(i)}><img src={p}/></button>)}</div>}</section><aside className="vehicle-public-info"><div className="info-head"><span>{vehicle.status==='in_transit'||vehicle.status==='ordered'?t.arrival:t.available}</span><button className={favorite?'liked':''} onClick={toggle}><Heart fill={favorite?'currentColor':'none'}/></button></div><h1>{vehicle.make} {vehicle.model}</h1><h2>{vehicle.trim}</h2><strong className="public-price">{money(vehicle.price_xof)}</strong><div className="selling-points"><h3><Sparkles/> {t.spec}</h3>{pts.map(p=><p key={p}>✓ {p}</p>)}</div><div className="vehicle-spec-grid"><div><small>Année</small><b>{vehicle.year||'—'}</b></div><div><small>Kilométrage</small><b>{vehicle.mileage!==null?new Intl.NumberFormat('fr-FR').format(vehicle.mileage)+' km':'—'}</b></div><div><small>Énergie</small><b>{vehicle.fuel_type||'—'}</b></div><div><small>Couleur</small><b>{vehicle.exterior_color||'—'}</b></div></div><div className="public-cta"><button className="public-primary" onClick={()=>book('viewing')}><CalendarDays/>{t.book}</button><button className="public-secondary" onClick={()=>book('test_drive')}><CarFront/>{t.test}</button><button className="public-secondary" onClick={()=>book('callback')}><Phone/>{t.call}</button></div></aside></div></main>{lead&&<LeadModal lang={lang} vehicle={lead.vehicle} type={lead.type} close={closeLead}/>}</div>}

function LeadModal({lang,vehicle,type,close}:{lang:Lang;vehicle:Vehicle;type:LeadType;close:()=>void}){const t=txt[lang],[form,setForm]=useState({customer_name:'',phone:'',email:'',preferred_date:'',preferred_time:'',notes:''}),[busy,setBusy]=useState(false),[done,setDone]=useState(false),[error,setError]=useState('');const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!supabase)return;setBusy(true);setError('');const{error}=await supabase.from('vehicle_leads').insert({...form,vehicle_id:vehicle.id,lead_type:type,email:form.email||null,preferred_date:form.preferred_date||null,preferred_time:form.preferred_time||null,notes:form.notes||null});setBusy(false);if(error)setError(error.message);else setDone(true)};return <div className="lead-layer"><div className="lead-modal"><button className="lead-close" onClick={close}><X/></button>{done?<div className="lead-done"><span>✓</span><h2>{t.sent}</h2><button className="public-primary" onClick={close}>OK</button></div>:<><small>GREEN FAST AUTO</small><h2>{t.form}</h2><p>{vehicle.make} {vehicle.model} · {type==='test_drive'?t.test:type==='viewing'?t.book:t.call}</p><form onSubmit={submit}><label>{t.name}<input required value={form.customer_name} onChange={e=>setForm({...form,customer_name:e.target.value})}/></label><label>{t.phone}<input required value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>{t.email}<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><div className="lead-row"><label>{t.date}<input type="date" value={form.preferred_date} onChange={e=>setForm({...form,preferred_date:e.target.value})}/></label><label>{t.time}<input type="time" value={form.preferred_time} onChange={e=>setForm({...form,preferred_time:e.target.value})}/></label></div><label>{t.notes}<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label>{error&&<div className="showroom-error">{error}</div>}<button className="public-primary" disabled={busy}>{busy?'…':t.send}</button></form></>}</div></div>}
