import { useEffect, useMemo, useState } from 'react'
import { CalendarDays, CarFront, Check, ChevronLeft, ChevronRight, GitCompareArrows, Heart, MapPin, Phone, Search, ShieldCheck, Sparkles, Truck, X } from 'lucide-react'
import { supabase } from '../lib/supabase'
import './PublicShowroomV2.css'

type Lang='fr'|'zh'
type Vehicle={id:string;make:string|null;model:string|null;trim:string|null;year:number|null;mileage:number|null;exterior_color:string|null;interior_color:string|null;fuel_type:string|null;status:string|null;price_xof:number|null;photos:string|null;eta_abidjan:string|null;arrival_date:string|null;body_type:string|null;engine:string|null;displacement:string|null;horsepower:number|null;transmission:string|null;drivetrain:string|null;seats:number|null;feature_summary:string|null;created_at:string}
type Banner={id:string;kind:string;vehicle_id:string|null;title:string;subtitle:string|null;badge:string|null;cta_label:string|null;cta_url:string|null;background_image:string|null;template:'midnight'|'emerald'|'sunset'|'clean';sort_order:number}
type LeadType='viewing'|'test_drive'|'callback'
const urls=(v:string|null)=>String(v||'').split(/\n|,/).map(x=>x.trim()).filter(x=>/^https?:\/\//.test(x))
const money=(n:number|null)=>n?new Intl.NumberFormat('fr-FR').format(n)+' FCFA':'Prix sur demande'
const t={fr:{home:'Accueil',stock:'Stock',promo:'Promotions',about:'À propos',appointment:'Prendre RDV',stockTitle:'VÉHICULES EN STOCK',all:'Tous',details:'Voir détails',compare:'Comparer',compareNow:'Comparer maintenant',book:'Réserver une visite',test:'Réserver un essai',callback:'Être rappelé',why:'POURQUOI CHOISIR GREEN FAST AUTO ?',verified:'Véhicules vérifiés',verifiedSub:'Inspection avant livraison',service:'Garantie & SAV',serviceSub:'Accompagnement après-vente',finance:'Prix transparents',financeSub:'Des offres claires',delivery:'Livraison rapide',deliverySub:'Abidjan et intérieur',specs:'Fiche technique',features:'Points forts',back:'Retour au stock',search:'Rechercher une marque ou un modèle…',favorite:'Favoris',compareHint:'Choisissez 2 véhicules à comparer',lead:'Votre demande',send:'Envoyer',name:'Nom complet',phone:'Téléphone / WhatsApp',email:'E-mail (optionnel)',date:'Date souhaitée',time:'Heure',notes:'Message',sent:'Demande envoyée. Notre équipe vous contactera rapidement.'},zh:{home:'首页',stock:'库存',promo:'优惠活动',about:'关于我们',appointment:'预约咨询',stockTitle:'热门在售车型',all:'全部',details:'查看详情',compare:'加入对比',compareNow:'立即对比',book:'预约看车',test:'预约试驾',callback:'请求回电',why:'为什么选择 GREEN FAST AUTO？',verified:'车辆严格验收',verifiedSub:'交付前车辆检查',service:'质保与售后',serviceSub:'售后持续支持',finance:'价格透明',financeSub:'清晰报价体系',delivery:'快速交付',deliverySub:'阿比让及周边',specs:'配置参数',features:'核心卖点',back:'返回库存',search:'搜索品牌或车型…',favorite:'收藏',compareHint:'请选择两款车进行对比',lead:'提交预约',send:'提交',name:'姓名',phone:'电话 / WhatsApp',email:'邮箱（选填）',date:'预约日期',time:'时间',notes:'备注',sent:'提交成功，我们会尽快联系你。'}}
const specRows=(v:Vehicle)=>[['Année / 年款',v.year||'—'],['Carrosserie / 车身',v.body_type||'—'],['Moteur / 发动机',v.engine||'—'],['Cylindrée / 排量',v.displacement||'—'],['Puissance / 马力',v.horsepower?`${v.horsepower} ch`:'—'],['Transmission / 变速箱',v.transmission||'—'],['Transmission intégrale / 驱动',v.drivetrain||'—'],['Places / 座位',v.seats||'—'],['Énergie / 能源',v.fuel_type||'—'],['Kilométrage / 里程',v.mileage!=null?`${new Intl.NumberFormat('fr-FR').format(v.mileage)} km`:'—'],['Couleur / 颜色',v.exterior_color||'—']]
const points=(v:Vehicle,lang:Lang)=>{const custom=String(v.feature_summary||'').split(/\n|,|;/).map(x=>x.trim()).filter(Boolean);if(custom.length)return custom.slice(0,6);return [v.year?(lang==='fr'?`Millésime ${v.year}`:`${v.year} 年款`):'',v.trim||'',v.horsepower?`${v.horsepower} ${lang==='fr'?'ch':'马力'}`:'',v.drivetrain||'',v.transmission||'',v.seats?`${v.seats} ${lang==='fr'?'places':'座'}`:''].filter(Boolean) as string[]}

export default function PublicShowroomV2(){
 const[lang,setLang]=useState<Lang>('fr'),[vehicles,setVehicles]=useState<Vehicle[]>([]),[banners,setBanners]=useState<Banner[]>([]),[hero,setHero]=useState(0),[query,setQuery]=useState(''),[category,setCategory]=useState('all'),[selected,setSelected]=useState<Vehicle|null>(null),[compare,setCompare]=useState<string[]>([]),[compareOpen,setCompareOpen]=useState(false),[lead,setLead]=useState<{vehicle:Vehicle;type:LeadType}|null>(null),[favorites,setFavorites]=useState<string[]>(()=>{try{return JSON.parse(localStorage.getItem('gf_favorites')||'[]')}catch{return[]}})
 const x=t[lang]
 useEffect(()=>{void(async()=>{if(!supabase)return;const[{data:v},{data:b}]=await Promise.all([supabase.from('public_vehicle_catalog').select('*').order('created_at',{ascending:false}),supabase.from('showroom_banners').select('*').order('sort_order')]);setVehicles((v||[]) as Vehicle[]);setBanners((b||[]) as Banner[])})()},[])
 useEffect(()=>{localStorage.setItem('gf_favorites',JSON.stringify(favorites))},[favorites])
 useEffect(()=>{if(banners.length<2)return;const id=setInterval(()=>setHero(h=>(h+1)%banners.length),6500);return()=>clearInterval(id)},[banners.length])
 useEffect(()=>{const id=new URLSearchParams(location.search).get('vehicle');if(id&&vehicles.length){const v=vehicles.find(x=>x.id===id);if(v)setSelected(v)}},[vehicles])
 const heroItems=useMemo(()=>banners.length?banners:vehicles.slice(0,3).map((v,i)=>({id:`auto-${v.id}`,kind:'vehicle',vehicle_id:v.id,title:`${v.make||''} ${v.model||''}`,subtitle:[v.trim,v.year,money(v.price_xof)].filter(Boolean).join(' · '),badge:i===0?'NOUVEAU STOCK':'GREEN FAST SELECT',cta_label:x.details,cta_url:null,background_image:urls(v.photos)[0]||null,template:'midnight' as const,sort_order:i})),[banners,vehicles,x.details])
 const categories=useMemo(()=>['all',...Array.from(new Set(vehicles.map(v=>v.body_type||v.fuel_type).filter(Boolean) as string[])).slice(0,5)],[vehicles])
 const filtered=vehicles.filter(v=>`${v.make||''} ${v.model||''} ${v.trim||''}`.toLowerCase().includes(query.toLowerCase())&&(category==='all'||v.body_type===category||v.fuel_type===category))
 const toggleCompare=(id:string)=>setCompare(c=>c.includes(id)?c.filter(x=>x!==id):c.length<2?[...c,id]:[c[1],id])
 const openBanner=(b:Banner)=>{if(b.vehicle_id){const v=vehicles.find(x=>x.id===b.vehicle_id);if(v)setSelected(v)}}
 if(selected)return <VehicleDetail v={selected} lang={lang} back={()=>setSelected(null)} favorite={favorites.includes(selected.id)} toggleFav={()=>setFavorites(f=>f.includes(selected.id)?f.filter(x=>x!==selected.id):[...f,selected.id])} compare={compare.includes(selected.id)} toggleCompare={()=>toggleCompare(selected.id)} book={type=>setLead({vehicle:selected,type})} lead={lead} closeLead={()=>setLead(null)}/>
 return <div className="gf-site"><header className="gf-nav"><div className="gf-logo"><CarFront/><strong>GREENFAST<span>AUTO</span></strong></div><nav><a>{x.home}</a><a href="#stock">{x.stock}</a><a>{x.promo}</a><a>{x.about}</a></nav><div className="gf-actions"><button className="gf-icon"><Search/></button><button className="gf-icon"><Heart/><b>{favorites.length}</b></button><button className="gf-lang" onClick={()=>setLang(lang==='fr'?'zh':'fr')}>{lang==='fr'?'FR':'中文'}</button><button className="gf-rdv">{x.appointment}</button></div></header>
 {heroItems.length>0&&<section className={`gf-hero hero-${heroItems[hero]?.template||'midnight'}`} style={{backgroundImage:`linear-gradient(90deg,rgba(0,0,0,.88) 0%,rgba(0,0,0,.54) 38%,rgba(0,0,0,.08) 75%),url(${heroItems[hero]?.background_image||urls(vehicles.find(v=>v.id===heroItems[hero]?.vehicle_id)?.photos||null)[0]||''})`}}><button className="hero-arrow left" onClick={()=>setHero(h=>(h-1+heroItems.length)%heroItems.length)}><ChevronLeft/></button><div className="hero-copy"><small>{heroItems[hero]?.badge}</small><h1>{heroItems[hero]?.title}</h1><p>{heroItems[hero]?.subtitle}</p><div className="hero-specs">{vehicles.find(v=>v.id===heroItems[hero]?.vehicle_id)&&points(vehicles.find(v=>v.id===heroItems[hero]?.vehicle_id)!,lang).slice(0,4).map(p=><span key={p}><Check/>{p}</span>)}</div><button onClick={()=>openBanner(heroItems[hero])}>{heroItems[hero]?.cta_label||x.details}</button></div><button className="hero-arrow right" onClick={()=>setHero(h=>(h+1)%heroItems.length)}><ChevronRight/></button><div className="hero-dots">{heroItems.map((_,i)=><button key={i} className={i===hero?'active':''} onClick={()=>setHero(i)}/>)}</div></section>}
 <section className="trust-strip"><div><ShieldCheck/><span><b>{x.verified}</b><small>{x.verifiedSub}</small></span></div><div><Sparkles/><span><b>{x.service}</b><small>{x.serviceSub}</small></span></div><div><Check/><span><b>{x.finance}</b><small>{x.financeSub}</small></span></div><div><Truck/><span><b>{x.delivery}</b><small>{x.deliverySub}</small></span></div></section>
 <main className="gf-main" id="stock"><div className="stock-head"><h2>{x.stockTitle}</h2><div className="stock-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={x.search}/></div></div><div className="category-row">{categories.map(c=><button className={category===c?'active':''} onClick={()=>setCategory(c)} key={c}>{c==='all'?x.all:c}</button>)}</div><div className="gf-car-grid">{filtered.map(v=><CarCard key={v.id} v={v} lang={lang} fav={favorites.includes(v.id)} onFav={()=>setFavorites(f=>f.includes(v.id)?f.filter(x=>x!==v.id):[...f,v.id])} open={()=>setSelected(v)} comparing={compare.includes(v.id)} toggleCompare={()=>toggleCompare(v.id)}/>)}</div>
 <section className="gf-why"><h2>{x.why}</h2><div><article><ShieldCheck/><b>{x.verified}</b><p>{x.verifiedSub}</p></article><article><Sparkles/><b>{x.service}</b><p>{x.serviceSub}</p></article><article><Check/><b>{x.finance}</b><p>{x.financeSub}</p></article><article><Truck/><b>{x.delivery}</b><p>{x.deliverySub}</p></article></div></section></main>
 <footer className="gf-footer"><div className="gf-logo"><CarFront/><strong>GREENFAST<span>AUTO</span></strong></div><p><MapPin/> Abidjan, Côte d’Ivoire</p><span>© Green Fast Auto</span></footer>
 {compare.length>0&&<div className="compare-tray"><GitCompareArrows/><span>{compare.length}/2 · {x.compareHint}</span><div>{compare.map(id=>{const v=vehicles.find(x=>x.id===id)!;return <b key={id}>{v.make} {v.model}<button onClick={()=>toggleCompare(id)}><X/></button></b>})}</div><button disabled={compare.length!==2} onClick={()=>setCompareOpen(true)}>{x.compareNow}</button></div>}
 {compareOpen&&<CompareModal lang={lang} vehicles={compare.map(id=>vehicles.find(v=>v.id===id)!).filter(Boolean)} close={()=>setCompareOpen(false)}/>}</div>
}

function CarCard({v,lang,fav,onFav,open,comparing,toggleCompare}:{v:Vehicle;lang:Lang;fav:boolean;onFav:()=>void;open:()=>void;comparing:boolean;toggleCompare:()=>void}){const x=t[lang],photo=urls(v.photos)[0];return <article className="gf-card"><div className="gf-card-img" onClick={open}>{photo?<img src={photo}/>:<CarFront/>}<span>{v.status==='in_transit'?(lang==='fr'?'EN TRANSIT':'在途'):(lang==='fr'?'EN STOCK':'现车')}</span><button onClick={e=>{e.stopPropagation();onFav()}} className={fav?'liked':''}><Heart fill={fav?'currentColor':'none'}/></button></div><div className="gf-card-body"><h3>{v.make} {v.model}</h3><p>{v.trim||'—'}</p><div className="mini-specs"><span>{v.fuel_type||'—'}</span><span>{v.drivetrain||'—'}</span><span>{v.transmission||'—'}</span></div><strong>{money(v.price_xof)}</strong><div className="card-buttons"><button onClick={open}>{x.details}</button><button className={comparing?'selected':''} onClick={toggleCompare}><GitCompareArrows/>{x.compare}</button></div></div></article>}

function VehicleDetail({v,lang,back,favorite,toggleFav,compare,toggleCompare,book,lead,closeLead}:{v:Vehicle;lang:Lang;back:()=>void;favorite:boolean;toggleFav:()=>void;compare:boolean;toggleCompare:()=>void;book:(x:LeadType)=>void;lead:{vehicle:Vehicle;type:LeadType}|null;closeLead:()=>void}){const x=t[lang],pics=urls(v.photos),[pic,setPic]=useState(0);return <div className="gf-site"><header className="gf-nav"><div className="gf-logo"><CarFront/><strong>GREENFAST<span>AUTO</span></strong></div><button className="detail-back" onClick={back}><ChevronLeft/>{x.back}</button></header><main className="detail-v2"><section className="detail-gallery"><div className="main-photo">{pics[pic]?<img src={pics[pic]}/>:<CarFront/>}</div><div className="thumb-grid">{pics.slice(0,8).map((p,i)=><button className={i===pic?'active':''} onClick={()=>setPic(i)} key={p}><img src={p}/></button>)}</div></section><aside className="detail-summary"><div className="detail-badges"><span>{v.status==='in_transit'?(lang==='fr'?'En transit':'在途'):(lang==='fr'?'Disponible':'现车')}</span><button className={favorite?'liked':''} onClick={toggleFav}><Heart fill={favorite?'currentColor':'none'}/></button></div><small>{v.year} · {v.make}</small><h1>{v.model}</h1><h2>{v.trim}</h2><strong>{money(v.price_xof)}</strong><div className="detail-highlights">{points(v,lang).map(p=><span key={p}><Check/>{p}</span>)}</div><button className="big-cta" onClick={()=>book('viewing')}><CalendarDays/>{x.book}</button><button className="outline-cta" onClick={()=>book('test_drive')}><CarFront/>{x.test}</button><button className="outline-cta" onClick={toggleCompare}><GitCompareArrows/>{compare?`${x.compare} ✓`:x.compare}</button></aside><section className="spec-section"><h2>{x.specs}</h2><div className="spec-table">{specRows(v).map(([k,val])=><div key={String(k)}><span>{k}</span><b>{val}</b></div>)}</div></section><section className="feature-section"><h2>{x.features}</h2><div>{points(v,lang).map(p=><span key={p}><Sparkles/>{p}</span>)}</div></section></main>{lead&&<LeadModal lang={lang} vehicle={lead.vehicle} type={lead.type} close={closeLead}/>}</div>}

function CompareModal({lang,vehicles,close}:{lang:Lang;vehicles:Vehicle[];close:()=>void}){if(vehicles.length<2)return null;const rows=['year','body_type','engine','displacement','horsepower','transmission','drivetrain','seats','fuel_type','mileage','exterior_color'] as const;const labels:Record<string,string>={year:'Année / 年款',body_type:'Carrosserie / 车身',engine:'Moteur / 发动机',displacement:'Cylindrée / 排量',horsepower:'Puissance / 马力',transmission:'Transmission / 变速箱',drivetrain:'4WD / 驱动',seats:'Places / 座位',fuel_type:'Énergie / 能源',mileage:'Kilométrage / 里程',exterior_color:'Couleur / 颜色'};return <div className="compare-layer"><div className="compare-modal"><button className="compare-close" onClick={close}><X/></button><h2>{lang==='fr'?'Comparatif véhicules':'车型参数对比'}</h2><div className="compare-head"><span></span>{vehicles.map(v=><div key={v.id}><img src={urls(v.photos)[0]}/><b>{v.make} {v.model}</b><strong>{money(v.price_xof)}</strong></div>)}</div>{rows.map(r=><div className="compare-row" key={r}><span>{labels[r]}</span>{vehicles.map(v=><b key={v.id}>{String(v[r]??'—')}</b>)}</div>)}</div></div>}

function LeadModal({lang,vehicle,type,close}:{lang:Lang;vehicle:Vehicle;type:LeadType;close:()=>void}){const x=t[lang],[form,setForm]=useState({customer_name:'',phone:'',email:'',preferred_date:'',preferred_time:'',notes:''}),[busy,setBusy]=useState(false),[done,setDone]=useState(false),[error,setError]=useState('');const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!supabase)return;setBusy(true);setError('');const{data,error}=await supabase.functions.invoke('showroom-lead',{body:{...form,vehicle_id:vehicle.id,lead_type:type,email:form.email||null,preferred_date:form.preferred_date||null,preferred_time:form.preferred_time||null,notes:form.notes||null}});setBusy(false);if(error||data?.error)setError(error?.message||data.error);else setDone(true)};return <div className="lead-layer"><div className="lead-modal"><button className="lead-close" onClick={close}><X/></button>{done?<div className="lead-done"><span>✓</span><h2>{x.sent}</h2></div>:<><small>GREEN FAST AUTO</small><h2>{x.lead}</h2><p>{vehicle.make} {vehicle.model} · {type}</p><form onSubmit={submit}><label>{x.name}<input required value={form.customer_name} onChange={e=>setForm({...form,customer_name:e.target.value})}/></label><label>{x.phone}<input required value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>{x.email}<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><div className="lead-row"><label>{x.date}<input type="date" value={form.preferred_date} onChange={e=>setForm({...form,preferred_date:e.target.value})}/></label><label>{x.time}<input type="time" value={form.preferred_time} onChange={e=>setForm({...form,preferred_time:e.target.value})}/></label></div><label>{x.notes}<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label>{error&&<div className="showroom-error">{error}</div>}<button className="big-cta" disabled={busy}>{busy?'…':x.send}</button></form></>}</div></div>}
