import {useEffect,useState} from 'react'
import {CarFront,CheckCircle2,MessageCircle,ShieldCheck} from 'lucide-react'
import {supabase} from '../lib/supabase'
import './PublicTrackingGateway.css'

type BioInfo={code:string;profile_id:string;employee_name:string;destination:string;whatsapp_mode?:string}
export default function PublicEmployeeBioGateway(){
 const code=decodeURIComponent(window.location.pathname.split('/').pop()||'').toUpperCase()
 const[info,setInfo]=useState<BioInfo|null>(null),[name,setName]=useState(''),[whatsapp,setWhatsapp]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('')
 useEffect(()=>{void load()},[code])
 const load=async()=>{try{setLoading(true);setError('');if(!supabase)throw new Error('Service indisponible');const{data,error}=await supabase.rpc('gf_get_employee_bio_link',{p_code:code});if(error)throw error;const row=Array.isArray(data)?data[0]:data;if(!row)throw new Error('Lien indisponible ou non configuré');setInfo(row as BioInfo);void supabase.rpc('gf_record_employee_bio_click',{p_code:code})}catch(e:any){setError(e?.message||'Lien invalide')}finally{setLoading(false)}}
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!info||!supabase)return;try{setSaving(true);setError('');const{data,error}=await supabase.rpc('gf_capture_employee_bio_lead',{p_code:code,p_full_name:name.trim(),p_whatsapp:whatsapp.trim(),p_interested_model:null});if(error)throw error;const row=Array.isArray(data)?data[0]:data;const dest=String(row?.destination||info.destination).replace(/\D/g,'');const text=`Bonjour ${info.employee_name}, je viens de votre TikTok Green Fast Auto. Réf: ${code}`;window.location.href=`https://wa.me/${dest}?text=${encodeURIComponent(text)}`}catch(e:any){setError(e?.message||'Impossible de continuer')}finally{setSaving(false)}}
 if(loading)return <main className="tg-page"><div className="tg-card tg-loading">Chargement…</div></main>
 if(error&&!info)return <main className="tg-page"><div className="tg-card"><div className="tg-brand"><CarFront/><b>GREEN FAST AUTO</b></div><h1>Lien indisponible</h1><p>{error}</p></div></main>
 return <main className="tg-page"><section className="tg-card tg-fast"><div className="tg-brand"><CarFront/><b>GREEN FAST AUTO</b></div><span className="tg-badge"><CheckCircle2 size={15}/> TikTok · {info?.employee_name}</span><h1>Parlez directement avec votre conseiller</h1><p className="tg-sub">2 informations, puis WhatsApp. Aucun questionnaire.</p><form onSubmit={submit}><label>Votre nom<input autoFocus autoComplete="name" value={name} onChange={e=>setName(e.target.value)} placeholder="Ex. Yao Kouassi" required minLength={2}/></label><label>Votre WhatsApp<input autoComplete="tel" value={whatsapp} onChange={e=>setWhatsapp(e.target.value)} placeholder="Ex. 07 00 00 00 00" required inputMode="tel"/></label>{error&&<div className="tg-error">{error}</div>}<button disabled={saving}><MessageCircle size={18}/>{saving?'Un instant…':'Continuer sur WhatsApp'}</button></form><div className="tg-trust"><ShieldCheck size={16}/><span>Suivi commercial Green Fast Auto uniquement.</span></div><footer><b>{info?.employee_name}</b><span>Green Fast Auto</span></footer></section></main>
}
