import { useEffect, useState } from 'react'
import { Bot, CarFront, CircleDollarSign, RefreshCw, Target, TrendingUp, Zap } from 'lucide-react'
import type { Lang, Role } from '../lib/modules'
import { getRevenueDirector, getRevenueLearningMatrix, type RevenueLearningRow, type RevenueRecommendation } from '../lib/revenueDirector'
import '../revenue-director.css'

export default function RevenueDirector({lang,userId,role}:{lang:Lang;userId:string;role?:Role}){
 const zh=lang==='zh';const[rows,setRows]=useState<RevenueRecommendation[]>([]),[matrix,setMatrix]=useState<RevenueLearningRow[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[coverage,setCoverage]=useState(0),[liveId,setLiveId]=useState<string|null>(null),[note,setNote]=useState('')
 const load=async()=>{setLoading(true);setError('');try{const [r,m]=await Promise.all([getRevenueDirector(userId),getRevenueLearningMatrix(role==='owner'||role==='manager'?undefined:userId)]);setRows(r.recommendations);setCoverage(r.grossProfitCoverage);setLiveId(r.liveSessionId);setNote(r.note);setMatrix(m)}catch(e:any){setError(e?.message||String(e))}finally{setLoading(false)}}
 useEffect(()=>{void load()},[userId,role])
 const money=(n:number)=>n?`${Math.round(n/100000)/10} M CFA`:'0'
 const top=rows[0]
 return <main className="rad-page">
  <section className="rad-hero"><div><span><Bot size={15}/> LIVE SALES AI • V0.5.2</span><h1>{zh?'Revenue AI Director':'Revenue AI Director'}</h1><p>{zh?'从车型优先级继续学习到“销售 × 车型 × 动作 × CTA”的真实业务结果。':'Le système apprend désormais par vendeur × modèle × action × CTA à partir des résultats business.'}</p></div><button onClick={()=>void load()}><RefreshCw size={16}/>{zh?'刷新':'Actualiser'}</button></section>
  {error&&<div className="rad-error">{error}</div>}
  <section className="rad-status"><div><small>{zh?'毛利数据覆盖':'Couverture marge brute'}</small><strong>{coverage}%</strong></div><div><small>{zh?'当前直播':'Session LIVE'}</small><strong>{liveId?liveId.slice(0,8):zh?'暂无':'Aucune'}</strong></div><div><small>{zh?'模型数量':'Modèles analysés'}</small><strong>{rows.length}</strong></div><div><small>{zh?'学习组合':'Combinaisons apprises'}</small><strong>{matrix.length}</strong></div></section>
  {top&&<section className="rad-primary"><div><span>{zh?'当前优先车型':'PRIORITÉ ACTUELLE'}</span><h2>{top.model}</h2><p>{zh?'当前预计商业价值最高；执行AI动作后会把车型和经济目标一起写入学习记录。':'La priorité économique est enregistrée avec chaque action AI Director pour apprendre après conversion.'}</p></div><div><small>{top.valueBasis==='gross_profit'?(zh?'预计毛利价值':'Valeur marge attendue'):(zh?'预计收入代理值':'Proxy de revenu attendu')}</small><strong>{money(top.expectedValue)}</strong><em>{zh?'成交概率':'Prob. de vente'} {(top.closeProbability*100).toFixed(1)}% · {top.confidence}</em></div></section>}
  <section className="rad-grid">{rows.map((r,i)=><article key={r.model} className={i===0?'top':''}><header><div><CarFront size={18}/><b>{r.model}</b></div><span>#{i+1}</span></header><div className="rad-metrics"><div><small>{zh?'车辆':'Unités'}</small><strong>{r.units}</strong></div><div><small>{zh?'运输中':'Transit'}</small><strong>{r.inTransit}</strong></div><div><small>{zh?'LIVE线索':'Leads LIVE'}</small><strong>{r.leads}</strong></div><div><small>{zh?'成交':'Ventes'}</small><strong>{r.sales}</strong></div></div><div className="rad-value"><Target size={15}/><div><small>{r.valueBasis==='gross_profit'?(zh?'真实毛利基础':'Marge brute réelle'):(zh?'收入代理基础':'Proxy revenu')}</small><b>{money(r.unitValue)}</b></div></div><div className="rad-score"><TrendingUp size={15}/><span>{zh?'预计商业价值':'Valeur attendue'}</span><strong>{money(r.expectedValue)}</strong></div><p>{r.reason}</p><footer><span>{(r.closeProbability*100).toFixed(1)}% close</span><span className={`q ${r.confidence.toLowerCase()}`}>{r.confidence}</span><span>{r.grossProfitAvailable?(zh?'毛利可用':'GP OK'):(zh?'成本缺失':'COST MISSING')}</span></footer></article>)}</section>
  <section className="rad-learning"><header><div><Zap size={18}/><div><b>{zh?'销售策略学习矩阵':'MATRICE D’APPRENTISSAGE COMMERCIAL'}</b><small>{zh?'销售 × 车型 × AI动作 × CTA':'Vendeur × modèle × action IA × CTA'}</small></div></div><span>{zh?'不是因果证明':'ANALYTIQUE · NON CAUSAL'}</span></header><div className="rad-table"><table><thead><tr><th>{zh?'车型':'Modèle'}</th><th>{zh?'动作':'Action'}</th><th>CTA</th><th>{zh?'次数':'Actions'}</th><th>{zh?'助攻线索':'Leads'}</th><th>{zh?'预约':'RDV'}</th><th>{zh?'成交':'Ventes'}</th><th>{zh?'预计价值变化':'Lift valeur'}</th><th>{zh?'关联成交额':'CA associé'}</th></tr></thead><tbody>{matrix.length?matrix.map((m,i)=><tr key={`${m.presenterId}-${m.model}-${m.actionType}-${m.ctaType}-${i}`}><td><b>{m.model}</b></td><td>{m.actionType.split('_').join(' ')}</td><td>{m.ctaType.split('_').join(' ')}</td><td>{m.actions}</td><td>{m.assistedLeads}</td><td>{m.appointments}</td><td><b>{m.sales}</b></td><td className={m.avgExpectedLift>0?'positive':m.avgExpectedLift<0?'negative':''}>{m.avgExpectedLift>0?'+':''}{money(m.avgExpectedLift)}</td><td>{money(m.revenue)}</td></tr>):<tr><td colSpan={9}>{zh?'执行并测量AI动作后，这里会开始积累真实学习样本。':'La matrice se remplira après exécution et mesure des actions AI Director.'}</td></tr>}</tbody></table></div><p>{zh?'预计价值变化是内部决策指标；关联成交额来自助攻归因，不代表该动作单独造成了成交。':'Le lift de valeur est un indicateur interne. Le CA associé provient de l’attribution assistée et ne prouve pas une causalité.'}</p></section>
  {!loading&&!rows.length&&<div className="rad-empty">{zh?'暂无可计算车型':'Aucun modèle exploitable pour le moment'}</div>}
  <section className="rad-note"><CircleDollarSign size={18}/><div><b>{zh?'当前模型说明':'Règle actuelle V0.5.2'}</b><p>{zh?'成交概率使用Beta(1,11)内部基线，并随着真实LIVE成交样本增加逐步被真实数据替代。执行动作时记录预计商业价值，动作测量结束后再次计算同车型价值，从而得到Expected Value Lift。':'La probabilité utilise un prior interne Beta(1,11), progressivement remplacé par les résultats observés. La valeur attendue est enregistrée avant et après chaque action afin de calculer un Expected Value Lift.'}</p><p>{note}</p></div></section>
 </main>
}
