import {useEffect,useMemo,useState} from 'react'
import {CheckCircle2,Link2,Loader2,Phone,ShieldCheck} from 'lucide-react'
import {supabase} from '../lib/supabase'
import {getMyTikTokConnection,getTikTokOAuthReadiness} from '../lib/tiktokAccounts'
import type {Lang} from '../lib/modules'
import './SellerTikTokSetupChecklist.css'

type State={role:string;whatsapp:string;tiktok:boolean;bio:boolean;code:string|null}
export default function SellerTikTokSetupChecklist({lang,userId}:{lang:Lang;userId:string}){
 const zh=lang==='zh',ready=getTikTokOAuthReadiness(),[state,setState]=useState<State|null>(null),[phone,setPhone]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const load=async()=>{if(!supabase)return;const[{data:p},{data:b},connection]=await Promise.all([supabase.from('profiles').select('role,whatsapp').eq('id',userId).maybeSingle(),supabase.from('employee_bio_links').select('active,code,destination').eq('profile_id',userId).maybeSingle(),getMyTikTokConnection(userId)]);const w=p?.whatsapp||'';setPhone(w);setState({role:p?.role||'',whatsapp:w,tiktok:connection?.token_status==='connected',bio:Boolean(b?.active),code:b?.code||null})}
 useEffect(()=>{void load()},[userId])
 const complete=useMemo(()=>Boolean(state?.whatsapp&&state?.tiktok&&state?.bio),[state])
 if(!state||state.role==='owner'||!['sales','manager'].includes(state.role)||complete)return null
 const saveWhatsApp=async()=>{try{setBusy(true);setError('');if(!supabase)throw new Error('Supabase not configured');const {error:e}=await supabase.rpc('gf_set_employee_bio_whatsapp',{p_profile_id:userId,p_destination:phone,p_mode:'personal'});if(e)throw e;await supabase.from('profiles').update({whatsapp:phone}).eq('id',userId);await load()}catch(e:any){setError(e?.message||String(e))}finally{setBusy(false)}}
 const connectTikTok=async()=>{try{setBusy(true);setError('');if(!supabase)throw new Error('Supabase not configured');if(!ready.ready)throw new Error(zh?'TikTok OAuth 尚未配置':'OAuth TikTok non configuré');const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error(zh?'请重新登录':'Reconnectez-vous');const base=import.meta.env.VITE_SUPABASE_URL,res=await fetch(`${base}/functions/v1/tiktok-oauth-start`,{headers:{authorization:`Bearer ${session.access_token}`}}),body=await res.json();if(!res.ok||!body.url)throw new Error(body.error||'TikTok OAuth unavailable');window.location.assign(body.url)}catch(e:any){setError(e?.message||String(e));setBusy(false)}}
 const steps=[{ok:Boolean(state.whatsapp),icon:Phone,title:zh?'绑定个人 WhatsApp':'Renseigner mon WhatsApp',desc:zh?'客户会直接进入你的 WhatsApp。':'Les prospects arrivent directement sur votre WhatsApp.'},{ok:state.tiktok,icon:Link2,title:zh?'连接自己的 TikTok':'Connecter mon TikTok',desc:zh?'只授权你自己的员工 TikTok 账号。':'Autorisez uniquement votre compte TikTok employé.'},{ok:state.bio,icon:ShieldCheck,title:zh?'启用永久 Bio Link':'Activer le Bio Link permanent',desc:zh?'前两步完成后系统自动启用，无需手工设置。':'Activation automatique après les deux premières étapes.'}]
 return <section className="lsa-setup-checklist"><header><div><small>SELLER SETUP</small><h3>{zh?'完成 TikTok 获客配置':'Finaliser ma configuration TikTok'}</h3><p>{zh?'只需配置一次，以后客户会自动进入你的 CRM 和个人 WhatsApp。':'À configurer une seule fois. Les prospects seront ensuite attribués à votre CRM et à votre WhatsApp personnel.'}</p></div><b>{steps.filter(s=>s.ok).length}/3</b></header><div className="lsa-setup-steps">{steps.map(({ok,icon:Icon,title,desc},i)=><article className={ok?'done':''} key={title}><span>{ok?<CheckCircle2/>:<Icon/>}</span><div><small>{zh?'步骤':'ÉTAPE'} {i+1}</small><b>{title}</b><p>{desc}</p>{i===0&&!ok&&<div className="lsa-setup-inline"><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+2250700000000"/><button disabled={busy||phone.replace(/\D/g,'').length<8} onClick={()=>void saveWhatsApp()}>{busy?<Loader2/>:(zh?'保存':'Enregistrer')}</button></div>}{i===1&&!ok&&<button className="lsa-setup-action" disabled={busy||!ready.ready} onClick={()=>void connectTikTok()}>{busy?<Loader2/>:<Link2/>}{zh?'连接 TikTok':'Connecter TikTok'}</button>}{i===2&&state.code&&<code>{state.code}</code>}</div></article>)}</div>{error&&<div className="lsa-setup-error">{error}</div>}<footer>{zh?'员工个人账号不得使用 Green Fast 官方 WhatsApp；官方账号由 Owner 单独管理。':'Un compte employé ne peut pas utiliser le WhatsApp officiel Green Fast. Le compte officiel est géré séparément par le Owner.'}</footer></section>
}
