import {useEffect,useMemo,useState} from 'react'
import {CalendarDays,Eye,MessageCircle,Store,Target,TrendingUp,Video,Radio,Trophy} from 'lucide-react'
import {supabase} from '../lib/supabase'
import type {Lang} from '../lib/modules'
import './seller-sales-cockpit.css'

type Props={lang:Lang;userId:string}
type VideoRow={view_count:number|null;create_time:string|null}
type AttrRow={captured_at:string|null;visited_at:string|null;sold_at:string|null;sale_price_xof:number|null}
const dayStart=(d=new Date())=>new Date(d.getFullYear(),d.getMonth(),d.getDate()).toISOString()
const monthStart=(d=new Date())=>new Date(d.getFullYear(),d.getMonth(),1).toISOString()
const fmt=(n:number)=>new Intl.NumberFormat('fr-FR',{notation:n>=10000?'compact':'standard',maximumFractionDigits:1}).format(n)
const clamp=(n:number)=>Math.max(0,Math.min(100,Math.round(n)))

export default function SellerSalesCockpit({lang,userId}:Props){
 const zh=lang==='zh',[videos,setVideos]=useState<VideoRow[]>([]),[attr,setAttr]=useState<AttrRow[]>([]),[loading,setLoading]=useState(true)
 useEffect(()=>{void(async()=>{try{if(!supabase)return;const start=monthStart();const [{data:v},{data:a}]=await Promise.all([supabase.from('tiktok_videos').select('view_count,create_time').eq('profile_id',userId).gte('create_time',start),supabase.from('tiktok_content_attribution').select('captured_at,visited_at,sold_at,sale_price_xof').eq('profile_id',userId).gte('captured_at',start)]);setVideos((v||[]) as VideoRow[]);setAttr((a||[]) as AttrRow[])}finally{setLoading(false)}})()},[userId])
 const now=new Date(),today=dayStart(now),daysInMonth=new Date(now.getFullYear(),now.getMonth()+1,0).getDate(),day=now.getDate(),daysLeft=Math.max(1,daysInMonth-day+1)
 const stats=useMemo(()=>{const tv=videos.filter(v=>(v.create_time||'')>=today),ta=attr.filter(a=>(a.captured_at||'')>=today);return {todayVideos:tv.length,todayViews:tv.reduce((s,v)=>s+Number(v.view_count||0),0),monthVideos:videos.length,monthViews:videos.reduce((s,v)=>s+Number(v.view_count||0),0),leads:attr.length,visits:attr.filter(a=>a.visited_at).length,sales:attr.filter(a=>a.sold_at).length,revenue:attr.filter(a=>a.sold_at).reduce((s,a)=>s+Number(a.sale_price_xof||0),0),todayLeads:ta.length}},[videos,attr,today])
 // Green Fast operating baseline discussed with sales team: 30 prospects -> about 3 customers/sales per month.
 const targets={prospects:30,sales:3,videos:30,liveMinutes:600}
 const expectedProspects=targets.prospects*day/daysInMonth,expectedSales=targets.sales*day/daysInMonth
 const pace=stats.leads>=expectedProspects*.9&&stats.sales>=expectedSales*.65?'on':stats.leads>=expectedProspects*.65?'risk':'behind'
 const needProspects=Math.max(0,targets.prospects-stats.leads),needSales=Math.max(0,targets.sales-stats.sales)
 const todayNeedProspects=Math.ceil(needProspects/daysLeft),todayNeedVideos=Math.max(0,Math.ceil((targets.videos-stats.monthVideos)/daysLeft)),todayLive=Math.max(0,Math.ceil((targets.liveMinutes/daysInMonth)/10)*10)
 const action=pace==='behind'?(zh?`进度落后：今天优先完成 ${todayNeedVideos} 条视频 + ${todayLive} 分钟 LIVE + ${todayNeedProspects} 个有效客户。`:`Retard : priorité aujourd’hui à ${todayNeedVideos} vidéo(s) + ${todayLive} min LIVE + ${todayNeedProspects} prospect(s) qualifié(s).`):pace==='risk'?(zh?`接近计划线：今天至少补 ${todayNeedProspects} 个有效客户，并把已有客户推进到店。`:`Proche du rythme : ajoutez au moins ${todayNeedProspects} prospect(s) et faites avancer les leads vers la visite.`):(zh?'进度正常：保持内容和 LIVE 节奏，重点推进高意向客户到店与成交。':'Rythme correct : maintenez contenu + LIVE et poussez les prospects chauds vers visite et vente.')
 const progress=[{n:zh?'Prospects':'Prospects',v:stats.leads,t:targets.prospects},{n:zh?'成交':'Ventes',v:stats.sales,t:targets.sales},{n:zh?'视频':'Vidéos',v:stats.monthVideos,t:targets.videos}]
 return <section className="ssc"><header><div><span><TrendingUp size={15}/>{zh?'我的销售作战台':'MON COCKPIT COMMERCIAL'}</span><h2>{zh?'目标 → 进度 → 今天必须做什么':'Objectif → rythme → action du jour'}</h2></div><small><CalendarDays size={14}/>{zh?`本月第 ${day}/${daysInMonth} 天`:`Jour ${day}/${daysInMonth}`}</small></header><div className="ssc-grid"><article><Video/><small>{zh?'今日视频':'Vidéos aujourd’hui'}</small><strong>{stats.todayVideos}</strong><em>{zh?`本月 ${stats.monthVideos}`:`Mois ${stats.monthVideos}`}</em></article><article><Eye/><small>{zh?'今日播放':'Vues aujourd’hui'}</small><strong>{fmt(stats.todayViews)}</strong><em>{zh?`本月 ${fmt(stats.monthViews)}`:`Mois ${fmt(stats.monthViews)}`}</em></article><article><MessageCircle/><small>{zh?'TikTok获客':'Leads TikTok'}</small><strong>{stats.leads}</strong><em>{zh?`今日 ${stats.todayLeads}`:`Aujourd’hui ${stats.todayLeads}`}</em></article><article><Store/><small>{zh?'到店':'Visites'}</small><strong>{stats.visits}</strong><em>{zh?'本月':'Ce mois'}</em></article><article><Target/><small>{zh?'成交':'Ventes'}</small><strong>{stats.sales}</strong><em>{zh?'本月':'Ce mois'}</em></article><article><TrendingUp/><small>{zh?'归因销售额':'CA attribué'}</small><strong>{stats.revenue?`${fmt(Math.round(stats.revenue/1000000))}M`:'0'}</strong><em>CFA · {zh?'内部归因':'attribution interne'}</em></article></div><div className={`ssc-pace ${pace}`}><div className="ssc-pace-title"><span><Trophy size={15}/>{zh?'本月目标进度':'RYTHME MENSUEL'}</span><b>{pace==='on'?(zh?'正常':'DANS LE RYTHME'):pace==='risk'?(zh?'需要追赶':'À RATTRAPER'):(zh?'落后':'EN RETARD')}</b></div><div className="ssc-progress">{progress.map(x=><div key={x.n}><label><span>{x.n}</span><b>{x.v} / {x.t}</b></label><i><em style={{width:`${clamp(x.v/x.t*100)}%`}}/></i></div>)}</div><div className="ssc-gap"><span>{zh?'还差':'Reste'} <b>{needProspects}</b> Prospects</span><span>{zh?'还差':'Reste'} <b>{needSales}</b> {zh?'台成交':'ventes'}</span><span>{zh?'剩余':'Jours restants'} <b>{daysLeft}</b> {zh?'天':'jours'}</span></div></div><div className="ssc-plan"><div><b><Video size={14}/>{zh?'今天内容':'CONTENU'}</b><strong>{todayNeedVideos}</strong><small>{zh?'条视频建议':'vidéo(s) conseillée(s)'}</small></div><div><b><Radio size={14}/>{zh?'今天直播':'LIVE'}</b><strong>{todayLive}</strong><small>{zh?'分钟建议':'minutes conseillées'}</small></div><div><b><MessageCircle size={14}/>{zh?'今天获客':'PROSPECTS'}</b><strong>{todayNeedProspects}</strong><small>{zh?'个有效客户':'prospect(s) qualifié(s)'}</small></div></div><div className="ssc-next"><b>{zh?'AI 今日任务':'ACTION PRIORITAIRE'}</b><p>{loading?(zh?'正在读取你的数据…':'Lecture de vos données…'):action}</p></div><p className="ssc-baseline">{zh?'当前目标基准：30 Prospects/月 → 约3台成交；视频与LIVE为内部执行基准，后续由真实转化数据自动校准。':'Base actuelle : 30 prospects/mois → env. 3 ventes. Les objectifs vidéo/LIVE sont des repères internes qui seront recalibrés avec les conversions réelles.'}</p></section>
}
