import { useEffect, useMemo, useState } from 'react'
import { ArrowRight, BadgeCheck, CircleUserRound, ExternalLink, Flame, Mail, MessageCircle, Phone, Radio, RefreshCw, Search, Video } from 'lucide-react'
import { supabase } from '../lib/supabase'
import type { Lang, Role } from '../lib/modules'
import TikTokWatchlistPanel from './TikTokWatchlistPanel'
import TikTokRadarOwnerControls from './TikTokRadarOwnerControls'
import './TikTokLeadRadar.css'

type LeadStatus='new'|'high_intent'|'assigned'|'contact_attempted'|'replied'|'contact_captured'|'converted'|'invalid'
type SocialLead={id:string;username:string;display_name:string|null;source_type:'live'|'video_comment';original_text:string;interested_model:string|null;intent_label:string|null;intent_score:number;occurrence_count:number;last_seen_at:string;status:LeadStatus;assigned_to:string|null;notes:string|null;public_phone:string|null;public_whatsapp:string|null;public_email:string|null}
type Profile={id:string;full_name:string|null;role:'manager'|'sales'|string}
type SourceDetail={source_account:string|null;source_url:string|null;source_content_id:string|null;source_event_id:string|null}
type Tab='leads'|'monitor'
type SourceFilter='live'|'video_comment'|'all'
const statusCopy:Record<LeadStatus,{fr:string;zh:string}>={new:{fr:'Nouveau',zh:'新发现'},high_intent:{fr:'Intention forte',zh:'高意向'},assigned:{fr:'Assigné',zh:'已分配'},contact_attempted:{fr:'Contact tenté',zh:'已尝试联系'},replied:{fr:'A répondu',zh:'已回复'},contact_captured:{fr:'Contact obtenu',zh:'已取得联系方式'},converted:{fr:'Converti CRM',zh:'已转正式CRM'},invalid:{fr:'Invalide',zh:'无效'}}
const statusFlow:LeadStatus[]=['new','high_intent','assigned','contact_attempted','replied','contact_captured','converted']
const fmtCommentDate=(v:string)=>new Intl.DateTimeFormat('fr-FR',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(v))
const relativeAge=(v:string,lang:Lang)=>{const sec=Math.max(0,Math.floor((Date.now()-new Date(v).getTime())/1000));if(sec<60)return lang==='fr'?'à l’instant':'刚刚';const min=Math.floor(sec/60);if(min<60)return lang==='fr'?`il y a ${min} min`:`${min}分钟前`;const h=Math.floor(min/60);if(h<24)return lang==='fr'?`il y a ${h} h`:`${h}小时前`;return fmtCommentDate(v)}
const safeLeadFields='id,username,display_name,source_type,original_text,interested_model,intent_label,intent_score,occurrence_count,last_seen_at,status,assigned_to,notes,public_phone,public_whatsapp,public_email'

export default function TikTokLeadRadar({lang,role,userId,onOpenCrm}:{lang:Lang;role:Role;userId:string;onOpenCrm:()=>void}){
  const [leads,setLeads]=useState<SocialLead[]>([]),[profiles,setProfiles]=useState<Profile[]>([]),[loading,setLoading]=useState(true),[q,setQ]=useState(''),[filter,setFilter]=useState<'all'|LeadStatus>('all'),[sourceFilter,setSourceFilter]=useState<SourceFilter>('live'),[selected,setSelected]=useState<SocialLead|null>(null),[sourceDetail,setSourceDetail]=useState<SourceDetail|null>(null),[busy,setBusy]=useState(false),[phone,setPhone]=useState(''),[whatsapp,setWhatsapp]=useState(''),[tab,setTab]=useState<Tab>('leads'),[checked,setChecked]=useState<Set<string>>(new Set()),[bulkTarget,setBulkTarget]=useState('')
  const isOwner=role==='owner',txt=(fr:string,zh:string)=>lang==='fr'?fr:zh
  const load=async()=>{if(!supabase)return;setLoading(true);const leadQ=supabase.from('social_leads').select(safeLeadFields).order('last_seen_at',{ascending:false}).limit(300);const profileQ=isOwner?supabase.from('profiles').select('id,full_name,role').in('role',['manager','sales']):Promise.resolve({data:[] as Profile[]});const [{data:leadData},{data:profileData}]=await Promise.all([leadQ,profileQ]);setLeads((leadData||[]) as unknown as SocialLead[]);setProfiles((profileData||[]) as Profile[]);setLoading(false)}
  useEffect(()=>{void load();const t=window.setInterval(()=>void load(),15_000);return()=>window.clearInterval(t)},[])
  const visible=useMemo(()=>leads.filter(l=>(sourceFilter==='all'||l.source_type===sourceFilter)&&(filter==='all'||l.status===filter)&&(!q||`${l.username} ${l.display_name||''} ${l.original_text} ${l.interested_model||''} ${l.public_phone||''} ${l.public_whatsapp||''}`.toLowerCase().includes(q.toLowerCase()))).sort((a,b)=>sourceFilter==='live'?new Date(b.last_seen_at).getTime()-new Date(a.last_seen_at).getTime():(b.intent_score-a.intent_score)||(new Date(b.last_seen_at).getTime()-new Date(a.last_seen_at).getTime())),[leads,q,filter,sourceFilter])
  const selectable=visible.filter(x=>x.status!=='converted'&&x.status!=='invalid')
  const metrics=useMemo(()=>({live:leads.filter(x=>x.source_type==='live'&&x.status!=='converted'&&x.status!=='invalid').length,video:leads.filter(x=>x.source_type==='video_comment'&&x.status!=='converted'&&x.status!=='invalid').length,hot:leads.filter(x=>x.intent_score>=80&&x.status!=='converted'&&x.status!=='invalid').length,converted:leads.filter(x=>x.status==='converted').length}),[leads])
  const toggle=(id:string)=>setChecked(s=>{const n=new Set(s);n.has(id)?n.delete(id):n.add(id);return n})
  const toggleAll=()=>setChecked(s=>selectable.length>0&&selectable.every(x=>s.has(x.id))?new Set():new Set(selectable.map(x=>x.id)))
  const bulkAssign=async()=>{if(!supabase||!isOwner||!bulkTarget||checked.size===0)return;setBusy(true);const{error}=await supabase.rpc('gfauto_bulk_assign_social_leads',{p_lead_ids:Array.from(checked).slice(0,100),p_target_id:bulkTarget});setBusy(false);if(!error){setChecked(new Set());setBulkTarget('');await load()}}
  const assignOne=async(lead:SocialLead,to:string)=>{if(!supabase||!to)return;setBusy(true);const{error}=await supabase.rpc('gfauto_assign_social_lead',{p_lead_id:lead.id,p_target_id:to});setBusy(false);if(!error){await load();setSelected(prev=>prev?.id===lead.id?{...prev,assigned_to:to,status:'assigned'}:prev)}}
  const update=async(id:string,patch:Partial<SocialLead>)=>{if(!supabase)return;setBusy(true);const{error}=await supabase.from('social_leads').update(patch).eq('id',id);setBusy(false);if(!error){setLeads(prev=>prev.map(x=>x.id===id?{...x,...patch}:x));setSelected(prev=>prev?.id===id?{...prev,...patch}:prev)}}
  const advance=async(lead:SocialLead)=>{const i=statusFlow.indexOf(lead.status);if(i>=0&&i<statusFlow.length-2)await update(lead.id,{status:statusFlow[i+1]})}
  const openLead=async(lead:SocialLead)=>{setSelected(lead);setPhone(lead.public_phone||'');setWhatsapp(lead.public_whatsapp||'');setSourceDetail(null);if(isOwner&&supabase){const{data}=await supabase.rpc('gfauto_owner_get_social_lead_source',{p_lead_id:lead.id});if(data)setSourceDetail(data as SourceDetail)}}
  const markContactAttempted=async(lead:SocialLead)=>{if(['new','high_intent','assigned'].includes(lead.status))await update(lead.id,{status:'contact_attempted'});window.open(`https://www.tiktok.com/@${encodeURIComponent(lead.username)}`,'_blank','noopener,noreferrer')}
  const convert=async(lead:SocialLead)=>{if(!supabase||(!phone.trim()&&!whatsapp.trim()))return;setBusy(true);const customerName=lead.display_name||`@${lead.username}`;const{data,error}=await supabase.from('customers').insert({name:customerName,full_name:customerName,phone:phone.trim()||null,whatsapp:whatsapp.trim()||null,source:'tiktok',lead_source:'tiktok',interested_model:lead.interested_model,assigned_sales:lead.assigned_to||userId,assigned_to:lead.assigned_to||userId,stage:'new',notes:`TikTok Lead Radar\n@${lead.username}\nOriginal: ${lead.original_text}`}).select('id').single();if(!error&&data){await supabase.from('social_leads').update({status:'converted',converted_customer_id:data.id}).eq('id',lead.id);setSelected({...lead,status:'converted'});await load()}setBusy(false)}
  const managers=profiles.filter(p=>p.role==='manager'),sales=profiles.filter(p=>p.role==='sales')
  return <section className="lead-radar"><div className="lr-head"><div><span className="eyebrow">TIKTOK LEAD RADAR · V0.6.9</span><h1>{txt('Radar de prospects sociaux','TikTok 客户雷达')}</h1><p>{txt('Sélectionnez plusieurs prospects et attribuez-les directement à un manager ou à un vendeur.','首页直接多选潜客，批量分配给经理或销售。')}</p></div><button className="lr-refresh" onClick={()=>void load()}><RefreshCw size={17}/>{txt('Actualiser','刷新')}</button></div>
    {isOwner&&<div className="lr-tabs"><button className={tab==='leads'?'active':''} onClick={()=>setTab('leads')}>{txt('Prospects','潜客池')}</button><button className={tab==='monitor'?'active':''} onClick={()=>setTab('monitor')}>{txt('Contrôle Radar','监控控制')}</button></div>}
    {tab==='monitor'&&isOwner?<><TikTokRadarOwnerControls lang={lang}/><TikTokWatchlistPanel lang={lang} role={role} userId={userId}/></>:<><div className="lr-tabs"><button className={sourceFilter==='live'?'active':''} onClick={()=>setSourceFilter('live')}><Radio size={15}/> {txt('LIVE temps réel','🔥 LIVE 实时潜客')} · {metrics.live}</button><button className={sourceFilter==='video_comment'?'active':''} onClick={()=>setSourceFilter('video_comment')}><Video size={15}/> {txt('Prospects vidéo','视频潜客')} · {metrics.video}</button><button className={sourceFilter==='all'?'active':''} onClick={()=>setSourceFilter('all')}>{txt('Tous','全部潜客')}</button></div><div className="lr-metrics"><Metric icon={<Radio/>} n={metrics.live} label={txt('LIVE à traiter','LIVE待处理')}/><Metric icon={<Video/>} n={metrics.video} label={txt('Vidéo à traiter','视频待处理')}/><Metric icon={<Flame/>} n={metrics.hot} label={txt('Intentions fortes','高意向')}/><Metric icon={<ArrowRight/>} n={metrics.converted} label={txt('Convertis CRM','已转CRM')}/></div>
    {isOwner&&<div className="lr-toolbar"><button className="ghost" onClick={toggleAll}>{selectable.length>0&&selectable.every(x=>checked.has(x.id))?txt('Tout désélectionner','取消全选'):txt('Tout sélectionner','全选当前列表')}</button><strong>{txt(`${checked.size} sélectionnés`,`已选择 ${checked.size} 个`)}</strong><select value={bulkTarget} onChange={e=>setBulkTarget(e.target.value)}><option value="">{txt('Manager / vendeur','选择经理 / 销售')}</option>{managers.length>0&&<optgroup label={txt('Managers','经理')}>{managers.map(p=><option key={p.id} value={p.id}>👔 {p.full_name||p.id}</option>)}</optgroup>}{sales.length>0&&<optgroup label={txt('Vendeurs','销售')}>{sales.map(p=><option key={p.id} value={p.id}>👤 {p.full_name||p.id}</option>)}</optgroup>}</select><button className="primary-action" disabled={busy||checked.size===0||!bulkTarget} onClick={()=>void bulkAssign()}>{txt('Attribuer la sélection','批量分配')}</button></div>}
    <div className="lr-toolbar"><div className="lr-search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={txt('Rechercher compte, commentaire, modèle, téléphone…','搜索账号、评论、车型、电话…')}/></div><select value={filter} onChange={e=>setFilter(e.target.value as 'all'|LeadStatus)}><option value="all">{txt('Tous les statuts','全部状态')}</option>{Object.entries(statusCopy).map(([k,v])=><option key={k} value={k}>{v[lang]}</option>)}</select></div><div className="lr-table-wrap"><table className="lr-table"><thead><tr>{isOwner&&<th><input type="checkbox" aria-label={txt('Tout sélectionner','全选')} checked={selectable.length>0&&selectable.every(x=>checked.has(x.id))} onChange={toggleAll}/></th>}<th>{txt('Compte','账号')}</th><th>{txt('Type','类型')}</th><th>{sourceFilter==='live'?txt('Fraîcheur','实时性'):txt('Date du commentaire','评论日期')}</th><th>{txt('Commentaire','评论内容')}</th><th>{txt('Modèle','车型')}</th><th>{txt('Score','评分')}</th><th>{txt('Statut','状态')}</th><th></th></tr></thead><tbody>{loading?<tr><td colSpan={isOwner?9:8} className="empty">{txt('Chargement…','加载中…')}</td></tr>:visible.length===0?<tr><td colSpan={isOwner?9:8} className="empty">{txt('Aucun prospect pour le moment.','目前没有潜客。')}</td></tr>:visible.map(l=><tr key={l.id}>{isOwner&&<td>{l.status!=='converted'&&l.status!=='invalid'?<input type="checkbox" checked={checked.has(l.id)} onChange={()=>toggle(l.id)}/>:null}</td>}<td><div className="account"><CircleUserRound size={28}/><div><strong>@{l.username}</strong><small>{l.display_name||'—'} · ×{l.occurrence_count}</small></div></div></td><td><span className="source">{l.source_type==='live'?<Radio size={14}/>:<Video size={14}/>} {l.source_type==='live'?'LIVE':'VIDEO'}</span></td><td><span className="comment-date">{l.source_type==='live'?relativeAge(l.last_seen_at,lang):fmtCommentDate(l.last_seen_at)}</span></td><td className="quote">“{l.original_text}”<small>{l.intent_label||''}</small></td><td>{l.interested_model||'—'}</td><td><span className={`score s${Math.floor(l.intent_score/20)}`}>{l.intent_score}</span></td><td><span className={`status ${l.status}`}>{statusCopy[l.status][lang]}</span></td><td><button className="ghost" onClick={()=>void openLead(l)}>{txt('Ouvrir','打开')}</button></td></tr>)}</tbody></table></div></>}
    {selected&&<div className="lr-drawer-back" onClick={()=>setSelected(null)}><aside className="lr-drawer" onClick={e=>e.stopPropagation()}><button className="drawer-close" onClick={()=>setSelected(null)}>×</button><span className="eyebrow">@{selected.username}</span><h2>{selected.display_name||selected.username}</h2><div className="intent-card"><p>“{selected.original_text}”</p><b>{selected.intent_score}/100</b></div><button className="primary-action" disabled={busy} onClick={()=>void markContactAttempted(selected)}><ExternalLink size={17}/>{txt('Contacter sur TikTok','去TikTok联系')}</button>{(selected.public_phone||selected.public_whatsapp||selected.public_email)&&<div className="public-contact-card"><strong>{txt('Contact public','公开联系方式')}</strong>{selected.public_phone&&<span><Phone size={15}/>{selected.public_phone}</span>}{selected.public_whatsapp&&<span><MessageCircle size={15}/>{selected.public_whatsapp}</span>}{selected.public_email&&<span><Mail size={15}/>{selected.public_email}</span>}</div>}{isOwner&&<label>{txt('Réattribuer à','单独重新分配')}<select value={selected.assigned_to||''} onChange={e=>void assignOne(selected,e.target.value)}><option value="">{txt('Choisir','选择经理 / 销售')}</option>{managers.length>0&&<optgroup label={txt('Managers','经理')}>{managers.map(p=><option key={p.id} value={p.id}>{p.full_name||p.id}</option>)}</optgroup>}{sales.length>0&&<optgroup label={txt('Vendeurs','销售')}>{sales.map(p=><option key={p.id} value={p.id}>{p.full_name||p.id}</option>)}</optgroup>}</select></label>}{!['contact_captured','converted','invalid'].includes(selected.status)&&<button className="secondary-action" disabled={busy} onClick={()=>void advance(selected)}>{txt('Étape suivante','推进到下一状态')} <ArrowRight size={16}/></button>}{selected.status==='contact_captured'&&<div className="convert-box"><h3>{txt('Convertir en client CRM','转为正式CRM客户')}</h3><input placeholder={txt('Téléphone','电话')} value={phone} onChange={e=>setPhone(e.target.value)}/><input placeholder="WhatsApp" value={whatsapp} onChange={e=>setWhatsapp(e.target.value)}/><button className="convert" disabled={busy||(!phone.trim()&&!whatsapp.trim())} onClick={()=>void convert(selected)}>{txt('Créer le client','创建正式CRM客户')}</button></div>}{selected.status==='converted'&&<button className="primary-action" onClick={onOpenCrm}><BadgeCheck size={17}/>{txt('Ouvrir le CRM','打开正式CRM')}</button>}{isOwner&&sourceDetail&&<details className="owner-source"><summary>{txt('Source technique (Owner)','技术来源（仅Owner）')}</summary><small>{sourceDetail.source_account||'—'}</small>{sourceDetail.source_url&&<a href={sourceDetail.source_url} target="_blank" rel="noreferrer">{txt('Ouvrir la source','打开来源')}</a>}</details>}</aside></div>}
  </section>
}
function Metric({icon,n,label}:{icon:React.ReactNode;n:number;label:string}){return <div className="lr-metric"><span>{icon}</span><div><strong>{n}</strong><small>{label}</small></div></div>}
