import { useEffect, useMemo, useState } from 'react'
import { Eye, MapPin, Plus, Radio, Search, Video } from 'lucide-react'
import { supabase } from '../lib/supabase'
import type { Lang, Role } from '../lib/modules'

type Watch={id:string;username:string;display_name:string|null;country_code:string|null;city:string|null;account_type:string|null;priority:number|null;watch_tier:'A'|'B'|'C';live_monitor:boolean;video_comment_monitor:boolean;scan_interval_minutes:number;is_active:boolean}
const tierMinutes:{[k:string]:number}={A:10,B:30,C:120}
export default function TikTokWatchlistPanel({lang,role,userId}:{lang:Lang;role:Role;userId:string}){
  const txt=(fr:string,zh:string)=>lang==='fr'?fr:zh
  const isManager=role==='owner'||role==='manager'
  const [watch,setWatch]=useState<Watch[]>([]),[loading,setLoading]=useState(true),[q,setQ]=useState(''),[busy,setBusy]=useState('')
  const [username,setUsername]=useState(''),[displayName,setDisplayName]=useState(''),[accountType,setAccountType]=useState('dealer'),[tier,setTier]=useState<'A'|'B'|'C'>('B')
  const load=async()=>{if(!supabase)return;setLoading(true);const {data}=await supabase.from('tiktok_watchlist').select('*').order('priority',{ascending:false});setWatch((data||[]) as Watch[]);setLoading(false)}
  useEffect(()=>{void load()},[])
  const filtered=useMemo(()=>watch.filter(x=>!q||`${x.username} ${x.display_name||''} ${x.account_type||''}`.toLowerCase().includes(q.toLowerCase())),[watch,q])
  const add=async()=>{if(!supabase||!username.trim())return;setBusy('add');await supabase.from('tiktok_watchlist').insert({username:username.trim().replace(/^@/,''),display_name:displayName.trim()||null,account_type:accountType,country_code:'CI',city:'Abidjan',market_scope:'abidjan_auto',priority:tier==='A'?90:tier==='B'?70:50,watch_tier:tier,scan_interval_minutes:tierMinutes[tier],created_by:userId});setUsername('');setDisplayName('');setBusy('');await load()}
  const patch=async(id:string,values:Partial<Watch>)=>{if(!supabase)return;setBusy(id);await supabase.from('tiktok_watchlist').update(values).eq('id',id);setBusy('');await load()}
  return <div className="wl-panel"><div className="wl-head"><div><span className="eyebrow">ABIDJAN AUTO WATCHLIST</span><h2>{txt('Comptes TikTok surveillés','TikTok 监控账号')}</h2><p>{txt('LIVE et commentaires vidéo des comptes automobiles sélectionnés.','监控已选汽车账号的直播和视频评论。')}</p></div></div>
    <div className="wl-summary"><div><b>{watch.filter(x=>x.is_active).length}</b><span>{txt('Actifs','启用')}</span></div><div><b>{watch.filter(x=>x.watch_tier==='A'&&x.is_active).length}</b><span>Tier A</span></div><div><b>{watch.filter(x=>x.live_monitor&&x.is_active).length}</b><span>LIVE</span></div><div><b>{watch.filter(x=>x.video_comment_monitor&&x.is_active).length}</b><span>{txt('Commentaires vidéo','视频评论')}</span></div></div>
    {isManager&&<div className="wl-add"><input placeholder="@compte" value={username} onChange={e=>setUsername(e.target.value)}/><input placeholder={txt('Nom affiché','显示名称')} value={displayName} onChange={e=>setDisplayName(e.target.value)}/><select value={accountType} onChange={e=>setAccountType(e.target.value)}><option value="dealer">Dealer</option><option value="importer">Importer</option><option value="blogger">Blogger</option><option value="media">Auto media</option></select><select value={tier} onChange={e=>setTier(e.target.value as 'A'|'B'|'C')}><option value="A">A · 10 min</option><option value="B">B · 30 min</option><option value="C">C · 120 min</option></select><button className="primary-action" disabled={busy==='add'||!username.trim()} onClick={()=>void add()}><Plus size={16}/>{txt('Ajouter','加入监控')}</button></div>}
    <div className="lr-search wl-search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={txt('Rechercher un compte…','搜索监控账号…')}/></div>
    <div className="wl-grid">{loading?<div className="empty">{txt('Chargement…','加载中…')}</div>:filtered.map(w=><article className={`wl-card ${!w.is_active?'off':''}`} key={w.id}><div className="wl-card-top"><div><strong>@{w.username}</strong><small>{w.display_name||w.account_type||'—'}</small></div><span className={`tier tier-${w.watch_tier}`}>{w.watch_tier}</span></div><div className="wl-meta"><span><MapPin size={14}/> {w.city||'Abidjan'}, {w.country_code||'CI'}</span><span><Eye size={14}/> {w.scan_interval_minutes} min</span></div><div className="wl-switches"><button className={w.live_monitor?'on':''} disabled={!isManager||busy===w.id} onClick={()=>void patch(w.id,{live_monitor:!w.live_monitor})}><Radio size={14}/> LIVE</button><button className={w.video_comment_monitor?'on':''} disabled={!isManager||busy===w.id} onClick={()=>void patch(w.id,{video_comment_monitor:!w.video_comment_monitor})}><Video size={14}/> Comments</button></div>{isManager&&<div className="wl-actions"><select value={w.watch_tier} onChange={e=>void patch(w.id,{watch_tier:e.target.value as 'A'|'B'|'C',scan_interval_minutes:tierMinutes[e.target.value]})}><option value="A">A · 10 min</option><option value="B">B · 30 min</option><option value="C">C · 120 min</option></select><button className={w.is_active?'danger-lite':'ok-lite'} onClick={()=>void patch(w.id,{is_active:!w.is_active})}>{w.is_active?txt('Pause','暂停'):txt('Activer','启用')}</button></div>}</article>)}</div>
  </div>
}
