import { useEffect, useState } from 'react'
import { Power, Radar, RefreshCw, ShieldCheck, UserSearch, Users } from 'lucide-react'
import { supabase } from '../lib/supabase'
import type { Lang } from '../lib/modules'
import TikTokLiveWatchPanel from './TikTokLiveWatchPanel'
import OwnerRadarAssignmentQueue from './OwnerRadarAssignmentQueue'

type Controls={id:boolean|string|number;master_enabled:boolean;auto_discovery_enabled:boolean;auto_join_enabled:boolean;auto_join_min_score:number;public_contact_enrichment_enabled:boolean;auto_lead_assignment_enabled:boolean}

export default function TikTokRadarOwnerControls({lang}:{lang:Lang}){
  const txt=(fr:string,zh:string)=>lang==='fr'?fr:zh
  const [cfg,setCfg]=useState<Controls|null>(null)
  const [busy,setBusy]=useState(false)
  const load=async()=>{if(!supabase)return;const {data}=await supabase.from('radar_worker_config').select('id,master_enabled,auto_discovery_enabled,auto_join_enabled,auto_join_min_score,public_contact_enrichment_enabled,auto_lead_assignment_enabled').limit(1).maybeSingle();if(data)setCfg(data as Controls)}
  useEffect(()=>{void load()},[])
  const patch=async(values:Partial<Controls>)=>{if(!supabase||!cfg)return;setBusy(true);const next={...cfg,...values};const {error}=await supabase.from('radar_worker_config').update(values).eq('id',cfg.id);if(!error)setCfg(next);setBusy(false)}
  if(!cfg)return <div className="radar-owner-controls"><div className="empty">{txt('Chargement des contrôles…','正在加载监控控制…')}</div></div>
  return <><TikTokLiveWatchPanel lang={lang}/><OwnerRadarAssignmentQueue lang={lang}/><div className="radar-owner-controls"><div className="roc-head"><div><span className="eyebrow">OWNER ONLY</span><h2>{txt('Contrôle du Radar','客户雷达监控控制')}</h2><p>{txt("Les employés et managers ne voient pas ces réglages.",'员工和管理层不显示这些监控设置。')}</p></div><button className="lr-refresh" onClick={()=>void load()}><RefreshCw size={16}/>{txt('Actualiser','刷新')}</button></div><div className="roc-grid"><Control icon={<Power/>} title={txt('Radar principal','监控总开关')} desc={txt('Arrête ou reprend toutes les nouvelles analyses LIVE/vidéo.','停止或恢复全部新的LIVE/视频扫描。')} on={cfg.master_enabled} disabled={busy} onToggle={()=>void patch({master_enabled:!cfg.master_enabled})}/><Control icon={<Users/>} title={txt('Attribution automatique','潜客自动分配')} desc={txt('Distribue les nouveaux prospects aux vendeurs actifs avec la charge la plus faible.','新潜客自动分给当前待处理潜客最少的在岗销售。')} on={cfg.auto_lead_assignment_enabled} disabled={busy} onToggle={()=>void patch({auto_lead_assignment_enabled:!cfg.auto_lead_assignment_enabled})}/><Control icon={<Radar/>} title={txt('Découverte automatique','自动发现账号')} desc={txt('Recherche automatiquement des comptes/vidéos auto en Côte d’Ivoire.','自动搜索科特迪瓦汽车账号和视频。')} on={cfg.auto_discovery_enabled} disabled={busy} onToggle={()=>void patch({auto_discovery_enabled:!cfg.auto_discovery_enabled})}/><Control icon={<ShieldCheck/>} title={txt('Ajout automatique haute confiance','高置信度自动入监控')} desc={txt(`Ajoute automatiquement les candidats ≥ ${cfg.auto_join_min_score}.`,`评分≥${cfg.auto_join_min_score}的高置信账号自动加入监控。`)} on={cfg.auto_join_enabled} disabled={busy} onToggle={()=>void patch({auto_join_enabled:!cfg.auto_join_enabled})}/><Control icon={<UserSearch/>} title={txt('Contact public','公开联系方式补充')} desc={txt('Pour les prospects forts, tente de lire uniquement les contacts publiquement affichés sur le profil.','对高意向潜客，仅尝试提取TikTok主页公开展示的电话/WhatsApp/邮箱。')} on={cfg.public_contact_enrichment_enabled} disabled={busy} onToggle={()=>void patch({public_contact_enrichment_enabled:!cfg.public_contact_enrichment_enabled})}/></div><div className="roc-threshold"><label>{txt("Seuil d'ajout automatique",'自动加入阈值')} <b>{cfg.auto_join_min_score}</b></label><input type="range" min={60} max={95} step={5} value={cfg.auto_join_min_score} disabled={busy} onChange={e=>void patch({auto_join_min_score:Number(e.target.value)})}/></div></div></>
}
function Control({icon,title,desc,on,disabled,onToggle}:{icon:React.ReactNode;title:string;desc:string;on:boolean;disabled:boolean;onToggle:()=>void}){return <div className={`roc-card ${on?'on':''}`}><span>{icon}</span><div><strong>{title}</strong><small>{desc}</small></div><button disabled={disabled} onClick={onToggle}>{on?'ON':'OFF'}</button></div>}
