import { useEffect, useState } from 'react'
import { AlertTriangle, CheckCircle2, Link2, Loader2, RefreshCw, Unplug, CalendarRange, DatabaseZap } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { getMyTikTokConnection, getTikTokOAuthReadiness, type TikTokConnection } from '../lib/tiktokAccounts'
import type { Lang } from '../lib/modules'
import '../live-sales-ai.css'

type Props={userId?:string;lang:Lang}
type RangePreset='month'|'lastMonth'|'30d'|'90d'|'custom'
type ContentStats={videos:number;views:number;likes:number;comments:number;shares:number;followers:number|null;accountLikes:number|null}
const emptyStats:ContentStats={videos:0,views:0,likes:0,comments:0,shares:0,followers:null,accountLikes:null}
const iso=(d:Date)=>d.toISOString().slice(0,10)
const getRange=(p:RangePreset)=>{const now=new Date();let s=new Date(now),e=new Date(now);if(p==='month'){s=new Date(now.getFullYear(),now.getMonth(),1)}else if(p==='lastMonth'){s=new Date(now.getFullYear(),now.getMonth()-1,1);e=new Date(now.getFullYear(),now.getMonth(),0)}else if(p==='30d'){s.setDate(now.getDate()-29)}else if(p==='90d'){s.setDate(now.getDate()-89)}return {start:iso(s),end:iso(e)}}
const fmt=(n:number|null)=>n==null?'—':new Intl.NumberFormat().format(n)

export default function TikTokAccountCard({userId,lang}:Props){
  const zh=lang==='zh', readiness=getTikTokOAuthReadiness(),initial=getRange('month')
  const [connection,setConnection]=useState<TikTokConnection|null>(null),[loading,setLoading]=useState(true),[syncing,setSyncing]=useState(false),[error,setError]=useState(''),[isOwner,setIsOwner]=useState(false),[profileId,setProfileId]=useState('')
  const [preset,setPreset]=useState<RangePreset>('month'),[startDate,setStartDate]=useState(initial.start),[endDate,setEndDate]=useState(initial.end),[stats,setStats]=useState<ContentStats>(emptyStats),[lastSync,setLastSync]=useState<string|null>(null)

  const loadStats=async(pid:string,s=startDate,e=endDate)=>{
    if(!supabase||!pid)return
    const from=`${s}T00:00:00.000Z`,to=`${e}T23:59:59.999Z`
    const [{data:videos,error:ve},{data:account,error:ae},{data:conn}]=await Promise.all([
      supabase.from('tiktok_videos').select('view_count,like_count,comment_count,share_count').eq('profile_id',pid).gte('create_time',from).lte('create_time',to),
      supabase.from('tiktok_account_stats').select('follower_count,likes_count,captured_at').eq('profile_id',pid).order('captured_at',{ascending:false}).limit(1).maybeSingle(),
      supabase.from('tiktok_account_connections').select('last_synced_at').eq('user_id',pid).maybeSingle()
    ])
    if(ve)throw ve;if(ae)throw ae
    const rows=videos||[]
    setStats({videos:rows.length,views:rows.reduce((a,v)=>a+Number(v.view_count||0),0),likes:rows.reduce((a,v)=>a+Number(v.like_count||0),0),comments:rows.reduce((a,v)=>a+Number(v.comment_count||0),0),shares:rows.reduce((a,v)=>a+Number(v.share_count||0),0),followers:account?.follower_count==null?null:Number(account.follower_count),accountLikes:account?.likes_count==null?null:Number(account.likes_count)})
    setLastSync(conn?.last_synced_at||null)
  }

  const load=async()=>{try{setLoading(true);setError('');if(!supabase)throw new Error('Supabase not configured');const {data:{user}}=await supabase.auth.getUser();const currentUserId=user?.id||'',pid=userId||currentUserId;if(!pid)throw new Error(zh?'未找到当前登录用户':'Utilisateur connecté introuvable');setProfileId(pid);if(currentUserId){const {data:profile}=await supabase.from('profiles').select('role').eq('id',currentUserId).maybeSingle();setIsOwner(profile?.role==='owner')}setConnection(await getMyTikTokConnection(pid));await loadStats(pid)}catch(e:any){setError(e?.message||String(e))}finally{setLoading(false)}}
  useEffect(()=>{void load()},[userId])
  useEffect(()=>{if(profileId)void loadStats(profileId,startDate,endDate).catch(e=>setError(e?.message||String(e)))},[startDate,endDate,profileId])
  const chooseRange=(p:RangePreset)=>{setPreset(p);if(p!=='custom'){const r=getRange(p);setStartDate(r.start);setEndDate(r.end)}}

  const syncContent=async()=>{try{setSyncing(true);setError('');if(!supabase)throw new Error('Supabase not configured');const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error(zh?'请先登录 Green Fast Auto':'Connectez-vous d’abord à Green Fast Auto');const base=import.meta.env.VITE_SUPABASE_URL,res=await fetch(`${base}/functions/v1/tiktok-content-sync`,{method:'POST',headers:{authorization:`Bearer ${session.access_token}`}}),body=await res.json().catch(()=>({}));if(!res.ok)throw new Error(body.error||'TikTok content sync failed');if(profileId)await loadStats(profileId,startDate,endDate)}catch(e:any){setError(e?.message||String(e))}finally{setSyncing(false)}}
  const startOAuth=async()=>{try{setLoading(true);setError('');if(!readiness.ready)throw new Error(zh?'TikTok OAuth 公共配置尚未完成':'Configuration publique TikTok OAuth incomplète');if(!supabase)throw new Error('Supabase not configured');const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error(zh?'请先登录 Green Fast Auto':'Connectez-vous d’abord à Green Fast Auto');const base=import.meta.env.VITE_SUPABASE_URL,res=await fetch(`${base}/functions/v1/tiktok-oauth-start`,{headers:{authorization:`Bearer ${session.access_token}`}}),body=await res.json();if(!res.ok||!body.url)throw new Error(body.error||'TikTok OAuth unavailable');window.location.assign(body.url)}catch(e:any){setError(e?.message||String(e));setLoading(false)}}
  const disconnect=async()=>{try{if(!isOwner)throw new Error(zh?'只有 Owner 可以断开 TikTok 连接':'Seul le Owner peut déconnecter TikTok');if(!connection)return;if(!window.confirm(zh?'确认断开该 TikTok 账号？断开后将停止同步该账号数据。':'Confirmer la déconnexion de ce compte TikTok ? La synchronisation sera arrêtée.'))return;setLoading(true);setError('');if(!supabase)throw new Error('Supabase not configured');const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error(zh?'请先登录 Green Fast Auto':'Connectez-vous d’abord à Green Fast Auto');const base=import.meta.env.VITE_SUPABASE_URL,res=await fetch(`${base}/functions/v1/tiktok-disconnect`,{method:'POST',headers:{authorization:`Bearer ${session.access_token}`,'content-type':'application/json'},body:JSON.stringify({profile_id:connection.profile_id,open_id:connection.open_id})}),body=await res.json().catch(()=>({}));if(!res.ok)throw new Error(body.error||'TikTok disconnect failed');await load()}catch(e:any){setError(e?.message||String(e));setLoading(false)}}

  const connected=connection?.token_status==='connected'
  return <section className="lsa-tiktok-account"><div><span className="lsa-eyebrow"><Link2 size={14}/> TIKTOK ACCOUNT</span><h3>{connected?(connection?.display_name||connection?.username||'TikTok'):(zh?'连接个人 TikTok 账号':'Connecter mon compte TikTok')}</h3><p>{connected?(zh?'授权账号的公开视频与账号统计可同步到 Green Fast。':'Les vidéos publiques et statistiques autorisées peuvent être synchronisées dans Green Fast.'):(zh?'使用 TikTok 官方 Login Kit 授权当前员工账号。':'Autorisez le compte employé via TikTok Login Kit.')}</p>{!connected&&!readiness.ready&&<small className="lsa-status"><AlertTriangle size={12}/> {zh?'等待 Client Key + Redirect URI':'En attente du Client Key + Redirect URI'}</small>}{error&&<small className="lsa-status"><AlertTriangle size={12}/> {error}</small>}
  {connected&&<><div className="lsa-date-range"><span className="lsa-eyebrow"><CalendarRange size={14}/> {zh?'内容统计区间':'PÉRIODE ANALYTIQUE'}</span><div className="lsa-range-presets">{([['month',zh?'本月':'Ce mois'],['lastMonth',zh?'上月':'Mois dernier'],['30d',zh?'近30天':'30 jours'],['90d',zh?'近90天':'90 jours'],['custom',zh?'自定义':'Personnalisé']] as [RangePreset,string][]).map(([k,label])=><button key={k} className={preset===k?'active':''} onClick={()=>chooseRange(k)}>{label}</button>)}</div><div className="lsa-range-inputs"><label>{zh?'开始日期':'Début'}<input type="date" value={startDate} max={endDate} onChange={e=>{setPreset('custom');setStartDate(e.target.value)}}/></label><span>→</span><label>{zh?'截止日期':'Fin'}<input type="date" value={endDate} min={startDate} max={iso(new Date())} onChange={e=>{setPreset('custom');setEndDate(e.target.value)}}/></label></div><small>{zh?`当前统计：${startDate} 至 ${endDate}`:`Analyse actuelle : ${startDate} au ${endDate}`}</small></div>
  <div className="lsa-content-metrics"><div><b>{fmt(stats.videos)}</b><span>{zh?'视频':'Vidéos'}</span></div><div><b>{fmt(stats.views)}</b><span>{zh?'播放':'Vues'}</span></div><div><b>{fmt(stats.likes)}</b><span>{zh?'点赞':'Likes'}</span></div><div><b>{fmt(stats.comments)}</b><span>{zh?'评论':'Commentaires'}</span></div><div><b>{fmt(stats.shares)}</b><span>{zh?'分享':'Partages'}</span></div><div><b>{fmt(stats.followers)}</b><span>{zh?'当前粉丝':'Abonnés actuels'}</span></div></div>{lastSync&&<small>{zh?'最近同步':'Dernière synchro'}: {new Date(lastSync).toLocaleString()}</small>}</>}</div>
  {connected?<div className="lsa-tiktok-actions"><div className="lsa-connected"><CheckCircle2 size={18}/><b>{zh?'已连接':'CONNECTÉ'}</b></div><button className="lsa-live" onClick={()=>void syncContent()} disabled={syncing||loading}>{syncing?<Loader2 size={16}/>:<DatabaseZap size={16}/>} {zh?'同步 TikTok 数据':'SYNCHRONISER'}</button><button className="lsa-secondary" onClick={()=>void startOAuth()} disabled={loading||!readiness.ready}>{loading?<Loader2 size={16}/>:<RefreshCw size={16}/>} {zh?'重新授权':'RÉAUTORISER'}</button>{isOwner&&<button className="lsa-secondary" onClick={()=>void disconnect()} disabled={loading}><Unplug size={16}/> {zh?'断开连接':'DÉCONNECTER'}</button>}</div>:<button className="lsa-live" onClick={()=>void startOAuth()} disabled={loading||!readiness.ready}>{loading?<Loader2 size={16}/>:<Link2 size={16}/>} {readiness.ready?(zh?'连接 TikTok':'CONNECTER TIKTOK'):(zh?'OAuth 未配置':'OAUTH NON CONFIGURÉ')}</button>}</section>
}
