import { useEffect, useMemo, useState } from 'react'
import { ArrowRight, BadgeCheck, CircleUserRound, Flame, MessageCircle, Radio, RefreshCw, Search, UserPlus, Video } from 'lucide-react'
import { supabase } from '../lib/supabase'
import type { Lang, Role } from '../lib/modules'
import './TikTokLeadRadar.css'

type LeadStatus='new'|'high_intent'|'assigned'|'contact_attempted'|'replied'|'contact_captured'|'converted'|'invalid'
type SocialLead={id:string;username:string;display_name:string|null;source_type:'live'|'video_comment';source_account:string|null;source_url:string|null;original_text:string;interested_model:string|null;intent_label:string|null;intent_score:number;occurrence_count:number;last_seen_at:string;status:LeadStatus;assigned_to:string|null;notes:string|null}
type Profile={id:string;full_name:string|null;role:string}

const statusCopy:Record<LeadStatus,{fr:string;zh:string}>={new:{fr:'Nouveau',zh:'新发现'},high_intent:{fr:'Intention forte',zh:'高意向'},assigned:{fr:'Assigné',zh:'已分配'},contact_attempted:{fr:'Contact tenté',zh:'已尝试联系'},replied:{fr:'A répondu',zh:'已回复'},contact_captured:{fr:'Contact obtenu',zh:'已取得联系方式'},converted:{fr:'Converti CRM',zh:'已转正式CRM'},invalid:{fr:'Invalide',zh:'无效'}}
const statusFlow:LeadStatus[]=['new','high_intent','assigned','contact_attempted','replied','contact_captured','converted']
const fmt=(v:string)=>new Intl.DateTimeFormat('fr-FR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(v))

export default function TikTokLeadRadar({lang,role,userId,onOpenCrm}:{lang:Lang;role:Role;userId:string;onOpenCrm:()=>void}){
  const [leads,setLeads]=useState<SocialLead[]>([]),[profiles,setProfiles]=useState<Profile[]>([]),[loading,setLoading]=useState(true),[q,setQ]=useState(''),[filter,setFilter]=useState<'all'|LeadStatus>('all'),[selected,setSelected]=useState<SocialLead|null>(null),[busy,setBusy]=useState(false),[phone,setPhone]=useState(''),[whatsapp,setWhatsapp]=useState('')
  const isManager=role==='owner'||role==='manager'
  const load=async()=>{if(!supabase)return;setLoading(true);const leadQ=supabase.from('social_leads').select('*').order('intent_score',{ascending:false}).order('last_seen_at',{ascending:false}).limit(300);const [{data:leadData},{data:profileData}]=await Promise.all([leadQ,supabase.from('profiles').select('id,full_name,role').in('role',['sales','manager'])]);setLeads((leadData||[]) as SocialLead[]);setProfiles((profileData||[]) as Profile[]);setLoading(false)}
  useEffect(()=>{void load()},[])
  const visible=useMemo(()=>leads.filter(l=>(filter==='all'||l.status===filter)&&(!q||`${l.username} ${l.display_name||''} ${l.original_text} ${l.interested_model||''}`.toLowerCase().includes(q.toLowerCase()))),[leads,q,filter])
  const metrics=useMemo(()=>({all:leads.length,hot:leads.filter(x=>x.intent_score>=80&&x.status!=='converted'&&x.status!=='invalid').length,replied:leads.filter(x=>['replied','contact_captured'].includes(x.status)).length,captured:leads.filter(x=>x.status==='contact_captured').length,converted:leads.filter(x=>x.status==='converted').length}),[leads])
  const update=async(id:string,patch:Partial<SocialLead>)=>{if(!supabase)return;setBusy(true);const {error}=await supabase.from('social_leads').update(patch).eq('id',id);setBusy(false);if(!error){setLeads(prev=>prev.map(x=>x.id===id?{...x,...patch}:x));setSelected(prev=>prev?.id===id?{...prev,...patch}:prev)}}
  const assign=async(lead:SocialLead,to:string)=>{await update(lead.id,{assigned_to:to,status:'assigned'})}
  const advance=async(lead:SocialLead)=>{const i=statusFlow.indexOf(lead.status);if(i<0||i>=statusFlow.length-2)return;await update(lead.id,{status:statusFlow[i+1]})}
  const convert=async(lead:SocialLead)=>{if(!supabase||(!phone.trim()&&!whatsapp.trim()))return;setBusy(true);const {data,error}=await supabase.from('customers').insert({full_name:lead.display_name||`@${lead.username}`,phone:phone.trim()||null,whatsapp:whatsapp.trim()||null,lead_source:'tiktok',interested_model:lead.interested_model,assigned_to:lead.assigned_to||userId,stage:'new',notes:`TikTok Lead Radar\n@${lead.username}\n${lead.source_type}: ${lead.source_account||''}\nOriginal: ${lead.original_text}`}).select('id').single();if(!error&&data){await supabase.from('social_leads').update({status:'converted',converted_customer_id:data.id}).eq('id',lead.id);setPhone('');setWhatsapp('');setSelected({...lead,status:'converted'});await load()}setBusy(false)}
  const txt=(fr:string,zh:string)=>lang==='fr'?fr:zh
  return <section className="lead-radar">
    <div className="lr-head"><div><span className="eyebrow">TIKTOK LEAD RADAR · V0.1</span><h1>{txt('Radar de prospects sociaux','TikTok 客户雷达')}</h1><p>{txt("Détecte les comptes publics à intention d'achat. Ils restent hors CRM tant qu'aucun téléphone/WhatsApp n'est obtenu.",'识别公开购车意向账号；没有电话/WhatsApp前，不进入正式CRM。')}</p></div><button className="lr-refresh" onClick={()=>void load()}><RefreshCw size={17}/>{txt('Actualiser','刷新')}</button></div>
    <div className="lr-metrics"><Metric icon={<Radio/>} n={metrics.all} label={txt('Prospects détectés','发现潜客')}/><Metric icon={<Flame/>} n={metrics.hot} label={txt('Intentions fortes','高意向')}/><Metric icon={<MessageCircle/>} n={metrics.replied} label={txt('Réponses','已回复')}/><Metric icon={<BadgeCheck/>} n={metrics.captured} label={txt('Contacts obtenus','取得联系方式')}/><Metric icon={<ArrowRight/>} n={metrics.converted} label={txt('Convertis CRM','已转CRM')}/></div>
    <div className="lr-toolbar"><div className="lr-search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={txt('Rechercher compte, commentaire, modèle…','搜索账号、评论、车型…')}/></div><select value={filter} onChange={e=>setFilter(e.target.value as any)}><option value="all">{txt('Tous les statuts','全部状态')}</option>{Object.entries(statusCopy).map(([k,v])=><option key={k} value={k}>{v[lang]}</option>)}</select></div>
    <div className="lr-table-wrap"><table className="lr-table"><thead><tr><th>{txt('Compte','账号')}</th><th>{txt('Source','来源')}</th><th>{txt('Signal détecté','原始意向')}</th><th>{txt('Modèle','车型')}</th><th>{txt('Score AI','AI评分')}</th><th>{txt('Statut','状态')}</th><th></th></tr></thead><tbody>{loading?<tr><td colSpan={7} className="empty">{txt('Chargement…','加载中…')}</td></tr>:visible.length===0?<tr><td colSpan={7} className="empty">{txt('Aucun prospect pour ce filtre.','当前筛选暂无潜客。')}</td></tr>:visible.map(l=><tr key={l.id} className={l.intent_score>=80?'hot-row':''}><td><div className="account"><CircleUserRound size={28}/><div><strong>@{l.username}</strong><small>{l.display_name||'—'} · ×{l.occurrence_count}</small></div></div></td><td><span className="source">{l.source_type==='live'?<Radio size={14}/>:<Video size={14}/>} {l.source_account||txt('TikTok public','TikTok公开内容')}</span><small>{fmt(l.last_seen_at)}</small></td><td className="quote">“{l.original_text}”<small>{l.intent_label||''}</small></td><td>{l.interested_model||'—'}</td><td><span className={`score s${Math.floor(l.intent_score/20)}`}>{l.intent_score}</span></td><td><span className={`status ${l.status}`}>{statusCopy[l.status][lang]}</span></td><td><button className="ghost" onClick={()=>{setSelected(l);setPhone('');setWhatsapp('')}}>{txt('Ouvrir','打开')}</button></td></tr>)}</tbody></table></div>
    {selected&&<div className="lr-drawer-back" onClick={()=>setSelected(null)}><aside className="lr-drawer" onClick={e=>e.stopPropagation()}><button className="drawer-close" onClick={()=>setSelected(null)}>×</button><span className="eyebrow">@{selected.username}</span><h2>{selected.display_name||selected.username}</h2><div className="intent-card"><strong>{txt('Signal public détecté','识别到的公开意向')}</strong><p>“{selected.original_text}”</p><div><span>{txt('Score','评分')} <b>{selected.intent_score}/100</b></span><span>{selected.interested_model||txt('Modèle inconnu','车型未知')}</span></div></div>
      <label>{txt('Statut','状态')}<select value={selected.status} onChange={e=>void update(selected.id,{status:e.target.value as LeadStatus})}>{Object.entries(statusCopy).map(([k,v])=><option key={k} value={k}>{v[lang]}</option>)}</select></label>
      {isManager&&<label>{txt('Assigner à','分配给销售')}<select value={selected.assigned_to||''} onChange={e=>void assign(selected,e.target.value)}><option value="">{txt('Non assigné','未分配')}</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.full_name||p.id}</option>)}</select></label>}
      {!isManager&&!selected.assigned_to&&<button className="primary-action" disabled={busy} onClick={()=>void assign(selected,userId)}><UserPlus size={17}/>{txt('Prendre ce prospect','领取这个潜客')}</button>}
      {!['contact_captured','converted','invalid'].includes(selected.status)&&<button className="secondary-action" disabled={busy} onClick={()=>void advance(selected)}>{txt('Passer à l’étape suivante','推进到下一状态')} <ArrowRight size={16}/></button>}
      {selected.status==='contact_captured'&&<div className="convert-box"><h3>{txt('Convertir en client CRM','转为正式CRM客户')}</h3><p>{txt('Un téléphone ou WhatsApp est obligatoire.','必须已经取得电话或WhatsApp。')}</p><input placeholder={txt('Téléphone','电话')} value={phone} onChange={e=>setPhone(e.target.value)}/><input placeholder="WhatsApp" value={whatsapp} onChange={e=>setWhatsapp(e.target.value)}/><button className="convert" disabled={busy||(!phone.trim()&&!whatsapp.trim())} onClick={()=>void convert(selected)}>{txt('Créer le client dans le CRM','创建正式CRM客户')}</button></div>}
      {selected.status==='converted'&&<button className="primary-action" onClick={onOpenCrm}><BadgeCheck size={17}/>{txt('Ouvrir le CRM','打开正式CRM')}</button>}
    </aside></div>}
  </section>
}
function Metric({icon,n,label}:{icon:React.ReactNode;n:number;label:string}){return <div className="lr-metric"><span>{icon}</span><div><strong>{n}</strong><small>{label}</small></div></div>}
