import { useEffect, useMemo, useState } from 'react'
import { BadgeCheck, Eye, MapPin, Plus, RefreshCw, Radio, Search, Sparkles, Video, X } from 'lucide-react'
import { supabase } from '../lib/supabase'
import type { Lang, Role } from '../lib/modules'
import TikTokWatcherHealth from './TikTokWatcherHealth'

type Watch={id:string;username:string;display_name:string|null;country_code:string|null;city:string|null;account_type:string|null;priority:number|null;watch_tier:'A'|'B'|'C';live_monitor:boolean;video_comment_monitor:boolean;scan_interval_minutes:number;is_active:boolean;last_scan_at:string|null}
type Suggestion={id:string;username:string;display_name:string|null;country_code:string;city:string|null;account_type:string|null;geo_score:number;auto_relevance_score:number;purchase_signal_count:number;live_signal_count:number;video_signal_count:number;suggested_priority:number;suggested_tier:'A'|'B'|'C';status:'suggested'|'approved'|'rejected'}

const tierMinutes:{[k:string]:number}={A:10,B:30,C:120}
export default function TikTokWatchlistPanel({lang,role,userId}:{lang:Lang;role:Role;userId:string}){
  const txt=(fr:string,zh:string)=>lang==='fr'?fr:zh
  const isManager=role==='owner'||role==='manager'
  const [watch,setWatch]=useState<Watch[]>([]),[suggestions,setSuggestions]=useState<Suggestion[]>([]),[loading,setLoading]=useState(true),[q,setQ]=useState(''),[busy,setBusy]=useState('')
  const [username,setUsername]=useState(''),[displayName,setDisplayName]=useState(''),[accountType,setAccountType]=useState('dealer'),[tier,setTier]=useState<'A'|'B'|'C'>('B')
  const load=async()=>{if(!supabase)return;setLoading(true);const [{data:w},{data:s}]=await Promise.all([supabase.from('tiktok_watchlist').select('*').order('priority',{ascending:false}),isManager?supabase.from('tiktok_watchlist_suggestions').select('*').eq('status','suggested').order('suggested_priority',{ascending:false}):Promise.resolve({data:[] as any[]})]);setWatch((w||[]) as Watch[]);setSuggestions((s||[]) as Suggestion[]);setLoading(false)}
  useEffect(()=>{void load()},[])
  const filtered=useMemo(()=>watch.filter(x=>!q||`${x.username} ${x.display_name||''} ${x.account_type||''}`.toLowerCase().includes(q.toLowerCase())),[watch,q])
  const add=async()=>{if(!supabase||!username.trim())return;setBusy('add');await supabase.from('tiktok_watchlist').insert({username:username.trim().replace(/^@/,''),display_name:displayName.trim()||null,account_type:accountType,country_code:'CI',city:'Abidjan',market_scope:'abidjan_auto',priority:tier==='A'?90:tier==='B'?70:50,watch_tier:tier,scan_interval_minutes:tierMinutes[tier],created_by:userId});setUsername('');setDisplayName('');setBusy('');await load()}
  const patch=async(id:string,values:Partial<Watch>)=>{if(!supabase)return;setBusy(id);await supabase.from('tiktok_watchlist').update(values).eq('id',id);setBusy('');await load()}
  const approve=async(s:Suggestion)=>{if(!supabase)return;setBusy(s.id);const {data}=await supabase.from('tiktok_watchlist').upsert({username:s.username,display_name:s.display_name,account_type:s.account_type||'auto',country_code:'CI',city:s.city||'Abidjan',market_scope:'abidjan_auto',priority:s.suggested_priority,watch_tier:s.suggested_tier,scan_interval_minutes:tierMinutes[s.suggested_tier],created_by:userId},{onConflict:'username'}).select('id').single();if(data)await supabase.from('tiktok_watchlist_suggestions').update({status:'approved',approved_watchlist_id:data.id,reviewed_by:userId}).eq('id',s.id);setBusy('');await load()}
  const reject=async(id:string)=>{if(!supabase)return;setBusy(id);await supabase.from('tiktok_watchlist_suggestions').update({status:'rejected',reviewed_by:userId}).eq('id',id);setBusy('');await load()}
  return <div className="wl-panel">
    <TikTokWatcherHealth lang={lang} role={role}/>
    <div className="wl-head"><div><span className="eyebrow">ABIDJAN AUTO WATCHLIST</span><h2>{txt('Comptes TikTok surveillés','TikTok 监控账号')}</h2><p>{txt("Priorité aux concessionnaires, importateurs, blogueurs auto et vidéos automobiles de Côte d’Ivoire.",'优先监控科特迪瓦经销商、进口商、汽车博主及汽车相关视频账号。')}</p></div><button className="lr-refresh" onClick={()=>void load()}><RefreshCw size={16}/>{txt('Actualiser','刷新')}</button></div>
    <div className="wl-summary"><div><b>{watch.filter(x=>x.is_active).length}</b><span>{txt('Actifs','启用监控')}</span></div><div><b>{watch.filter(x=>x.watch_tier==='A'&&x.is_active).length}</b><span>{txt('Tier A','A级高频')}</span></div><div><b>{watch.filter(x=>x.live_monitor&&x.is_active).length}</b><span>{txt('LIVE','直播监控')}</span></div><div><b>{watch.filter(x=>x.video_comment_monitor&&x.is_active).length}</b><span>{txt('Commentaires vidéo','视频评论')}</span></div><div><b>{suggestions.length}</b><span>{txt('Suggestions AI','AI建议账号')}</span></div></div>
    {isManager&&<div className="wl-add"><input placeholder="@compte" value={username} onChange={e=>setUsername(e.target.value)}/><input placeholder={txt('Nom affiché','显示名称')} value={displayName} onChange={e=>setDisplayName(e.target.value)}/><select value={accountType} onChange={e=>setAccountType(e.target.value)}><option value="dealer">Dealer</option><option value="importer">Importer</option><option value="blogger">Blogger</option><option value="media">Auto media</option><option value="marketplace">Marketplace</option></select><select value={tier} onChange={e=>setTier(e.target.value as any)}><option value="A">A · 10 min</option><option value="B">B · 30 min</option><option value="C">C · 120 min</option></select><button className="primary-action" disabled={busy==='add'||!username.trim()} onClick={()=>void add()}><Plus size={16}/>{txt('Ajouter','加入监控')}</button></div>}
    <div className="lr-search wl-search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={txt('Rechercher un compte…','搜索监控账号…')}/></div>
    <div className="wl-grid">{loading?<div className="empty">{txt('Chargement…','加载中…')}</div>:filtered.map(w=><article className={`wl-card ${!w.is_active?'off':''}`} key={w.id}><div className="wl-card-top"><div><strong>@{w.username}</strong><small>{w.display_name||w.account_type||'—'}</small></div><span className={`tier tier-${w.watch_tier}`}>{w.watch_tier}</span></div><div className="wl-meta"><span><MapPin size={14}/> {w.city||'Abidjan'}, {w.country_code||'CI'}</span><span><Eye size={14}/> {w.scan_interval_minutes} min</span></div><div className="wl-switches"><button className={w.live_monitor?'on':''} disabled={!isManager||busy===w.id} onClick={()=>void patch(w.id,{live_monitor:!w.live_monitor})}><Radio size={14}/> LIVE</button><button className={w.video_comment_monitor?'on':''} disabled={!isManager||busy===w.id} onClick={()=>void patch(w.id,{video_comment_monitor:!w.video_comment_monitor})}><Video size={14}/> Comments</button></div>{isManager&&<div className="wl-actions"><select value={w.watch_tier} onChange={e=>void patch(w.id,{watch_tier:e.target.value as any,scan_interval_minutes:tierMinutes[e.target.value]})}><option value="A">A · 10 min</option><option value="B">B · 30 min</option><option value="C">C · 120 min</option></select><button className={w.is_active?'danger-lite':'ok-lite'} onClick={()=>void patch(w.id,{is_active:!w.is_active})}>{w.is_active?txt('Pause','暂停'):txt('Activer','启用')}</button></div>}</article>)}</div>
    {isManager&&<div className="wl-suggest"><div className="wl-suggest-title"><Sparkles size={18}/><div><h3>{txt('Suggested Watchlist','建议监控账号')}</h3><p>{txt("Comptes auto ivoiriens découverts par le système; validation humaine avant surveillance.",'系统发现的科特迪瓦汽车账号；加入监控前由经理确认。')}</p></div></div>{suggestions.length===0?<div className="empty">{txt('Aucune suggestion pour le moment.','目前暂无建议账号。')}</div>:suggestions.map(s=><div className="suggest-row" key={s.id}><div><strong>@{s.username}</strong><small>{s.display_name||s.account_type||'—'} · {s.city||'Abidjan'}</small></div><div className="suggest-score"><span>Geo <b>{s.geo_score}</b></span><span>Auto <b>{s.auto_relevance_score}</b></span><span>Signals <b>{s.purchase_signal_count}</b></span><span className={`tier tier-${s.suggested_tier}`}>{s.suggested_tier}</span></div><div className="suggest-actions"><button className="approve" disabled={busy===s.id} onClick={()=>void approve(s)}><BadgeCheck size={15}/>{txt('Ajouter','加入')}</button><button className="reject" disabled={busy===s.id} onClick={()=>void reject(s.id)}><X size={15}/>{txt('Ignorer','忽略')}</button></div></div>)}</div>}
  </div>
}
