import { useEffect, useState } from 'react'
import { AlertTriangle, CheckCircle2, Link2, Loader2, RefreshCw, Unplug, CalendarRange } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { getMyTikTokConnection, getTikTokOAuthReadiness, type TikTokConnection } from '../lib/tiktokAccounts'
import type { Lang } from '../lib/modules'
import '../live-sales-ai.css'

type Props={userId?:string;lang:Lang}
type RangePreset='month'|'lastMonth'|'30d'|'90d'|'custom'
const iso=(d:Date)=>d.toISOString().slice(0,10)
const getRange=(p:RangePreset)=>{const now=new Date();let s=new Date(now),e=new Date(now);if(p==='month'){s=new Date(now.getFullYear(),now.getMonth(),1)}else if(p==='lastMonth'){s=new Date(now.getFullYear(),now.getMonth()-1,1);e=new Date(now.getFullYear(),now.getMonth(),0)}else if(p==='30d'){s.setDate(now.getDate()-29)}else if(p==='90d'){s.setDate(now.getDate()-89)}return {start:iso(s),end:iso(e)}}

export default function TikTokAccountCard({userId,lang}:Props){
  const zh=lang==='zh', readiness=getTikTokOAuthReadiness()
  const initial=getRange('month')
  const [connection,setConnection]=useState<TikTokConnection|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[isOwner,setIsOwner]=useState(false)
  const [preset,setPreset]=useState<RangePreset>('month'),[startDate,setStartDate]=useState(initial.start),[endDate,setEndDate]=useState(initial.end)

  const load=async()=>{try{setLoading(true);setError('');if(!supabase)throw new Error('Supabase not configured');const {data:{user}}=await supabase.auth.getUser();const currentUserId=user?.id||'',profileId=userId||currentUserId;if(!profileId)throw new Error(zh?'未找到当前登录用户':'Utilisateur connecté introuvable');if(currentUserId){const {data:profile}=await supabase.from('profiles').select('role').eq('id',currentUserId).maybeSingle();setIsOwner(profile?.role==='owner')}setConnection(await getMyTikTokConnection(profileId))}catch(e:any){setError(e?.message||String(e))}finally{setLoading(false)}}
  useEffect(()=>{void load()},[userId])
  const chooseRange=(p:RangePreset)=>{setPreset(p);if(p!=='custom'){const r=getRange(p);setStartDate(r.start);setEndDate(r.end)}}

  const startOAuth=async()=>{try{setLoading(true);setError('');if(!readiness.ready)throw new Error(zh?'TikTok OAuth 公共配置尚未完成':'Configuration publique TikTok OAuth incomplète');if(!supabase)throw new Error('Supabase not configured');const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error(zh?'请先登录 Green Fast Auto':'Connectez-vous d’abord à Green Fast Auto');const base=import.meta.env.VITE_SUPABASE_URL,res=await fetch(`${base}/functions/v1/tiktok-oauth-start`,{headers:{authorization:`Bearer ${session.access_token}`}}),body=await res.json();if(!res.ok||!body.url)throw new Error(body.error||'TikTok OAuth unavailable');window.location.assign(body.url)}catch(e:any){setError(e?.message||String(e));setLoading(false)}}
  const disconnect=async()=>{try{if(!isOwner)throw new Error(zh?'只有 Owner 可以断开 TikTok 连接':'Seul le Owner peut déconnecter TikTok');if(!connection)return;if(!window.confirm(zh?'确认断开该 TikTok 账号？断开后将停止同步该账号数据。':'Confirmer la déconnexion de ce compte TikTok ? La synchronisation sera arrêtée.'))return;setLoading(true);setError('');if(!supabase)throw new Error('Supabase not configured');const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error(zh?'请先登录 Green Fast Auto':'Connectez-vous d’abord à Green Fast Auto');const base=import.meta.env.VITE_SUPABASE_URL,res=await fetch(`${base}/functions/v1/tiktok-disconnect`,{method:'POST',headers:{authorization:`Bearer ${session.access_token}`,'content-type':'application/json'},body:JSON.stringify({profile_id:connection.profile_id,open_id:connection.open_id})}),body=await res.json().catch(()=>({}));if(!res.ok)throw new Error(body.error||'TikTok disconnect failed');await load()}catch(e:any){setError(e?.message||String(e));setLoading(false)}}

  const connected=connection?.token_status==='connected'
  return <section className="lsa-tiktok-account"><div><span className="lsa-eyebrow"><Link2 size={14}/> TIKTOK ACCOUNT</span><h3>{connected?(connection?.display_name||connection?.username||'TikTok'):(zh?'连接个人 TikTok 账号':'Connecter mon compte TikTok')}</h3><p>{connected?(zh?'该员工的 LIVE Session 与内容数据将绑定到此 TikTok 身份。':'Les sessions LIVE et les données de contenu seront liées à cette identité TikTok.'):(zh?'使用 TikTok 官方 Login Kit 授权当前员工账号。':'Autorisez le compte employé via TikTok Login Kit.')}</p>{!connected&&!readiness.ready&&<small className="lsa-status"><AlertTriangle size={12}/> {zh?'等待 Client Key + Redirect URI':'En attente du Client Key + Redirect URI'}</small>}{error&&<small className="lsa-status">{error}</small>}
  {connected&&<div className="lsa-date-range"><span className="lsa-eyebrow"><CalendarRange size={14}/> {zh?'内容统计区间':'PÉRIODE ANALYTIQUE'}</span><div className="lsa-range-presets">{([['month',zh?'本月':'Ce mois'],['lastMonth',zh?'上月':'Mois dernier'],['30d',zh?'近30天':'30 jours'],['90d',zh?'近90天':'90 jours'],['custom',zh?'自定义':'Personnalisé']] as [RangePreset,string][]).map(([k,label])=><button key={k} className={preset===k?'active':''} onClick={()=>chooseRange(k)}>{label}</button>)}</div><div className="lsa-range-inputs"><label>{zh?'开始日期':'Début'}<input type="date" value={startDate} max={endDate} onChange={e=>{setPreset('custom');setStartDate(e.target.value)}}/></label><span>→</span><label>{zh?'截止日期':'Fin'}<input type="date" value={endDate} min={startDate} max={iso(new Date())} onChange={e=>{setPreset('custom');setEndDate(e.target.value)}}/></label></div><small>{zh?`当前统计：${startDate} 至 ${endDate}`:`Analyse actuelle : ${startDate} au ${endDate}`}</small></div>}</div>
  {connected?<div className="lsa-tiktok-actions"><div className="lsa-connected"><CheckCircle2 size={18}/><b>{zh?'已连接':'CONNECTÉ'}</b></div><button className="lsa-live" onClick={()=>void startOAuth()} disabled={loading||!readiness.ready}>{loading?<Loader2 size={16}/>:<RefreshCw size={16}/>} {zh?'重新授权':'RÉAUTORISER'}</button>{isOwner&&<button className="lsa-secondary" onClick={()=>void disconnect()} disabled={loading}><Unplug size={16}/> {zh?'断开连接':'DÉCONNECTER'}</button>}</div>:<button className="lsa-live" onClick={()=>void startOAuth()} disabled={loading||!readiness.ready}>{loading?<Loader2 size={16}/>:<Link2 size={16}/>} {readiness.ready?(zh?'连接 TikTok':'CONNECTER TIKTOK'):(zh?'OAuth 未配置':'OAUTH NON CONFIGURÉ')}</button>}</section>
}
