import {useMemo,useState} from 'react'
import {Check,ScanSearch,Sparkles} from 'lucide-react'
import {supabase} from '../lib/supabase'
import type{Lang}from'../lib/modules'
import{parseSpecs,specGroups,vehicleSpecs,type SpecMap}from'../lib/vehicleSpecs'

type Props={lang:Lang;photos:string[];initial:unknown;onApply:(specs:SpecMap,fields:Record<string,unknown>)=>void}
export default function VehicleAiIntake({lang,photos,initial,onApply}:Props){const[specs,setSpecs]=useState<SpecMap>(parseSpecs(initial)),[fields,setFields]=useState<Record<string,unknown>>({}),[busy,setBusy]=useState(false),[error,setError]=useState('');const groups=useMemo(()=>specGroups.map(g=>[g,vehicleSpecs.filter(s=>s.group===g[0]) ] as const),[])
 const recognize=async()=>{if(!supabase||!photos.length)return;setBusy(true);setError('');const{data,error}=await supabase.functions.invoke('recognize-vehicle-config',{body:{image_urls:photos.slice(0,16)}});setBusy(false);if(error||data?.error){setError(error?.message||data?.error||'AI error');return}setSpecs(data.specs||{});setFields(data.vehicle_fields||{})}
 const setValue=(key:string,value:string)=>setSpecs(s=>({...s,[key]:{...(s[key]||{}),value,source:'manual',confidence:1,confirmed:true,public:s[key]?.public!==false}}));const toggle=(key:string,part:'confirmed'|'public')=>setSpecs(s=>({...s,[key]:{...(s[key]||{value:''}),[part]:!s[key]?.[part]}}))
 return <section className="card" style={{marginTop:18,padding:18}}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center'}}><div><b>{lang==='fr'?'Dossier AI du véhicule':'AI 一次建档 · 配置识别'}</b><p style={{margin:'5px 0',fontSize:11,opacity:.65}}>{lang==='fr'?'Analyse les photos/configurations puis vous laisse confirmer chaque donnée.':'上传图片后自动识别车辆和配置；低置信度项目必须人工确认后才公开。'}</p></div><button type="button" className="secondary" disabled={busy||!photos.length} onClick={()=>void recognize()}><ScanSearch size={15}/>{busy?(lang==='fr'?'Analyse…':'识别中…'):(lang==='fr'?'Reconnaître':'AI识别车辆+配置')}</button></div>{error&&<div className="error-banner">{error}</div>}<div style={{display:'grid',gap:12,marginTop:12}}>{groups.map(([g,items])=>{const visible=items.filter(i=>specs[i.key]?.value!==undefined&&specs[i.key]?.value!=='');if(!visible.length)return null;return <div key={g[0]} style={{border:'1px solid #e4e9e6',borderRadius:12,padding:12}}><b>{lang==='fr'?g[2]:g[1]}</b><div className="detail-grid" style={{marginTop:8}}>{visible.map(i=>{const x=specs[i.key];const low=(x.confidence??1)<.8&&!x.confirmed;return <div key={i.key} style={low?{background:'#fff7df'}:{}}><small>{lang==='fr'?i.fr:i.zh} · {x.source==='ai'?'AI':'MANUAL'} {x.confidence!=null?Math.round(x.confidence*100)+'%':''}</small><input value={String(x.value??'')} onChange={e=>setValue(i.key,e.target.value)} style={{width:'100%'}}/><span style={{display:'flex',gap:6,marginTop:5}}><button type="button" className="secondary" onClick={()=>toggle(i.key,'confirmed')}><Check size={12}/>{x.confirmed?(lang==='fr'?'Confirmé':'已确认'):(lang==='fr'?'Confirmer':'确认')}</button><button type="button" className="secondary" onClick={()=>toggle(i.key,'public')}>{x.public===false?(lang==='fr'?'Interne':'不公开'):(lang==='fr'?'Public':'前端展示')}</button></span></div>})}</div></div>})}</div>{Object.keys(specs).length>0&&<button type="button" className="primary" style={{marginTop:12}} onClick={()=>onApply(specs,fields)}><Sparkles size={15}/>{lang==='fr'?'Appliquer au dossier':'应用识别结果到车辆档案'}</button>}</section>}
