import { useEffect, useMemo, useState } from 'react'
import type { Session } from '@supabase/supabase-js'
import { ArrowRight, Bell, CalendarDays, CarFront, Check, ChevronDown, CircleDollarSign, ClipboardCheck, Clock3, FileText, Gauge, Headphones, LayoutDashboard, LogOut, Menu, MoreHorizontal, PackageCheck, Search, Sparkles, Target, TrendingUp, UserRound, UsersRound, WalletCards, X } from 'lucide-react'
import { isSupabaseReady, supabase } from './lib/supabase'

type Role='owner'|'manager'|'sales'|'finance'|'delivery'
type Lang='fr'|'zh'
const roles:Role[]=['owner','manager','sales','finance','delivery']
const allNav=[['dashboard',LayoutDashboard],['inventory',CarFront],['crm',UsersRound],['tasks',Target],['content',FileText],['pricing',CircleDollarSign],['orders',WalletCards],['payments',TrendingUp],['payroll',Gauge],['delivery',PackageCheck],['afterSales',Headphones]] as const
const access:Record<Role,string[]>={owner:allNav.map(x=>x[0]),manager:allNav.map(x=>x[0]),sales:['dashboard','inventory','crm','tasks','content','orders','delivery','afterSales'],finance:['dashboard','pricing','orders','payments','payroll'],delivery:['dashboard','inventory','tasks','delivery','afterSales']}
const copy={
 fr:{welcome:'Bonjour, Amélie',today:"Voici ce qui se passe aujourd’hui.",search:'Rechercher un véhicule, client...',week:'Cette semaine',performance:'Performance commerciale',seeReport:'Voir le rapport',stock:'Véhicules en stock',leads:'Nouveaux prospects',sales:'Ventes conclues',revenue:"Chiffre d’affaires",tasks:'Tâches prioritaires',seeAll:'Voir tout',pipeline:'Pipeline des ventes',recent:'Véhicules récents',viewInventory:"Voir l’inventaire",content:'Attribution contenu → ventes',signout:'Se déconnecter',configure:'Connexion Supabase à configurer',quick:'Action rapide',newLead:'Nouveau prospect',newVehicle:'Ajouter véhicule',role:'Rôle'},
 zh:{welcome:'你好，Amélie',today:'这是今天的业务概览。',search:'搜索车辆、客户...',week:'本周',performance:'销售业绩',seeReport:'查看报告',stock:'库存车辆',leads:'新潜在客户',sales:'已完成销售',revenue:'营业额',tasks:'优先任务',seeAll:'查看全部',pipeline:'销售管道',recent:'最近车辆',viewInventory:'查看库存',content:'内容 → 销售归因',signout:'退出登录',configure:'请配置 Supabase 连接',quick:'快捷操作',newLead:'新潜在客户',newVehicle:'添加车辆',role:'角色'}
}
const navFr:Record<string,string>={dashboard:'Tableau de bord',inventory:'Parc véhicules',crm:'CRM & Prospects',tasks:'Tâches & KPI',content:'Suivi du contenu',pricing:'Validation des prix',orders:'Ventes & Commandes',payments:'Paiements',payroll:'Commissions & Paie',delivery:'Inspection & Livraison',afterSales:'Service après-vente'}
const navZh:Record<string,string>={dashboard:'仪表板',inventory:'车辆库存',crm:'客户管理',tasks:'任务与 KPI',content:'内容跟踪',pricing:'价格审批',orders:'销售与订单',payments:'付款',payroll:'佣金与工资',delivery:'验车与交付',afterSales:'售后服务'}
const money=(n:number)=>new Intl.NumberFormat('fr-FR').format(n)+' FCFA'

function Login(){const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[error,setError]=useState('');const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!supabase){setError('Ajoutez les variables Supabase dans Vercel.');return}const {error}=await supabase.auth.signInWithPassword({email,password});setError(error?.message||'')};return <main className="login"><div className="login-card"><Brand/><div className="login-copy"><span>PORTAIL ÉQUIPE</span><h1>Heureux de vous revoir.</h1><p>Connectez-vous pour piloter vos opérations.</p></div><form onSubmit={submit}><label>Adresse e-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="nom@greenfastauto.ci" required/></label><label>Mot de passe<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••" required/></label>{error&&<p className="error">{error}</p>}<button className="primary">Se connecter <ArrowRight size={18}/></button></form><p className="secure">Accès sécurisé · Abidjan, Côte d’Ivoire</p></div></main>}
function Brand(){return <div className="brand"><div className="brandmark"><CarFront size={21}/></div><div><strong>GREEN FAST</strong><small>AUTO MANAGEMENT</small></div></div>}
function App(){const[session,setSession]=useState<Session|null>(null);const[checking,setChecking]=useState(true);const[demo,setDemo]=useState(false);useEffect(()=>{if(!supabase){setChecking(false);setDemo(true);return}supabase.auth.getSession().then(({data})=>{setSession(data.session);setChecking(false)});const{data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);if(checking)return <div className="loader"><CarFront/></div>;if(!session&&!demo)return <Login/>;return <Dashboard session={session}/>}

function Dashboard({session}:{session:Session|null}){const[lang,setLang]=useState<Lang>('fr');const[role,setRole]=useState<Role>((session?.user.user_metadata.role as Role)||'manager');const[active,setActive]=useState('dashboard');const[mobile,setMobile]=useState(false);const t=copy[lang];const nav=lang==='fr'?navFr:navZh;const available=useMemo(()=>allNav.filter(([id])=>access[role].includes(id)),[role]);return <div className="shell">
 <aside className={mobile?'open':''}><div className="side-head"><Brand/><button className="icon close" onClick={()=>setMobile(false)}><X/></button></div><nav>{available.map(([id,Icon])=><button className={active===id?'active':''} onClick={()=>{setActive(id);setMobile(false)}} key={id}><Icon size={19}/><span>{nav[id]}</span>{id==='crm'&&<b>12</b>}</button>)}</nav><div className="side-foot"><div className="help"><Sparkles size={20}/><strong>Besoin d’aide ?</strong><small>Contactez l’administrateur</small></div><button className="profile"><span>AD</span><div><strong>{session?.user.user_metadata.full_name||'Amélie Diallo'}</strong><small>{role[0].toUpperCase()+role.slice(1)}</small></div><MoreHorizontal size={18}/></button></div></aside>
 <div className="content"><header><button className="icon menub" onClick={()=>setMobile(true)}><Menu/></button><div className="search"><Search size={18}/><input placeholder={t.search}/><kbd>⌘ K</kbd></div><div className="tools"><select aria-label={t.role} value={role} onChange={e=>setRole(e.target.value as Role)}>{roles.map(r=><option key={r}>{r}</option>)}</select><button className="lang" onClick={()=>setLang(lang==='fr'?'zh':'fr')}>{lang==='fr'?'中文':'FR'}</button><button className="icon bell"><Bell size={19}/><i/></button>{session&&<button className="icon" title={t.signout} onClick={()=>supabase?.auth.signOut()}><LogOut size={18}/></button>}</div></header>
 {active==='dashboard'?<DashboardHome t={t}/>:<ModulePage title={nav[active]} id={active}/>}</div>{mobile&&<div className="scrim" onClick={()=>setMobile(false)}/>}</div>}

function DashboardHome({t}:{t:typeof copy.fr}){return <main className="main"><section className="welcome"><div><p>SAMEDI 22 AOÛT</p><h1>{t.welcome} <span>👋🏾</span></h1><h2>{t.today}</h2></div><div className="welcome-actions"><button className="secondary"><CalendarDays size={17}/>{t.week}<ChevronDown size={15}/></button><button className="primary">{t.quick}<ChevronDown size={16}/></button></div></section><section className="stats"><Stat icon={<CarFront/>} label={t.stock} value="48" note="+6 ce mois" positive/><Stat icon={<UsersRound/>} label={t.leads} value="124" note="+18,2%" positive/><Stat icon={<Check/>} label={t.sales} value="17" note="Objectif : 24"/><Stat icon={<TrendingUp/>} label={t.revenue} value="186,4 M" note="+12,5%" positive/></section><section className="grid"><div className="card performance"><CardHead title={t.performance} action={t.seeReport}/><div className="chart-info"><div><small>VENTES</small><strong>186,4 M <em>FCFA</em></strong></div><span>↗ 12,5%</span></div><BarChart/></div><div className="card tasks"><CardHead title={t.tasks} action={t.seeAll}/><Task color="orange" title="Valider le prix · Toyota RAV4" meta="Aujourd’hui · 10:30"/><Task color="purple" title="Relancer Koné Ibrahim" meta="Aujourd’hui · 14:00"/><Task color="green" title="Inspection · Hyundai Tucson" meta="Demain · 09:00"/></div><div className="card pipeline"><CardHead title={t.pipeline} action="CRM"/><div className="funnel"><Funnel n="42" label="Nouveaux" w="100%"/><Funnel n="28" label="Qualifiés" w="82%"/><Funnel n="16" label="Négociation" w="61%"/><Funnel n="9" label="Confirmés" w="43%"/></div></div><div className="card recent"><CardHead title={t.recent} action={t.viewInventory}/><Vehicle initials="TX" name="Toyota Land Cruiser Prado" meta="2021 · Diesel · Automatique" price={38500000} status="Disponible"/><Vehicle initials="MT" name="Mitsubishi Pajero Sport" meta="2022 · Diesel · Automatique" price={31400000} status="Réservé"/><Vehicle initials="HN" name="Hyundai Santa Fe" meta="2020 · Essence · Automatique" price={22750000} status="Inspection"/></div></section></main>}
function Stat({icon,label,value,note,positive}:{icon:React.ReactNode,label:string,value:string,note:string,positive?:boolean}){return <div className="stat"><div className="stat-top"><span>{icon}</span><MoreHorizontal/></div><p>{label}</p><strong>{value}</strong><small className={positive?'pos':''}>{note}</small></div>}
function CardHead({title,action}:{title:string,action:string}){return <div className="card-head"><h3>{title}</h3><button>{action}<ArrowRight size={15}/></button></div>}
function BarChart(){const vals=[38,52,46,63,58,78,68,89,73,92,80,96];return <div className="bars">{vals.map((v,i)=><div key={i}><i style={{height:`${v}%`}} className={i===11?'hot':''}/><small>{['S1','','S2','','S3','','S4','','S5','','S6',''][i]}</small></div>)}</div>}
function Task({color,title,meta}:{color:string,title:string,meta:string}){return <div className="task"><button className={'check '+color}/><div><strong>{title}</strong><small><Clock3 size={13}/>{meta}</small></div><MoreHorizontal size={18}/></div>}
function Funnel({n,label,w}:{n:string,label:string,w:string}){return <div className="funnel-row"><span>{label}</span><div><i style={{width:w}}/><strong>{n}</strong></div></div>}
function Vehicle({initials,name,meta,price,status}:{initials:string,name:string,meta:string,price:number,status:string}){return <div className="vehicle"><div className="vehicle-img">{initials}</div><div className="vehicle-info"><strong>{name}</strong><small>{meta}</small></div><b>{money(price)}</b><span className={'pill '+status.toLowerCase()}>{status}</span><MoreHorizontal size={18}/></div>}
function ModulePage({title,id}:{title:string,id:string}){return <main className="main module"><div className="module-title"><div><p>GREEN FAST AUTO</p><h1>{title}</h1><h2>Centralisez vos opérations et gardez votre équipe alignée.</h2></div><button className="primary">+ Créer</button></div><div className="card empty"><div className="empty-icon">{id==='inventory'?<CarFront/>:<ClipboardCheck/>}</div><h3>{title}</h3><p>Les données de ce module sont protégées selon votre rôle et synchronisées avec Supabase.</p><button className="secondary">Configurer la première entrée</button></div></main>}
export default App
