-- LIVE SALES AI V0.6 — normalized LIVE provider event layer
-- Supports simulation today and future official/authorized providers without changing downstream AI contracts.

create table if not exists public.live_provider_events (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.live_sessions(id) on delete cascade,
  provider text not null check (provider in ('simulation','tiktok_authorized')),
  event_type text not null check (event_type in ('viewer_join','comment','like','share','follow','viewer_count','watch_time','gift')),
  provider_event_id text,
  occurred_at timestamptz not null default now(),
  received_at timestamptz not null default now(),
  is_simulated boolean not null default true,
  payload jsonb not null default '{}'::jsonb
);

create unique index if not exists live_provider_events_provider_event_uidx
  on public.live_provider_events(provider, provider_event_id)
  where provider_event_id is not null;
create index if not exists live_provider_events_session_time_idx
  on public.live_provider_events(session_id, occurred_at desc);
create index if not exists live_provider_events_type_time_idx
  on public.live_provider_events(event_type, occurred_at desc);

alter table public.live_provider_events enable row level security;

drop policy if exists live_provider_events_select_policy on public.live_provider_events;
create policy live_provider_events_select_policy on public.live_provider_events
for select to authenticated using (
  exists (
    select 1 from public.live_sessions ls
    where ls.id=live_provider_events.session_id
      and (
        ls.presenter_id=auth.uid()
        or exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in ('owner','manager'))
      )
  )
);

drop policy if exists live_provider_events_insert_policy on public.live_provider_events;
create policy live_provider_events_insert_policy on public.live_provider_events
for insert to authenticated with check (
  exists (
    select 1 from public.live_sessions ls
    where ls.id=live_provider_events.session_id
      and (
        ls.presenter_id=auth.uid()
        or exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in ('owner','manager'))
      )
  )
);

create or replace view public.live_provider_health
with (security_invoker=true) as
select
  ls.id as session_id,
  ls.presenter_id,
  count(lpe.id)::int as events,
  count(lpe.id) filter (where lpe.is_simulated)::int as simulated_events,
  count(lpe.id) filter (where not lpe.is_simulated)::int as authorized_events,
  max(lpe.received_at) as last_event_received_at,
  case when count(lpe.id)=0 then 'no_data'
       when count(lpe.id) filter (where not lpe.is_simulated)>0 then 'authorized_data_present'
       else 'simulation_only' end as provider_status
from public.live_sessions ls
left join public.live_provider_events lpe on lpe.session_id=ls.id
group by ls.id,ls.presenter_id;

grant select on public.live_provider_health to authenticated;

comment on table public.live_provider_events is
'Normalized LIVE event ingestion boundary. Simulation events must remain marked is_simulated=true. Authorized TikTok data may be written only through a verified official/partner integration.';
